import { Card } from "@/src/types/cards";

export const CARDS_BT01: Card[] = [
  {
    name: "นนทก นิ้วเพชร",
    type: "Avatar",
    soi: 1,
    print: "BT01-001",
    rare: "UR",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol เทพ} : ทำลาย Avatar ใบที่เป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ยักษ์",
    color: "แดง",
  },
  {
    name: "นนทก นิ้วเพชร",
    type: "Avatar",
    soi: 1,
    print: "BT01-001",
    rare: "SCR",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol เทพ} : ทำลาย Avatar ใบที่เป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ยักษ์",
    color: "แดง",
  },
  {
    name: "นนทก นิ้วเพชร",
    type: "Avatar",
    soi: 1,
    print: "BT01-001",
    rare: "CBR",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol เทพ} : ทำลาย Avatar ใบที่เป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ยักษ์",
    color: "แดง",
  },
  {
    name: "นนทก นิ้วเพชร",
    type: "Avatar",
    soi: 1,
    print: "BT01-001",
    rare: "PR",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar {symbol เทพ} : ทำลาย Avatar ใบที่เป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ยักษ์",
    color: "แดง",
  },
  {
    name: "ปื้ด เด็กเปรต",
    type: "Avatar",
    soi: 1,
    print: "BT01-002",
    rare: "SR",
    mainEffect: "ต่อเนื่อง การ์ดใบนี้ เพิ่ม POWER  ตามจำนวน LIFE Card ฝ่ายเรา ที่ถูกหงายอยู่ ใบละ 2",
    cost: 4,
    gem: 0,
    power: 0,
    symbol: "เปรต",
    color: "แดง",
  },
  {
    name: "ปื้ด เด็กเปรต",
    type: "Avatar",
    soi: 1,
    print: "BT01-002",
    rare: "SCR",
    mainEffect: "ต่อเนื่อง การ์ดใบนี้ เพิ่ม POWER  ตามจำนวน LIFE Card ฝ่ายเรา ที่ถูกหงายอยู่ ใบละ 2",
    cost: 4,
    gem: 0,
    power: 0,
    symbol: "เปรต",
    color: "แดง",
  },
  {
    name: "พระเวสสุกรรม",
    type: "Avatar",
    soi: 1,
    print: "BT01-003",
    rare: "R",
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck) 5 ใบ นำการ์ด Land Magic 1 ใบ จากที่ สอดแนม ขึ้นมือ จากนั้นนำการ์ดที่เหลือเรียงและนำไปไว้ใต้ Deck",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "หนุมาน",
    type: "Avatar",
    soi: 1,
    print: "BT01-004",
    rare: "C",
    mainEffect: "ต่อเนื่อง การ์ดใบนี้ เพิ่ม POWER  ตามจำนวน Avatar {symbol เทพ} บนสนามฝ่ายเรา ใบละ 1",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "สัตว์",
    color: "แดง",
  },
  {
    name: "อู๊ดลูกเสือ",
    type: "Avatar",
    soi: 1,
    print: "BT01-005",
    rare: "C",
    mainEffect: "อัตโนมัติ สั่งใช้ เมื่อ Avatar ตัวนี้ถูกโจมตี Avatar ใบอื่น บนสนามเรา 1 ใบ : ยกเลิกการโจมตีนั้น",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ชาวบ้านขายน้ำ",
    type: "Avatar",
    soi: 1,
    print: "BT01-006",
    rare: "SR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : นำ Modification Magic \"น้ำ\" 1 ใบ จาก Deck เรา ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ชาวบ้านขายน้ำ",
    type: "Avatar",
    soi: 1,
    print: "BT01-006",
    rare: "SCR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : นำ Modification Magic \"น้ำ\" 1 ใบ จาก Deck เรา ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "แม่กบ",
    type: "Avatar",
    soi: 1,
    print: "BT01-007",
    rare: "C",
    mainEffect: "อัตโนมัติ ในช่วง End Phase ของเรา : Avatar ใบนี้ POWER +1",
    cost: 3,
    gem: 1,
    power: 1,
    symbol: "สัตว์",
    color: "แดง",
  },
  {
    name: "รัททาทุย นางพญา",
    type: "Avatar",
    soi: 1,
    print: "BT01-008",
    rare: "UR",
    mainEffect: "ในช่วง Draw Phase แรกของเรา เราสามารถนำการ์ดใบนี้จาก Deck ขึ้นมือแทนการจั่วได้",
    cost: 2,
    gem: 2,
    power: 4,
    symbol: "รัททาทุย",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "รัททาทุย นางพญา",
    type: "Avatar",
    soi: 1,
    print: "BT01-008",
    rare: "SCR",
    mainEffect: "ในช่วง Draw Phase แรกของเรา เราสามารถนำการ์ดใบนี้จาก Deck ขึ้นมือแทนการจั่วได้",
    cost: 2,
    gem: 2,
    power: 4,
    symbol: "รัททาทุย",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "รัททาทุย พ่อพันธุ์",
    type: "Avatar",
    soi: 1,
    print: "BT01-009",
    rare: "R",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ถ้าบน Avatar Zone ฝ่ายเรามี \"รัททาทุย นางพญา\" สามารถอัญเชิญ Avatar ที่มีชื่อ \"รัททาทุย\" จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรากี่ใบก็ได้ โดย Cost รวมกันไม่เกิน 5 จากนั้นสับ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "รัททาทุย",
    color: "ฟ้า",
  },
  {
    name: "รัททาทุย",
    type: "Avatar",
    soi: 1,
    print: "BT01-010",
    rare: "C",
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\n#การ์ดใบนี้ สามารถใส่ใน Deck จำนวนได้มากสุด 50 ใบ",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: "รัททาทุย",
    color: "ฟ้า",
    customLimit: 50,
  },
  {
    name: "แมลงปอเลื่อยยนต์",
    type: "Avatar",
    soi: 1,
    print: "BT01-011",
    rare: "R",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) :  ทำลาย MAGIC บนสนาม 1ใบ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "แมลง",
    color: "ฟ้า",
  },
  {
    name: "ลูกแม่ศรีนวล",
    type: "Avatar",
    soi: 1,
    print: "BT01-012",
    rare: "C",
    mainEffect: "คำสั่งเสีย (เมื่อAvatarใบนี้ถูกทำลาย) : นำ LIFE Card ที่หงายอยู่ใบบนสุด กลับมาคว่ำ 1 ใบ",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: "สัตว์",
    color: "ฟ้า",
  },
  {
    name: "พ่อบุญใหญ่",
    type: "Avatar",
    soi: 1,
    print: "BT01-013",
    rare: "SR",
    mainEffect: "คำสั่งเสีย (เมื่อAvatarใบนี้ถูกทำลาย) : เลือก Avatar สัตว์ Cost ไม่เกิน 4 ในนรกเรา นำกลับขึ้นมือ",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "สัตว์",
    color: "ฟ้า",
  },
  {
    name: "พ่อบุญใหญ่",
    type: "Avatar",
    soi: 1,
    print: "BT01-013",
    rare: "SCR",
    mainEffect: "คำสั่งเสีย (เมื่อAvatarใบนี้ถูกทำลาย) : เลือก Avatar สัตว์ Cost ไม่เกิน 4 ในนรกเรา นำกลับขึ้นมือ",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "สัตว์",
    color: "ฟ้า",
  },
  {
    name: "จ่ามะนาว",
    type: "Avatar",
    soi: 1,
    print: "BT01-014",
    rare: "SR",
    mainEffect: "โล่มนุษย์ (เมื่อฝ่ายตรงข้ามประกาศโจมตี เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และเปลี่ยนเป้าหมายการโจมตีมาที่การ์ดใบนี้แทน)",
    cost: 3,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "จ่ามะนาว",
    type: "Avatar",
    soi: 1,
    print: "BT01-014",
    rare: "SCR",
    mainEffect: "โล่มนุษย์ (เมื่อฝ่ายตรงข้ามประกาศโจมตี เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และเปลี่ยนเป้าหมายการโจมตีมาที่การ์ดใบนี้แทน)",
    cost: 3,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "นายนิรยบาล \"เต๋า\"",
    type: "Avatar",
    soi: 1,
    print: "BT01-015",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกส่งลงนรกด้วยผลของ ธรณีสูบ(การ์ดตกนรกจาก Deck) : ทั้งสองฝ่าย ธรณีสูบ 2ใบ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "สุวรรณ",
    type: "Avatar",
    soi: 1,
    print: "BT01-016",
    rare: "SR",
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck) 5 ใบ  สามารถนำการ์ด \"พญายม\" หรือ \"นายนิรยบาล\" 1 ใบ จากที่สอดแนม ขึ้นมือ การ์ดที่เหลือเรียงและนำไปไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "สุวรรณ",
    type: "Avatar",
    soi: 1,
    print: "BT01-016",
    rare: "SCR",
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck) 5 ใบ  สามารถนำการ์ด \"พญายม\" หรือ \"นายนิรยบาล\" 1 ใบ จากที่สอดแนม ขึ้นมือ การ์ดที่เหลือเรียงและนำไปไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "ทศกัณฐ์ยักษ์ที่---เมียพระอิศวร",
    type: "Avatar",
    soi: 1,
    print: "BT01-017",
    rare: "UR",
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สามารถเลือก Avatar บน Avatar Zone ฝ่ายตรงข้าม 1 ใบ เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเราในสภาพนอน",
    cost: 4,
    gem: 3,
    power: 5,
    symbol: "ยักษ์",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "ทศกัณฐ์ที่---เมียพระอิศวร",
    type: "Avatar",
    soi: 1,
    print: "BT01-017",
    rare: "SCR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สามารถเลือก Avatar บน Avatar Zone ฝ่ายตรงข้าม 1 ใบ เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเราในสภาพนอน",
    cost: 4,
    gem: 3,
    power: 5,
    symbol: "ยักษ์",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "นีโม่",
    type: "Avatar",
    soi: 1,
    print: "BT01-018",
    rare: "R",
    mainEffect: "เมื่อการ์ดใบนี้ตกนรกด้วยผลของ ธรณีสูบ(การ์ดตกนรกจาก Deck) : นำการ์ดใบนี้กลับ Deck แล้วสับ",
    cost: 0,
    gem: 3,
    power: 0,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "ยมทูต",
    type: "Avatar",
    soi: 1,
    print: "BT01-019",
    rare: "C",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของเด็ค) 5 ใบ สามารถนำการ์ด \"สิมพลีนรก\" 1 ใบ จากที่สอดแนม ขึ้นมือ การ์ดที่เหลือเรียงและนำไปไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "ศาลพระภูมิ",
    type: "Avatar",
    soi: 1,
    print: "BT01-020",
    rare: "SR",
    mainEffect:
      "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : อัญเชิญ Avatar {รูป symbol ผี} จากใน Deck 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck\n\nต่อเนื่อง ตราบเท่าที่มีการ์ด Avatar {รูป symbol ผี} ใบอื่นบน Avatar Zone ฝ่ายเรา อีกฝ่ายจะไม่สามารถเลือก Avatar \"ศาลพระภูมิ\" เป็นเป้าหมายการโจมตีได้",
    cost: 4,
    gem: 1,
    power: 2,
    symbol: "ผี",
    color: "ม่วง",
  },
  {
    name: "ศาลพระภูมิ",
    type: "Avatar",
    soi: 1,
    print: "BT01-020",
    rare: "SCR",
    mainEffect:
      "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : อัญเชิญ Avatar {รูป symbol ผี} จากใน Deck 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck\n\nต่อเนื่อง ตราบเท่าที่มีการ์ด Avatar {รูป symbol ผี} ใบอื่นบน Avatar Zone ฝ่ายเรา อีกฝ่ายจะไม่สามารถเลือก Avatar \"ศาลพระภูมิ\" เป็นเป้าหมายการโจมตีได้",
    cost: 4,
    gem: 1,
    power: 2,
    symbol: "ผี",
    color: "ม่วง",
  },
  {
    name: "สารวัตร ตำรวจสัมภเวสี",
    type: "Avatar",
    soi: 1,
    print: "BT01-021",
    rare: "C",
    mainEffect: "จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : สามารถนำการ์ด \"ตำรวจสัมภเวสี\" จาก Deck ขึ้นมือได้ 1 ใบ จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "ผี",
    color: "ม่วง",
  },
  {
    name: "ตึก",
    type: "Avatar",
    soi: 1,
    print: "BT01-022",
    rare: "R",
    mainEffect: "",
    cost: 6,
    gem: 4,
    power: 9,
    symbol: "หุ่นยนต์",
    color: "แดง",
    ex: "Only #1",
  },
  {
    name: "ลูกกบ",
    type: "Avatar",
    soi: 1,
    print: "BT01-023",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: "สัตว์",
    color: "แดง",
  },
  {
    name: "พี่โด 2.0",
    type: "Avatar",
    soi: 1,
    print: "BT01-024",
    rare: "R",
    mainEffect: "",
    cost: 8,
    gem: 2,
    power: 8,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "เทวดาตำรวจ",
    type: "Avatar",
    soi: 1,
    print: "BT01-025",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "ครูวีรชัย",
    type: "Avatar",
    soi: 1,
    print: "BT01-026",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "ลูกค้าชาบู",
    type: "Avatar",
    soi: 1,
    print: "BT01-027",
    rare: "R",
    mainEffect: "",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "เจ้าของร้านชาบู",
    type: "Avatar",
    soi: 1,
    print: "BT01-028",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "จ่าแดงเดือด",
    type: "Avatar",
    soi: 1,
    print: "BT01-029",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "เฟนริล",
    type: "Avatar",
    soi: 1,
    print: "BT01-030",
    rare: "R",
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: "สัตว์",
    color: "ม่วง",
  },
  {
    name: "จอมมังการ์ด",
    type: "Avatar",
    soi: 1,
    print: "BT01-031",
    rare: "C",
    mainEffect: "",
    cost: 5,
    gem: 1,
    power: 6,
    symbol: "สัตว์",
    color: "ม่วง",
  },
  {
    name: "นายนิรยบาล ตัวใหญ่พิเศษ",
    type: "Avatar",
    soi: 1,
    print: "BT01-032",
    rare: "C",
    mainEffect: "",
    cost: 9,
    gem: 4,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "แบงค์ เทคนิคประทุมทู",
    type: "Avatar",
    soi: 1,
    print: "BT01-033",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "กาลจักร",
    type: "Avatar",
    soi: 1,
    print: "BT01-034",
    rare: "SR",
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: "ยักษ์",
    color: "เขียว",
  },
  {
    name: "ประมาทร่วม",
    type: "Magic",
    soi: 1,
    print: "BT01-035",
    rare: "C",
    mainEffect: "ผู้เล่นทุกคน ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 3 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "เมตตาระยะยาว",
    type: "Magic",
    soi: 1,
    print: "BT01-036",
    rare: "UR",
    mainEffect: "ทำลาย Avatar บนสนามอีกฝ่ายทุกใบ",
    subtype: "Normal",
    cost: 0,
    symbol: "เทพ",
    ex: "Only #1",
  },
  {
    name: "เมตตาระยะยาว",
    type: "Magic",
    soi: 1,
    print: "BT01-036",
    rare: "SCR",
    mainEffect: "ทำลาย Avatar บนสนามอีกฝ่ายทุกใบ",
    subtype: "Normal",
    cost: 0,
    symbol: "เทพ",
    ex: "Only #1",
  },
  {
    name: "เพื่อลูกค้า",
    type: "Magic",
    soi: 1,
    print: "BT01-037",
    rare: "R",
    mainEffect: "เซ่นไหว้ (ทำลายจากสนามลงนรก) Avatar \"Symbol สัตว์\" บน Avatar Zone ฝ่ายเรา 1 ใบ : จั่วการ์ดจาก Deck 3 ใบ จากนั้นในเทิร์นนี้จะอัญเชิญได้แค่ Avatar \"Symbol สัตว์\"",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ความเจริญ",
    type: "Magic",
    soi: 1,
    print: "BT01-038",
    rare: "SR",
    mainEffect: "จั่วการ์ดจาก Deck เรา 2 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ความเจริญ",
    type: "Magic",
    soi: 1,
    print: "BT01-038",
    rare: "SCR",
    mainEffect: "จั่วการ์ดจาก Deck เรา 2 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "เจ้ากล้าดียังไง",
    type: "Magic",
    soi: 1,
    print: "BT01-039",
    rare: "R",
    mainEffect: "เมื่อฝ่ายตรงข้ามประกาศโจมตี : ส่ง Avatar ที่ประกาศโจมตีลงนรก",
    subtype: "React",
    cost: 2,
    symbol: "เทพ",
  },
  {
    name: "หมอมาแล้วววว",
    type: "Magic",
    soi: 1,
    print: "BT01-040",
    rare: "C",
    mainEffect: "เมื่อ Avatar จะถูกทำลาย : Avatar ใบนั้นจะไม่ถูกทำลาย",
    subtype: "React",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "ชายจากอนาคต",
    type: "Magic",
    soi: 1,
    print: "BT01-041",
    rare: "UR",
    mainEffect: "เมื่อมีการใช้ Magic Card : ยกเลิกการใช้ Magic Card ใบนั้น",
    subtype: "React",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "ชายจากอนาคต",
    type: "Magic",
    soi: 1,
    print: "BT01-041",
    rare: "SCR",
    mainEffect: "เมื่อมีการใช้ Magic Card : ยกเลิกการใช้ Magic Card ใบนั้น",
    subtype: "React",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "ริกกี้ นักปลอมแปลง",
    type: "Magic",
    soi: 1,
    print: "BT01-042",
    rare: "UR",
    mainEffect: "เมื่อ Avatar บนสนามของเราถูกทำลายจากการต่อสู้ สามารถใช้การ์ดใบนี้ได้ : เปลี่ยนการควบคุม Avatar ที่อยู่ในสภาพนอน จากบนสนามอีกฝ่ายมาบนสนามฝ่ายเรา แล้วนำการ์ดใบนี้ไปเป็นModification Magic ถ้าการ์ดใบนี้ถูกทำลาย ส่ง Avatar กลับขึ้นมือเจ้าของ",
    subtype: "React",
    cost: 0,
    symbol: "แมลง",
  },
  {
    name: "ริกกี้ นักปลอมแปลง",
    type: "Magic",
    soi: 1,
    print: "BT01-042",
    rare: "SCR",
    mainEffect: "เมื่อ Avatar บนสนามของเราถูกทำลายจากการต่อสู้ สามารถใช้การ์ดใบนี้ได้ : เปลี่ยนการควบคุม Avatar ที่อยู่ในสภาพนอน จากบนสนามอีกฝ่ายมาบนสนามฝ่ายเรา แล้วนำการ์ดใบนี้ไปเป็นModification Magic ถ้าการ์ดใบนี้ถูกทำลาย ส่ง Avatar กลับขึ้นมือเจ้าของ",
    subtype: "React",
    cost: 0,
    symbol: "แมลง",
  },
  {
    name: "น้ำชูกำลัง",
    type: "Magic",
    soi: 1,
    print: "BT01-043",
    rare: "SR",
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้จะกลับมาเป็นสภาพตื่น ในช่วง End Phase",
    subtype: "Modification",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "รั้วของชาติ",
    type: "Magic",
    soi: 1,
    print: "BT01-044",
    rare: "C",
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ โล่มนุษย์ (เมื่อฝ่ายตรงข้ามประกาศโจมตี เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และเปลี่ยนเป้าหมายการโจมตีมาที่การ์ดใบนี้แทน)",
    subtype: "Modification",
    cost: 2,
    symbol: "ทหาร",
    dropRate: "3.00%",
  },
  {
    name: "ตีแม่",
    type: "Magic",
    soi: 1,
    print: "BT01-045",
    rare: "C",
    mainEffect:
      "POWER +2 ให้กับ Avatar ที่สวมใส่การ์ดใบนี้\n\nเมื่อการ์ดใบนี้ตกลงสู่นรก หงาย LIFE Card ใบบนสุดฝ่ายเรา 1 ใบ",
    subtype: "Modification",
    cost: 2,
    symbol: "คน",
    dropRate: "3.00%",
  },
  {
    name: "ตีพ่อ",
    type: "Magic",
    soi: 1,
    print: "BT01-046",
    rare: "C",
    mainEffect:
      "ใน Battle Phase ถ้า Avatar ที่สวมใส่การ์ดใบนี้ทำลาย Avatar อีกฝ่ายสำเร็จ : สามารถกลับมาสภาพตื่นได้ 1 ครั้ง\n\nเมื่อการ์ดใบนี้ตกลงสู่นรก เมื่อการ์ดใบนี้ตกลงสู่นรก หงาย LIFE Card ใบบนสุดฝ่ายเรา 1 ใบ",
    subtype: "Modification",
    cost: 3,
    symbol: "คน",
    dropRate: "3.00%",
  },
  {
    name: "เขาไกรลาสเอียง",
    type: "Magic",
    soi: 1,
    print: "BT01-047",
    rare: "R",
    mainEffect: "เมื่อมีการประกาศโจมตี : ฝ่ายที่ประกาศโจมตี ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ",
    subtype: "Land",
    cost: 1,
    symbol: "เทพ",
    dropRate: "1.00%",
  },
  {
    name: "ทุ่งนาแดนนี้(ไม่มีความหมาย)",
    type: "Magic",
    soi: 1,
    print: "BT01-048",
    rare: "R",
    mainEffect: "Avatar เผ่าแมลง สัตว์ รัททาทุย และมนุษย์ POWER +1",
    subtype: "Land",
    cost: 2,
    symbol: "ต้นไม้",
    dropRate: "1.00%",
  },
  {
    name: "มวยทะเลลลลลล",
    type: "Magic",
    soi: 1,
    print: "BT01-049",
    rare: "C",
    mainEffect: "ต่างฝ่ายต่างสั่ง Avatar โจมตีได้แค่ 1 ตัวต่อเทิร์น โดยที่การ์ดใบนี้จะอยู่บนสนามได้แค่ 4 เทิร์น",
    subtype: "Land",
    cost: 1,
    symbol: "ฤษี",
    dropRate: "3.00%",
  },
  {
    name: "โรงบาล",
    type: "Magic",
    soi: 1,
    print: "BT01-050",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดจากมือ 1 ใบ : เลือกการ์ด Avatar จากในนรก 1 ใบที่ Cost ไม่เกิน 3 ขึ้นมือได้ ในเทิร์นนี้การ์ดที่ขึ้นมือจากความสามารถ\"โรงบาล\"จะไม่สามารถอัญเชิญและไม่สามารถใช้ความสามารถได้ รวมถึงการ์ดชื่อเดียวกันกับที่ขึ้นมือทั้งหมด",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "1.00%",
  },
  {
    name: "ไม่นะ โปโป้ !",
    type: "Life",
    soi: 1,
    print: "BT01-051",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไอ้เลวเอ้ย! มึงปล่อยให้โปโป้ตาย โปโป้ทำอะไรผิดวะ มึงเลยปล่อยให้โปโป้ตาย ทำไม? อ๋อ... ก็แค่สละ 1 ชีวิต ไม่เป็นไรหรอกเนอะ...ไอ้คนใจดำเอ้ย!",
    dropRate: "3.00%",
  },
  {
    name: "ไม่นะ พ่อ !",
    type: "Life",
    soi: 1,
    print: "BT01-052",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "คุณปล่อยให้นาย สันทนัท เสาหลักของครอบครัวต้องตาย คุณทำให้เมียเขาเป็นหม้ายและลูก3คนต้องกำพร้าพ่อ น่าละอายจริงๆ ไอ้เลว",
    dropRate: "3.00%",
  },
  {
    name: "ไม่นะ แม่ !",
    type: "Life",
    soi: 1,
    print: "BT01-053",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "คุณเพิ่งปล่อยให้นาง กัลยา แม่ที่ทำแกงส้มเพื่อต้อนรับลูกสาวที่เข้ากรุงไปทำงานกว่า 2 ปีต้องตาย และดูเหมือนว่าเย็นนี้ ลูกของเธอต้องกินข้าวคนเดียวทั้งน้ำตา",
    dropRate: "3.00%",
  },
  {
    name: "ไม่นะ ลูก !",
    type: "Life",
    soi: 1,
    print: "BT01-054",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "คุณเพิ่งทำลายสิ่งที่เรียกว่า \"อนาคตของชาติ\" และในวันที่คุณป่วยใกล้ตาย และโรงพยาบาลแจ้งคุณว่า \"โอ้ไม่! เราไม่เหลือหมอเก่งๆแล้ว\"ก็ขอให้รู้เอาไว้ว่าเป็นความผิดของมึง",
    dropRate: "3.00%",
  },
  {
    name: "ไม่นะ เบิ้ม !",
    type: "Life",
    soi: 1,
    print: "BT01-055",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไม่ต้องห่วง คุณไม่ได้ปล่อยเบิ้มตาย ผลชันสูตรพบว่า เขาเป็นโรคตับแข็งจากการดื่มสุรา เพราะฉะนั้นดื่มเหล้าแต่พอเหมาะเพื่อไม่ให้เบิ้มต้องตายฟรี",
    dropRate: "3.00%",
  },
];
