import { Card } from "@/src/types/cards";

export const CARDS_BT04: Card[] = [
  {
    name: "จอมหักกระดูก",
    type: "Avatar",
    soi: 1,
    print: "BT04-001",
    rare: "UR",
    mainEffect:
      "โล่มนุษย์\n\nอัตโนมัติ เมื่อ Avatar ใบนี้ต่อสู้กับ Avatar ของฝ่ายตรงข้าม : POWER ของ Avatar ที่ต่อสู้ด้วยจะถูกปรับเป็น POWER ตั้งต้น จนจบการต่อสู้นั้น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: "เอเลี่ยน",
    color: "แดง",
  },
  {
    name: "จอมหักกระดูก",
    type: "Avatar",
    soi: 1,
    print: "BT04-001",
    rare: "SCR",
    mainEffect:
      "\"โล่มนุษย์\"\n\nอัตโนมัติ เมื่อ Avatar ใบนี้ต่อสู้กับ Avatar ของฝ่ายตรงข้าม : POWER ของ Avatar ที่ต่อสู้ด้วยจะถูกปรับเป็น POWER ตั้งต้น จนจบการต่อสู้นั้น",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: "เอเลี่ยน",
    color: "แดง",
  },
  {
    name: "ครููสงบ กล้ามโต",
    type: "Avatar",
    soi: 1,
    print: "BT04-002",
    rare: "C",
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้ประกาศโจมตี : สามารถทำลาย Modification Magic ของฝ่ายตรงข้าม 1 ใบ",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ไอ้นัท - คนใจเด็ด",
    type: "Avatar",
    soi: 1,
    print: "BT04-003",
    rare: "R",
    mainEffect: "ต่อเนื่อง Avatar ใบนี้จะไม่ถูกเปลี่ยนการควบคุม ยกเว้นจากความสามารถของ อีช่า - สาวน้อยคนเก่ง",
    cost: 1,
    gem: 2,
    power: 3,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "อีช่า - สาวน้อยคนเก่ง",
    type: "Avatar",
    soi: 1,
    print: "BT04-004",
    rare: "R",
    mainEffect: "จุติ : เซ่นไหว้ Avatar ใบอื่นใน Avatar Zone 1 ใบ : เลือก Avatar symbol {คน} , {เทพ} , {นรก} บน Avatar Zone ของฝ่ายตรงข้าม 1 ใบ เปลี่ยนการควบคุมมาบน Avatar Zone ฝ่ายเรา",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ยายกบ 1954",
    type: "Avatar",
    soi: 1,
    print: "BT04-005",
    rare: "C",
    mainEffect:
      "Avatar ใบนี้ไม่สามารถอัญเชิญแบบจ่าย Cost ได้ แต่สามารถอัญเชิญได้โดยการส่ง Avatar \"กบ\" ที่ได้รับผล เพิ่ม POWER ไปแล้ว 3 ครั้งหรือมากกว่า บน Avatar Zone ฝ่ายเราลงนรก\n\nPOWER ของ Avatar ใบนี้ เพิ่มขึ้นตาม POWER ของ Avatar \"กบ\" ที่ส่งลงนรกเพื่ออัญเชิญ",
    cost: 0,
    gem: 1,
    power: 2,
    symbol: "สัตว์",
    color: "แดง",
  },
  {
    name: "แบงค์ทีสต้า นักมวยปล้ำ",
    type: "Avatar",
    soi: 1,
    print: "BT04-006",
    rare: "R",
    mainEffect: "สามัคคี",
    cost: 2,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ราม และ วิโรจน์",
    type: "Avatar",
    soi: 1,
    print: "BT04-007",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้  เลือกปฎิบัติ :\n\n1) Avatar ใบนี้ POWER +2 จนถึง End Phase ต่อไปของฝ่ายตรงข้าม\n\n2) หากเทิร์นนี้ยังไม่มีการใช้ Modification Magic : นำ Modification Magic 1 ใบ จาก นรกฝ่ายเรา มาสวมใส่ที่ Avatar ใบนี้ และนับว่าเป็นการใช้ Modification Magic\n\n#Avatar ใบนี้ เป็น Symbol สัตว์ ด้วย",
    cost: 5,
    gem: 1,
    power: 4,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ราม และ วิโรจน์",
    type: "Avatar",
    soi: 1,
    print: "BT04-007",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้  เลือกปฎิบัติ :\n\n1) Avatar ใบนี้ POWER +2 จนถึง End Phase ต่อไปของฝ่ายตรงข้าม\n\n2) หากเทิร์นนี้ยังไม่มีการใช้ Modification Magic : นำ Modification Magic 1 ใบ จาก นรกฝ่ายเรา มาสวมใส่ที่ Avatar ใบนี้ และนับว่าเป็นการใช้ Modification Magic\n\n#Avatar ใบนี้ เป็น Symbol สัตว์ ด้วย",
    cost: 5,
    gem: 1,
    power: 4,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ลูกคนรวย",
    type: "Avatar",
    soi: 1,
    print: "BT04-008",
    rare: "R",
    mainEffect: "ต่อเนื่อง POWER ของ Avatar ใบนี้จะเท่ากับจำนวนการ์ดบนมือของฝ่ายตรงข้าม",
    cost: 2,
    gem: 4,
    power: 0,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "โทมาโทจัง ไอดอลเด็กน้อย",
    type: "Avatar",
    soi: 1,
    print: "BT04-009",
    rare: "R",
    mainEffect:
      "ต่อเนื่อง เมื่อ Avatar ตัวนี้อยู่บน Avatar Zone POWER + 2 ให้ Avatar \"ไอดอล\" ใบอื่นใน Avatar Zone ฝ่ายเรา ที่สวมใส่การ์ด \"โอตะ\" อยู่\n\nต่อเนื่อง ถ้า Avatar ใบนี้ สวมใส่การ์ด \"โอตะ\" อยู่ และมี Avatar \"ไอดอล\" ชื่ออื่นในสนามฝ่ายเรา Avatar ใบนี้จะไม่สามารถถูกเลือกเป็นเป้าหมายการโจมตีได้",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ไดโนกาฬสินธุ์ - สยามโมไทรันนัส",
    type: "Avatar",
    soi: 1,
    print: "BT04-010",
    rare: "UR",
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : สอดแนม 5 ใบ นำ Avatar symbol กะปอม กี่ใบก็ได้ อัญเชิญ จุติ ลงบน Avatar zone ฝ่ายเรา นำการ์ดที่เหลือกลับเข้า Deck แล้วสับ",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "กะปอม",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "ไดโนกาฬสินธุ์ - สยามโมไทรันนัส",
    type: "Avatar",
    soi: 1,
    print: "BT04-010",
    rare: "SCR",
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : สอดแนม 5 ใบ นำ Avatar symbol กะปอม กี่ใบก็ได้ อัญเชิญ จุติ ลงบน Avatar zone ฝ่ายเรา นำการ์ดที่เหลือกลับเข้า Deck แล้วสับ",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "กะปอม",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "เทอราโนดอน จากต่างแดน",
    type: "Avatar",
    soi: 1,
    print: "BT04-011",
    rare: "C",
    mainEffect: "ต่อเนื่อง ความสามารถ สอดแนม ของ Avatar symbol {กะปอม} ฝ่ายเราทุกใบ จะสอดแนมเพิ่มอีก 1 ใบ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "กะปอม",
    color: "ฟ้า",
  },
  {
    name: "เอเลี่ยนทูตดาวอังคาร",
    type: "Avatar",
    soi: 1,
    print: "BT04-012",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ สามารถแสดงการ์ด Avatar บนมือของเรากี่ใบก็ได้ : ทำลาย Avatar ของอีกฝ่าย 1 ตัว ที่มี POWER เท่ากับ จำนวนผลรวมของ Cost ที่เราแสดง จากนั้น นำการ์ดในมือเรา 1 ใบ ให้ฝ่ายตรงข้าม",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "โอตะตัวกะปอม",
    type: "Avatar",
    soi: 1,
    print: "BT04-013",
    rare: "C",
    mainEffect:
      "เมื่อถูกทิ้งเป็นค่า Cost ให้กับ Avatar \"ไอดอล\" : สามารถนำการ์ดนี้มาสวมใส่ให้ Avatar \"ไอดอล\" ฝ่ายเรา 1 ใบ\n\nAvatar ที่สวมใส่การ์ดใบนี้ POWER +1\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar \"ไอดอล\" เท่านั้น",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "กะปอม",
    color: "ฟ้า",
  },
  {
    name: "มาวิน เซียนเบ็ด",
    type: "Avatar",
    soi: 1,
    print: "BT04-014",
    rare: "SR",
    mainEffect: "จุติ : ทิ้ง Avatar {Symbol แมลง} หรือ Avatar \" เหยื่อ \" จากมือ 1 ใบ : อัญเชิญ Avatar symbol ปลา 1 ใบ จากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "มาวิน เซียนเบ็ด",
    type: "Avatar",
    soi: 1,
    print: "BT04-014",
    rare: "SCR",
    mainEffect: "จุติ : ทิ้ง Avatar {Symbol แมลง} หรือ Avatar \" เหยื่อ \" จากมือ 1 ใบ : อัญเชิญ Avatar symbol ปลา 1 ใบ จากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "บึงทมิฬ  People - คุณดีไมส์ (ปลาดาบ)",
    type: "Avatar",
    soi: 1,
    print: "BT04-015",
    rare: "SR",
    mainEffect:
      "สามารถสั่งใช้งานความสามารถได้เมื่อมี บึงทมิฬ อยู่บน Land Magic Zone\n\nสั่งใช้ เมื่อ Avatar ใบนี้ทำลาย Avatar บน Avatar Zone ของฝ่ายตรงข้ามสำเร็จ สามารถทิ้งการ์ดบนมือ 1 ใบ Avatar ตัวนี้จะกลับมาเป็นสภาพ ตื่น",
    cost: 6,
    gem: 2,
    power: 4,
    symbol: "ปลา",
    color: "ฟ้า",
  },
  {
    name: "ริกกี้ คุณตา",
    type: "Avatar",
    soi: 1,
    print: "BT04-016",
    rare: "UR",
    mainEffect: "ต่อเนื่อง Avatar ใบนี้ไม่รับผลจากความสามารถของการ์ด Magic ฝ่ายตรงข้าม",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "แมลง",
    color: "ฟ้า",
  },
  {
    name: "ริกกี้ คุณตา",
    type: "Avatar",
    soi: 1,
    print: "BT04-016",
    rare: "SCR",
    mainEffect: "ต่อเนื่อง Avatar ใบนี้ไม่รับผลจากความสามารถของการ์ด Magic ฝ่ายตรงข้าม",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "แมลง",
    color: "ฟ้า",
    dropRate: "3.00%",
  },
  {
    name: "หมานมเย็น",
    type: "Avatar",
    soi: 1,
    print: "BT04-017",
    rare: "R",
    mainEffect: "จุติ : อัญเชิญ Avatar  \"หมา\" หรือ \"แมว\"  ที่มี {Symbol สัตว์} 1 ใบ ที่ Cost ไม่เกิน 2 จาก Deck ลง Avatar Zone ฝ่ายเรา จากนั้น สับ Deck",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "สัตว์",
    color: "ฟ้า",
  },
  {
    name: "รัททาทุย 2 หัว",
    type: "Avatar",
    soi: 1,
    print: "BT04-018",
    rare: "C",
    mainEffect:
      "โล่มนุษย์\n\nเทิร์นละครั้ง สั่งใช้ เมื่อ Avatar ใบนี้จะถูกทำลายจากการต่อสู้ สามารถให้  Avatar ใบนี้ POWER -1 :\n\nAvatar ใบนี้จะไม่ถูกทำลาย\n\nเมื่อ Avatar ตัวนี้ POWER เท่ากับ 0 ทำลาย Avatar ตัวนี้ทันที",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "รัททาทุย",
    color: "ฟ้า",
  },
  {
    name: "คนแก่สติเลอะเลือนผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-019",
    rare: "UR",
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกสอดแนมโดย Avatar \" ผู้รู้ความจริง \" อัญเชิญ Avatar ใบนี้ลงบน Avatar Zone ฝ่ายเรา\n\nเทิร์นละครั้ง สั่งใช้ : จั่วการ์ดจาก Deck เรา 1 ใบ",
    cost: 6,
    gem: 3,
    power: 5,
    symbol: "คน",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "คนแก่สติเลอะเลือนผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-019",
    rare: "SCR",
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกสอดแนมโดย Avatar \" ผู้รู้ความจริง \" อัญเชิญ Avatar ใบนี้ลงบน Avatar Zone ฝ่ายเรา\n\nเทิร์นละครั้ง สั่งใช้ : จั่วการ์ดจาก Deck เรา 1 ใบ",
    cost: 6,
    gem: 3,
    power: 5,
    symbol: "คน",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "อู๊ด ประธานผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-020",
    rare: "UR",
    mainEffect: "จุติ สอดแนม 2 ใบ หลังจากนั้นนำการ์ดที่สอดแนมเรียงไว้บนสุดหรือล่างสุดของ Deck เรา : ทำลาย Avatar อีกฝ่าย 1 ใบที่มีค่า Cost เท่ากับหรือน้อยกว่าผลรวมของ Cost การ์ดที่แสดงจากผลของการ์ดใบนี้",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อู๊ด ประธานผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-020",
    rare: "SCR",
    mainEffect: "จุติ สอดแนม 2 ใบ หลังจากนั้นนำการ์ดที่สอดแนมเรียงไว้บนสุดหรือล่างสุดของ Deck เรา : ทำลาย Avatar อีกฝ่าย 1 ใบที่มีค่า Cost เท่ากับหรือน้อยกว่าผลรวมของ Cost การ์ดที่แสดงจากผลของการ์ดใบนี้",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อู๊ด ประธานผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-020",
    rare: "PR",
    mainEffect: "จุติ : สอดแนม 2 ใบ หลังจากนั้นนำการ์ดที่สอดแนมเรียงไว้บนสุดหรือล่างสุดของ Deck เรา : ทำลาย Avatar อีกฝ่าย 1 ใบที่มีค่า Cost เท่ากับหรือน้อยกว่าผลรวมของ Cost การ์ดที่แสดงจากผลของการ์ดใบนี้",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อู๊ด ประธานผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-020",
    rare: "CBR",
    mainEffect: "จุติ : สอดแนม 2 ใบ หลังจากนั้นนำการ์ดที่สอดแนมเรียงไว้บนสุดหรือล่างสุดของ Deck เรา : ทำลาย Avatar อีกฝ่าย 1 ใบที่มีค่า Cost เท่ากับหรือน้อยกว่าผลรวมของ Cost การ์ดที่แสดงจากผลของการ์ดใบนี้",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "น้องสาม ผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-021",
    rare: "R",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้โจมตี : สอดแนม 2 ใบ เพิ่ม POWER ของการ์ดใบนี้เท่ากับ POWER ของ Avatar \"ผู้รู้ความจริง\" ทั้งหมดที่สอดแนมเจอ จากนั้นสามารถนำ การ์ด Avatar \"ผู้รู้ความจริง\" 1 ใบ จากที่สอดแนมขึ้นมือ และนำการ์ดที่เหลือ วางไว้บนหรือล่างสุดของ Deck",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "รปภ ผู้รู้ความจริง",
    type: "Avatar",
    soi: 1,
    print: "BT04-022",
    rare: "R",
    mainEffect: "จุติ : จั่วการ์ด 1 ใบจาก Deck ฝ่ายเรา จากนั้นนำการ์ด 1 ใบ จากบนมือไปวางไว้บนสุดของ Deck ฝ่ายเรา",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "วิไลวรรณ แม่แบงค์",
    type: "Avatar",
    soi: 1,
    print: "BT04-023",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกจ่าย Cost เพื่ออัญเชิญ Avatar สีม่วง : สอดแนม 1 ใบ หลังจากนั้นเลือกนำการ์ดใบนั้นไว้บนสุดของ Deck หรือ ส่งลงนรก",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "นายนิรยบาล หมอ",
    type: "Avatar",
    soi: 1,
    print: "BT04-024",
    rare: "C",
    mainEffect: "จุติ : ทิ้งการ์ดจากบนมือ 1 ใบ : ธรณีสูบ 3 ใบ จากนั้น อัญเชิญ Avatar ที่มี {Symbol นรก} ค่า Cost ไม่เกิน 4 จากในนรกเรา 1ใบ ลง Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 1,
    power: 2,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "ครูแกง สอนเลข",
    type: "Avatar",
    soi: 1,
    print: "BT04-025",
    rare: "C",
    mainEffect: "จุติ : นำผลรวม POWER ของ Avatar บนสนามแต่ละฝ่าย ถ้าฝ่ายไหนรวมกันแล้วผลลัพธ์เป็น \"จำนวนเฉพาะ\" ทำลาย Avatar ทุกตัวบนสนามนั้นๆ",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "ลูกเขยบิ๊ก",
    type: "Avatar",
    soi: 1,
    print: "BT04-026",
    rare: "SR",
    mainEffect: "จุติ : นำการ์ด Magic \"แผนการ\" จาก Deck หรือ นรก 1 ใบ และนำขึ้นมือ ถ้านำขึ้นมือจาก Deck ให้สับ Deck ด้วย",
    cost: 3,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "ลูกเขยบิ๊ก",
    type: "Avatar",
    soi: 1,
    print: "BT04-026",
    rare: "SCR",
    mainEffect: "จุติ : นำการ์ด Magic \"แผนการ\" จาก Deck หรือ นรก 1 ใบ และนำขึ้นมือ ถ้านำขึ้นมือจาก Deck ให้สับ Deck ด้วย",
    cost: 3,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "ผู้งมงาย",
    type: "Avatar",
    soi: 1,
    print: "BT04-027",
    rare: "C",
    mainEffect: "จุติ : จั่วการ์ดจาก Deck 1 ใบ จากนั้น ทิ้งการ์ด 1 ใบจากมือเราลงนรก",
    cost: 2,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พญายักษ์ ทศกัณฑ์",
    type: "Avatar",
    soi: 1,
    print: "BT04-028",
    rare: "UR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ สามารถทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ Avatar Symbol ยักษ์ ที่มี POWER 3 ยกเว้น \"ทศกัณฑ์\" จาก Deck 1 ใบลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: "ยักษ์",
    color: "เขียว",
  },
  {
    name: "พญายักษ์ ทศกัณฑ์",
    type: "Avatar",
    soi: 1,
    print: "BT04-028",
    rare: "SCR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ สามารถทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ Avatar Symbol ยักษ์ ที่มี POWER 3 ยกเว้น \"ทศกัณฑ์\" จาก Deck 1 ใบลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: "ยักษ์",
    color: "เขียว",
  },
  {
    name: "เสามงคล ทรงโรมัน",
    type: "Avatar",
    soi: 1,
    print: "BT04-029",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้โจมตีไม่ได้\n\nอัตโนมัติ ในช่วง End Phase เรา อัญเชิญ Avatar \"ผู้เจริญ\" 1 ใบ จากนรกฝ่ายเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 5,
    gem: 2,
    power: 3,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "มาติเนซ Tank Ranger",
    type: "Avatar",
    soi: 1,
    print: "BT04-030",
    rare: "SR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar ตัวนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา\n\nเมื่อ Avatar \"รถถัง\" ที่สวมใส่การ์ดใบนี้ตกเป็นเป้าหมายของการ์ด Magic เราสามารถทำลายการ์ดใบนี้จากสภาพสวมใส่ : ยกเลิกความสามารถของการ์ด Magic ใบนั้น",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "มาติเนซ Tank Ranger",
    type: "Avatar",
    soi: 1,
    print: "BT04-030",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar ตัวนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา\n\nเมื่อ Avatar \"รถถัง\" ที่สวมใส่การ์ดใบนี้ตกเป็นเป้าหมายของการ์ด Magic เราสามารถทำลายการ์ดใบนี้จากสภาพสวมใส่ : ยกเลิกความสามารถของการ์ด Magic ใบนั้น",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "ทหารเวรคลังแสง",
    type: "Avatar",
    soi: 1,
    print: "BT04-031",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : สามารถนำ Modification Magic \" ปืนเล็กยาว\" จากใน Deck ของเรา 1 ใบขึ้นมือ จากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "พลปืนอาณาจักรของแพง",
    type: "Avatar",
    soi: 1,
    print: "BT04-032",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี \" ราชาอาณาจักรของแพง  พระเจ้านิโคไล \"\n\nAvartar ใบนี้ได้รับความสามารถ \" เตะไข่ \"",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "เจ้าของร้านอาบน้ำสัตว์",
    type: "Avatar",
    soi: 1,
    print: "BT04-033",
    rare: "R",
    mainEffect:
      "โล่มนุษย์\n\nเทิร์นละครั้ง สั่งใช้ : สามารถ ทิ้ง Avatar \"พนักงานอาบน้ำสัตว์\" หรือ การ์ด {Symbol สัตว์} จากบนมือเรา 1 ใบ: เลือก Avatar {Symbol สัตว์} 1 ใบ ใน Avatar Zone ฝ่ายเรา POWER +1",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "อนงค์ พนักงานอาบน้ำสัตว์",
    type: "Avatar",
    soi: 1,
    print: "BT04-034",
    rare: "C",
    mainEffect: "คำสั่งเสีย : อัญเชิญ Avatar \"หมา\" หรือ \"แมว\" ที่มี {Symbol สัตว์} และ Cost ไม่เกิน 3 จากในนรกฝ่ายเรา 1 ใบมาบน Avatar Zone ฝ่ายเรา",
    cost: 1,
    gem: 3,
    power: 0,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "แฟรงกี้ พนักงานอาบน้ำสัตว์",
    type: "Avatar",
    soi: 1,
    print: "BT04-035",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้ทิ้ง Cost เพื่ออัญเชิญ Avatar \"หมา\" หรือ \"แมว\" ที่มี {Symbol สัตว์}  : เลือก Avatar {Symbol สัตว์} 1 ใบ ใน Avatar Zone ฝ่ายเรา POWER+2 จนจบเทิร์น",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "หนุ่มผมยาวนักวิ่ง",
    type: "Avatar",
    soi: 1,
    print: "BT04-036",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ผู้เจริญระดับ 3",
    type: "Avatar",
    soi: 1,
    print: "BT04-037",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "นักดาบมือหนึ่ง",
    type: "Avatar",
    soi: 1,
    print: "BT04-038",
    rare: "R",
    mainEffect: "",
    cost: 5,
    gem: 1,
    power: 6,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "แมวมัทฉะ",
    type: "Avatar",
    soi: 1,
    print: "BT04-039",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 3,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "พัทธกาล",
    type: "Avatar",
    soi: 1,
    print: "BT04-040",
    rare: "SR",
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: "ยักษ์",
    color: "เขียว",
  },
  {
    name: "ล้มโต๊ะ",
    type: "Magic",
    soi: 1,
    print: "BT04-041",
    rare: "C",
    mainEffect: "นำการ์ดบนมือของทั้ง 2 ฝ่ายทั้งหมดกลับเข้า Deck แล้วสับ จากนั้น จั่วการ์ดจาก Deck คนละ 4 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "Grand Rumble !!!!",
    type: "Magic",
    soi: 1,
    print: "BT04-042",
    rare: "SR",
    mainEffect:
      "สามารถใช้การ์ดใบนี้ได้เมื่อบนสนามทั้งหมดมี Avatar รวมกันได้ 6 ใบ เท่านั้น : ผู้ใช้การ์ดนี้กำหนดให้ Avatar แต่ละตัว มีเลข 1-6 โดยไม่ซ้ำกัน\n\nจากนั้นทอยลูกเต๋า 1 ครั้ง ทำลาย Avatar ทุกใบในสนาม ยกเว้น Avatar ที่มีเลขเดียวกันกับ ผลของลูกเต๋า",
    subtype: "Normal",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "Grand Rumble !!!!",
    type: "Magic",
    soi: 1,
    print: "BT04-042",
    rare: "SCR",
    mainEffect:
      "สามารถใช้การ์ดใบนี้ได้เมื่อบนสนามทั้งหมดมี Avatar รวมกันได้ 6 ใบ เท่านั้น : ผู้ใช้การ์ดนี้กำหนดให้ Avatar แต่ละตัว มีเลข 1-6 โดยไม่ซ้ำกัน\n\nจากนั้นทอยลูกเต๋า 1 ครั้ง ทำลาย Avatar ทุกใบในสนาม ยกเว้น Avatar ที่มีเลขเดียวกันกับ ผลของลูกเต๋า",
    subtype: "Normal",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "แผนการ : ถอยรถชน",
    type: "Magic",
    soi: 1,
    print: "BT04-043",
    rare: "C",
    mainEffect: "เซ่นไหว้ Avatar เครื่องจักร บนสนามเรา 1 ใบ : ทำลาย Avatar บนสนาม 1 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "บีมมมมมมมมมม",
    type: "Magic",
    soi: 1,
    print: "BT04-044",
    rare: "R",
    mainEffect: "ทิ้งการ์ดบนมือ 1 ใบ : ทำลาย Avatar บนสนามฝ่ายตรงข้าม 1 ใบ",
    subtype: "Normal",
    cost: 2,
    symbol: "เทพ",
  },
  {
    name: "ใครเจ๋งกว่า !",
    type: "Magic",
    soi: 1,
    print: "BT04-045",
    rare: "C",
    mainEffect:
      "ทั้ง 2 ฝ่าย เลือกแสดงการ์ดที่มี Cost บนมือ คนละ 1 ใบ จากนั้น ฝ่ายที่มีค่า Cost น้อยกว่า ต้องทิ้งการ์ดใบนั้นลงนรก\n\nถ้าเท่ากัน ทั้ง 2 ฝ่ายนำการ์ดใบนั้นกลับเข้า Deck แล้วสับ\n\nฝ่ายที่ไม่มีการ์ด ที่มี Cost ให้แสดง จะต้อง แสดงการ์ดบนมือทั้งหมดให้อีกฝ่ายเห็น",
    subtype: "Normal",
    cost: 1,
    symbol: "ฤษี",
  },
  {
    name: "เลือกมันสำหรับพวก จน !!!",
    type: "Magic",
    soi: 1,
    print: "BT04-046",
    rare: "R",
    mainEffect:
      "เลือกปฏิบัติ :\n\n1) นำ Avatar Cost 5 หรือต่ำกว่า จาก นรก ฝ่ายเรา  ขึ้นมือ 1 ใบ ยกเว้นการ์ด Only 1\n\n2) นำ Avatar ที่มี Cost 5 หรือต่ำกว่า จาก Deck ฝ่ายเรา ขึ้นมือ 1 ใบ ยกเว้นการ์ด  Only 1 แล้วสับ Deck\n\nถ้า Life Card ของเราถูกหงายตั้งแต่ 4 ใบขึ้นไปและหงายมากกว่าฝ่ายตรงข้าม ทำความสามารถ 1) และ 2)",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ความจริงงงงงงง",
    type: "Magic",
    soi: 1,
    print: "BT04-047",
    rare: "C",
    mainEffect:
      "สามารถใช้ได้เมื่อบน Avatar Zone ฝ่ายเรามี \"ผู้รู้ความจริง\"\n\nแสดงการ์ดจากใน Deck  เรา 1 ใบ จากนั้นสับ Deck นำการ์ดที่แสดง วางไว้บนสุดของ Deck เรา",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "งานจับมือ",
    type: "Magic",
    soi: 1,
    print: "BT04-048",
    rare: "SR",
    mainEffect: "เมื่อ Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเราเป็นเป้าหมายการโจมตี : ยกเลิกการโจมตีนั้น และ นำ Avatar \"โอตะ\" จากในนรกเรา 1 ใบ มาสวมใส่ให้ Avatar \"ไอดอล\" 1 ใบ บน Avatar Zone ฝ่ายเรา",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "งานจับมือ",
    type: "Magic",
    soi: 1,
    print: "BT04-048",
    rare: "SCR",
    mainEffect: "เมื่อ Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเราเป็นเป้าหมายการโจมตี : ยกเลิกการโจมตีนั้น และ นำ Avatar \"โอตะ\" จากในนรกเรา 1 ใบ มาสวมใส่ให้ Avatar \"ไอดอล\" 1 ใบ บน Avatar Zone ฝ่ายเรา",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "เอาไปอยู่ด้วย",
    type: "Magic",
    soi: 1,
    print: "BT04-049",
    rare: "R",
    mainEffect: "ถ้า Avatar {Symbol ผี} บนสนามฝ่ายเราถูกทำลายโดยการ์ดฝ่ายตรงข้าม : ทำลาย Avatar บน Avatar Zone ของอีกฝ่าย 1 ใบ",
    subtype: "React",
    cost: 2,
    symbol: "ผี",
  },
  {
    name: "เชาว์ปัญญาลิง - ชิงปัญญาเรา",
    type: "Magic",
    soi: 1,
    print: "BT04-050",
    rare: "SR",
    mainEffect: "เมื่อฝ่ายตรงข้ามใช้ความสามารถของ Avatar บน Avatar Zone :  Avatar ใบนั้นของฝ่ายตรงข้ามสูญเสียความสามารถทั้งหมด จนจบเทิร์น",
    subtype: "React",
    cost: 0,
    symbol: "สัตว์",
  },
  {
    name: "เชาว์ปัญญาลิง - ชิงปัญญาเรา",
    type: "Magic",
    soi: 1,
    print: "BT04-050",
    rare: "SCR",
    mainEffect: "เมื่อฝ่ายตรงข้ามใช้ความสามารถของ Avatar บน Avatar Zone :  Avatar ใบนั้นของฝ่ายตรงข้ามสูญเสียความสามารถทั้งหมด จนจบเทิร์น",
    subtype: "React",
    cost: 0,
    symbol: "สัตว์",
  },
  {
    name: "ลดราคาล้นตลาด",
    type: "Magic",
    soi: 1,
    print: "BT04-051",
    rare: "C",
    mainEffect:
      "เมื่อทั้ง 2 ฝ่ายมี Modification Magic สวมใส่อยู่ บน Magic Zone :\n\nนำ Modification Magic ที่ติดอยู่บนสนามของทั้ง 2 ฝ่าย ฝ่ายละ 1 ใบ ส่งลงนรก",
    subtype: "React",
    cost: 0,
    symbol: "สัตว์",
  },
  {
    name: "กลับหลังหัน !!!",
    type: "Magic",
    soi: 1,
    print: "BT04-052",
    rare: "C",
    mainEffect: "เลือก Avatar ที่กำลังต่อสู้ 1 ใบ : นำค่า Cost และ POWER มาสลับกันจนจบการต่อสู้นั้น",
    subtype: "React",
    cost: 2,
    symbol: "ทหาร",
  },
  {
    name: "อาวุธนักรบผู้กล้า \" ไบโพล่า ชิลด์ \"",
    type: "Magic",
    soi: 1,
    print: "BT04-053",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar  \"ผู้กล้า\" ที่มี symbol เครื่องจักรเท่านั้น\n\nเทิร์นละครั้ง เมื่อ Avatar ที่สวมใส่การ์ดใบนี้จะออกจากสนามโดยการ์ดฝ่ายตรงข้าม : ทอยลูกเต๋า 1 ครั้ง ถ้าออกเลขคู่ Avatar ที่สวมใส่การ์ดใบนี้จะไม่ถูกนำออกจากสนาม",
    subtype: "Modification",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ของขวัญจากโอตะ",
    type: "Magic",
    soi: 1,
    print: "BT04-054",
    rare: "R",
    mainEffect:
      "สามารถสวมใส่ได้เฉพาะ Avatar \" ไอดอล \" และเมื่อการ์ดใบนี้สวมใส่ Avatar \"ไอดอล\" : จั่วการ์ด 1 ใบ\n\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar \"ไอดอล\" หรือ \"โปรดิวเซอร์\" เท่านั้น",
    subtype: "Modification",
    cost: 4,
    symbol: "จอมเวทย์",
  },
  {
    name: "ดาบพิฆาตสวรรค์ ราคา 4000 เหรียญทอง",
    type: "Magic",
    soi: 1,
    print: "BT04-055",
    rare: "C",
    mainEffect:
      "Avatar ที่สวมใส่ Modification ใบนี้ Cost + 2\n\nถ้า Avatar ที่สวมใส่ Modification ใบนี้ Cost เป็น 6 หรือมากกว่า POWER + 1",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ปืนเล็กยาว",
    type: "Magic",
    soi: 1,
    print: "BT04-056",
    rare: "C",
    mainEffect:
      "สวมใส่ได้แค่ Avatar \"ทหาร\" หรือ \"รด.\" ที่มี Symbol คน เท่านั้น\n\nAvatar ที่สวมใส่ POWER + 3",
    subtype: "Modification",
    cost: 2,
    symbol: "ทหาร",
  },
  {
    name: "สมาคมผู้รู้ความจริง",
    type: "Magic",
    soi: 1,
    print: "BT04-057",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง ถ้าเรามี Avatar \"ผู้รู้ความจริง\" อยู่บน Avatar Zone ฝ่ายเรา สอดแนม Deck เรา 3 ใบ เรียงลำดับการ์ดทั้ง 3 ใบนั้นไว้บน Deck หรือใต้ Deck",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "โรงบาลรัฐ",
    type: "Magic",
    soi: 1,
    print: "BT04-058",
    rare: "C",
    mainEffect: "LIFE Card ของทั้ง 2 ฝ่ายจะไม่สามารถเปลี่ยนเป็นสภาพคว่ำได้",
    subtype: "Land",
    cost: 2,
    symbol: "ต้นไม้",
  },
  {
    name: "พิภพรัททาทุย",
    type: "Magic",
    soi: 1,
    print: "BT04-059",
    rare: "SR",
    mainEffect:
      "ถ้าบน Avatar Zone ของฝ่ายเรา เป็น Avatar Symbol รัททาทุย ทั้งหมด เราจะสามารถควบคุม Avatar Symbol รัททาทุย บน Avatar Zone ได้ 6 ใบ\n\nPOWER +2 ให้ Avatar {Symbol รัททาทุย} ที่สั่งโจมตีจนจบการต่อสู้นั้น",
    subtype: "Land",
    cost: 3,
    symbol: "รัททาทุย",
  },
  {
    name: "พิภพรัททาทุย",
    type: "Magic",
    soi: 1,
    print: "BT04-059",
    rare: "SCR",
    mainEffect:
      "ถ้าบน Avatar Zone ของฝ่ายเรา เป็น Avatar Symbol รัททาทุย ทั้งหมด เราจะสามารถควบคุม Avatar Symbol รัททาทุย บน Avatar Zone ได้ 6 ใบ\n\nPOWER +2 ให้ Avatar {Symbol รัททาทุย} ที่สั่งโจมตีจนจบการต่อสู้นั้น",
    subtype: "Land",
    cost: 3,
    symbol: "รัททาทุย",
  },
  {
    name: "Podcast Untitled Case",
    type: "Magic",
    soi: 1,
    print: "BT04-060",
    rare: "UR",
    mainEffect: "Avatar เผ่า ผี เปรต เอเลี่ยน และไดโนเสาร์  POWER +1",
    subtype: "Land",
    cost: 1,
    symbol: "หุ่นยนต์",
  },
  {
    name: "Podcast Untitled Case",
    type: "Magic",
    soi: 1,
    print: "BT04-060",
    rare: "SCR",
    mainEffect: "Avatar เผ่า ผี เปรต เอเลี่ยน และไดโนเสาร์  POWER +1",
    subtype: "Land",
    cost: 1,
    symbol: "หุ่นยนต์",
  },
];
