import { Card } from "@/src/types/cards";

export const CARDS_BT06: Card[] = [
  {
    name: "วิรูฬ นาคเกล็ดทอง",
    type: "Avatar",
    soi: 2,
    print: "BT06-001",
    rare: "SR",
    mainEffect: "อัตโนมัติ ถ้า Avatar ใบนี้ POWER 7 หรือมากกว่าในช่วงเริ่ม Battle Phase : จะได้รับความสามารถดังต่อไปนี้จนจบเทิร์น \"เมื่อ Avatar ใบนี้ โจมตี LIFE Card LIFE Card ที่ถูกหงายจากการโจมตีของ Avatar ใบนี้ ความสามารถจะไม่ทำงาน",
    cost: 3,
    gem: 0,
    power: 4,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
  },
  {
    name: "ฉัพพยา นาคเกล็ดรุ้ง",
    type: "Avatar",
    soi: 2,
    print: "BT06-002",
    rare: "R",
    mainEffect: "อัตโนมัติ ถ้า Avatar ใบนี้ POWER 7 หรือมากกว่าในช่วงเริ่ม Battle Phase : จะได้รับความสามารถดังต่อไปนี้จนจบเทิร์น \"เมื่อ Avatar ใบนี้ โจมตี LIFE Card สำเร็จ จะทำความเสียหายต่อ LIFE Card 2 ใบ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
  },
  {
    name: "เอรา นาคเกล็ดเขียว",
    type: "Avatar",
    soi: 2,
    print: "BT06-003",
    rare: "C",
    mainEffect: "จุติ : เลือก Avatar \"นาค\" ที่เป็น Symbol สัตว์มหัศจรรย์ 1 ใบ ใน Avatar Zone ฝ่ายเรา Avatar ใบนั้น POWER +2",
    cost: 2,
    gem: 3,
    power: 1,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
  },
  {
    name: "อนันต์ ราชาแห่งนาค",
    type: "Avatar",
    soi: 2,
    print: "BT06-004",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : Avatar \"นาค\" ที่เป็น symbol สัตว์มหัศจรรย์ ใบอื่น ทุกใบใน Avatar Zone ฝ่ายเรา จะมี POWER เท่ากับ POWER ของ Avatar ใบนี้ จนจบเทิร์น\nอัตโนมัติ เมื่อ Avatar ใบนี้ โจมตี และทำลาย Avatar ฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ฝ่ายตรงข้าม หงาย LIFE Card 1 ใบ",
    cost: 6,
    gem: 2,
    power: 7,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
    ex: "Only #1",
  },
  {
    name: "อนันต์ ราชาแห่งนาค",
    type: "Avatar",
    soi: 2,
    print: "BT06-004",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : Avatar \"นาค\" ที่เป็น symbol สัตว์มหัศจรรย์ ใบอื่น ทุกใบใน Avatar Zone ฝ่ายเรา จะมี POWER เท่ากับ POWER ของ Avatar ใบนี้ จนจบเทิร์น\nอัตโนมัติ เมื่อ Avatar ใบนี้ โจมตี และทำลาย Avatar ฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ฝ่ายตรงข้าม หงาย LIFE Card 1 ใบ",
    cost: 6,
    gem: 2,
    power: 7,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
    ex: "Only #1",
  },
  {
    name: "รีวิวแมน",
    type: "Avatar",
    soi: 2,
    print: "BT06-005",
    rare: "SR",
    mainEffect: "Avatar ใบนี้สามารถสวมใส่ Modification Magic ได้โดยไม่สนเงื่อนไขการสวมใส่ที่ระบุไว้ใน Text Box ของ Modification Magic ใบนั้นๆ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
    ex: "#โดนใจ",
  },
  {
    name: "รีวิวแมน",
    type: "Avatar",
    soi: 2,
    print: "BT06-005",
    rare: "SCR",
    mainEffect: "Avatar ใบนี้สามารถสวมใส่ Modification Magic ได้โดยไม่สนเงื่อนไขการสวมใส่ที่ระบุไว้ใน Text Box ของ Modification Magic ใบนั้นๆ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
    ex: "#โดนใจ",
  },
  {
    name: "อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม",
    type: "Avatar",
    soi: 2,
    print: "BT06-006",
    rare: "UR",
    mainEffect:
      "จุติ ส่ง Modification \"ดาบศักดิ์สิทธิ์\" จาก Deck เรา 2 ใบ ลงนรก : อัญเชิญ Avatar \"อัศวินโต๊ะกลม\" 1 ใบ จาก Deck เรา จากนั้นสับ Deck จนกว่าจะจบเทิร์นนี้ Avatar ฝ่ายเราที่มีชื่อเดียวกันกับ Avatar ที่ถูกอัญเชิญด้วยความสามารถนี้จะไม่สามารถสั่งโจมตี และใช้ความสามารถได้\n#เราสามารถควบคุม อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม ใน Avatar Zone ได้เพียง 1 ใบเท่านั้น",
    cost: 7,
    gem: 2,
    power: 5,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม",
    type: "Avatar",
    soi: 2,
    print: "BT06-006",
    rare: "SCR",
    mainEffect:
      "จุติ ส่ง Modification \"ดาบศักดิ์สิทธิ์\" จาก Deck เรา 2 ใบ ลงนรก : อัญเชิญ Avatar \"อัศวินโต๊ะกลม\" 1 ใบ จาก Deck เรา จากนั้นสับ Deck จนกว่าจะจบเทิร์นนี้ Avatar ฝ่ายเราที่มีชื่อเดียวกันกับ Avatar ที่ถูกอัญเชิญด้วยความสามารถนี้จะไม่สามารถสั่งโจมตี และใช้ความสามารถได้ \n#เราสามารถควบคุม อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม ใน Avatar Zone ได้เพียง 1 ใบเท่านั้น",
    cost: 7,
    gem: 2,
    power: 5,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "เคย์ อัศวินโต๊ะกลมแห่งความหลักแหลม",
    type: "Avatar",
    soi: 2,
    print: "BT06-007",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ในเทิร์นฝ่ายตรงข้าม เมื่อ Avatar \"อัศวินโต๊ะกลม\" ฝ่ายเรา ถูกโจมตี สามารถส่ง Modification Magic \"ดาบศักดิ์สิทธิ์\" 1 ใบ จากสนามฝ่ายเรา ลงนรก :  Avatar \"อัศวินโต๊ะกลม\" 1 ใบ POWER +2 จนจบเทิร์น",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "ยอดนักบุญ",
    type: "Avatar",
    soi: 2,
    print: "BT06-008",
    rare: "C",
    mainEffect:
      "จุติ : นำ Modification Magic น้ำใจ ทีสวมใส่ อยู่กับ Avatar ใบอื่น ทุกใบใน Avatar Zone ฝ่ายเรา มาสวมใส่ที่ Avatar ใบนี้\nต่อเนื่อง ถ้า Avatar ใบนี้สวมใส่ Modification Magic น้ำใจ 4 ใบ POWER ตั้งต้น ของ Avatar ใบนี้ จะเป็น 10",
    cost: 3,
    gem: 0,
    power: 0,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "หุ่นนักรบผู้กล้า : โปรโตไมเกรน",
    type: "Avatar",
    soi: 2,
    print: "BT06-009",
    rare: "UR",
    mainEffect: "สั่งใช้ เมื่อ Avatar ใบนี้ โจมตีและทำลาย Avatar ฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ส่ง Avatar ใบนี้ลงนรก และ อัญเชิญ จุติ หุ่นนักรบผู้กล้า : ไมเกรน จาก Deck เรา จากนั้นสับ Deck ถ้า Avatar ใบนี้มีการ์ดสวมใส่อยู่ ให้นำการ์ดที่สวมใส่อยู่ทั้งหมด ไปสวมใส่ให้ Avatar ที่อัญเชิญมาด้วยความสามารถนี้แทน",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "พระอิศวรปลอม",
    type: "Avatar",
    soi: 2,
    print: "BT06-010",
    rare: "C",
    mainEffect: "จุติ : เลือก Avatar 1 ใบ POWER -2 จนจบเทิร์น",
    cost: 3,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ไดโนกาฬสินธุ์ - สุธีธรนีซอรัส",
    type: "Avatar",
    soi: 2,
    print: "BT06-011",
    rare: "SR",
    mainEffect: "คำสั่งเสีย สอดแนม 3 ใบ : เลือก Avatar \"ไดโนกาฬสินธุ์\" 1 ใบที่มี Cost 3 หรือต่ำกว่า และไม่ได้ ชื่อไดโนกาฬสินธุ์ - สุธีธรนีซอรัสอัญเชิญลง Avatar zone ฝ่ายเรานำที่เหลือกลับเข้า Deck แล้วสับ",
    cost: 3,
    gem: 0,
    power: 4,
    symbol: "กะปอม",
    color: "ฟ้า",
  },
  {
    name: "กัปตัน 7 สี",
    type: "Avatar",
    soi: 2,
    print: "BT06-012",
    rare: "C",
    mainEffect:
      "จุติ : เลือกปฏิบัติ 1 อย่าง ตาม Avatar ใบอื่นที่เราควบคุมอยู่บน Avatar Zone\nสีแดง  Power ของการ์ดใบนี้ +2 \nสีฟ้า จั่วการ์ดจาก Deck เรา 1 ใบ\nสีม่วง ธรณีสูบ 1 ใบ หลังจากนั้นนำ การ์ด 1 ใบจากในนรกกลับเข้าใต้ Deck\nสีเขียว Avatar ตัวนี้จะไม่ถูกทำลายจนจบเทิร์น ที่ถูกอัญเชิญ",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "บึงทมิฬ  People  - คุณบลูลอบสเตอร์",
    type: "Avatar",
    soi: 2,
    print: "BT06-013",
    rare: "C",
    mainEffect:
      "เมื่อ Avatar ใบนี้ถูกนำขึ้นมือจาก Deck ในช่วง Draw Phase และใน Land Magic Zone มีการ์ด \"บึงทมิฬ\" หรือ ถูกนำขึ้นมือด้วยความสามารถของ \"บึงทมิฬ\" แสดงการ์ดใบนี้ให้ฝ่ายตรงข้ามดู และอัญเชิญลงบน Avatar Zone ฝ่ายเรา\nเมื่อการ์ดใบนี้ถูกอัญเชิญด้วยความสามารถของตัวเอง : ทำลาย Avatar 1 ใบ ในสนามฝ่ายตรงข้าม",
    cost: 4,
    gem: 2,
    power: 0,
    symbol: "ปลา",
    color: "ฟ้า",
  },
  {
    name: "สวีนนีย์ มนุษย์ดาว R18",
    type: "Avatar",
    soi: 2,
    print: "BT06-014",
    rare: "UR",
    mainEffect:
      "อัตโนมัติ เมื่อการ์ดใบนี้ ทำลาย Avatar ฝ่ายตรงข้าม จากการต่อสู้และส่งลงนรก หลังจากการต่อสู้นั้นนำ Avatar ใบที่ถูกทำลาย มาไว้ที่ Magic Zone ฝ่ายเรา จากนั้น เปลี่ยนชื่อ Avatar ใบนั้นเป็น \"ข้ารับใช้ของ มนุษย์ดาว R18\" และเปลี่ยนเป็น Symbol เอเลี่ยน\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar \"ข้ารับใช้ของ มนุษย์ดาว R18\" ใน Magic Zone ฝ่ายเรา 1 ใบ ส่งการ์ดใบที่เลือกลงนรกเจ้าของเดิม",
    cost: 4,
    gem: 0,
    power: 5,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "สวีนนีย์ มนุษย์ดาว R18",
    type: "Avatar",
    soi: 2,
    print: "BT06-014",
    rare: "SCR",
    mainEffect:
      "อัตโนมัติ เมื่อการ์ดใบนี้ ทำลาย Avatar ฝ่ายตรงข้าม จากการต่อสู้และส่งลงนรก หลังจากการต่อสู้นั้นนำ Avatar ใบที่ถูกทำลาย มาไว้ที่ Magic Zone ฝ่ายเรา จากนั้น เปลี่ยนชื่อ Avatar ใบนั้นเป็น \"ข้ารับใช้ของ มนุษย์ดาว R18\" และเปลี่ยนเป็น Symbol เอเลี่ยน\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar \"ข้ารับใช้ของ มนุษย์ดาว R18\" ใน Magic Zone ฝ่ายเรา 1 ใบ ส่งการ์ดใบที่เลือกลงนรกเจ้าของเดิม",
    cost: 4,
    gem: 0,
    power: 5,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "อามัส มนุษย์ดาว R18",
    type: "Avatar",
    soi: 2,
    print: "BT06-015",
    rare: "SR",
    mainEffect: "ต่อเนื่อง POWER ของ Avatar ใบนี้ จะเพิ่มขึ้นตามจำนวน Avatar  \"ข้ารับใช้ของ มนุษย์ดาว R18\" ในสนามฝ่ายเรา ใบละ 1",
    cost: 3,
    gem: 3,
    power: 0,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "จอย มนุษย์ดาว R18",
    type: "Avatar",
    soi: 2,
    print: "BT06-016",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : เลือก Avatar \"ข้ารับใช้ของ มนุษย์ดาว R18\" 1 ใบ ใน Magic Zone ฝ่ายเรา อัญเชิญ Avatar ใบนั้น ลง Avatar Zone ฝ่ายเรา ในช่วง End Phase นำ Avatar ใบนั้น กลับมาไว้ที่ Magic Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "วิลโล่ ปลาแกะ",
    type: "Avatar",
    soi: 2,
    print: "BT06-017",
    rare: "R",
    mainEffect: "#Avatar ใบนี้ นับเป็น Symbol สัตว์ ด้วย",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "ปลา",
    color: "ฟ้า",
  },
  {
    name: "จ่ามะนาวแขนเหล็ก",
    type: "Avatar",
    soi: 2,
    print: "BT06-018",
    rare: "UR",
    mainEffect:
      "โล่มนุษย์ สามัคคี\nสั่งใช้ : เมื่อ Avatar \"จ่ามะนาว\" ที่ Cost 3 หรือต่ำกว่า ใน Avatar Zone ฝ่ายเรา ถูกทำลาย สามารถอัญเชิญการ์ดใบนี้จากบนมือได้ โดยการจ่าย Cost ถ้าอยู่ในสถานะสาหัส สามารถอัญเชิญด้วยความสามารถนี้ได้โดยไม่ต้องจ่าย Cost",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "จ่ามะนาวแขนเหล็ก",
    type: "Avatar",
    soi: 2,
    print: "BT06-018",
    rare: "SCR",
    mainEffect:
      "โล่มนุษย์ สามัคคี\nสั่งใช้ : เมื่อ Avatar \"จ่ามะนาว\" ที่ Cost 3 หรือต่ำกว่า ใน Avatar Zone ฝ่ายเรา ถูกทำลาย สามารถอัญเชิญการ์ดใบนี้จากบนมือได้ โดยการจ่าย Cost ถ้าอยู่ในสถานะสาหัส สามารถอัญเชิญด้วยความสามารถนี้ได้โดยไม่ต้องจ่าย Cost",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "ผู้เจริญระดับสูงสุด",
    type: "Avatar",
    soi: 2,
    print: "BT06-019",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : นำ Avatar \"เสามงคล\" 1 ใบ จาก Avatar Zone ฝ่ายเรา ไปที่ Magic Zone ฝ่ายเรา",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "บอล ผู้รักวิตามิน",
    type: "Avatar",
    soi: 2,
    print: "BT06-020",
    rare: "C",
    mainEffect: "ต่อเนื่อง POWER ของ Avatar ใบนี้ จะเพิ่มขึ้นตามจำนวน Avatar \"กุ่ย\" , \"ฮอล\" หรือ \"นาย\" ในสนามฝ่ายเรา ใบละ 1",
    cost: 2,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "ฮิฟีสตัส เทพโอลิมปัสแห่งการช่าง",
    type: "Avatar",
    soi: 2,
    print: "BT06-021",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกใช้เป็นค่า Cost เพื่อการก่อสร้าง Construct การ์ดใบนี้จะถือว่ามี GEM 5",
    cost: 0,
    gem: 1,
    power: 0,
    symbol: "เทพ",
    color: "ฟ้า",
  },
  {
    name: "แบงค์ผู้พิชิต",
    type: "Avatar",
    soi: 2,
    print: "BT06-022",
    rare: "UR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ ได้รับความสามารถเพิ่มตามจำนวน Avatar \"แบงค์\" ที่ชื่อต่างกันในนรกเรา\n- 5 ชื่อ Avatar ใบนี้ POWER +2 \n- 7 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามจากการต่อสู้สำเร็จ : หงาย LIFE Card ฝ่ายตรงข้าม 1 ใบ\n- 10 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามไม่สามารถใช้งาน React Magic ได้ จนจบการต่อสู้นั้น\nสั่งใช้ สามารถส่ง Avatar \"แบงค์\" 4 ใบจากบน Avatar Zone ฝ่ายเรา ลงนรก อัญเชิญ Avatar ใบนี้จากในนรกเรา ลง Avatar Zone ฝ่ายเรา",
    cost: 7,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "แบงค์ผู้พิชิต",
    type: "Avatar",
    soi: 2,
    print: "BT06-022",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ ได้รับความสามารถเพิ่มตามจำนวน Avatar \"แบงค์\" ที่ชื่อต่างกันในนรกเรา\n- 5 ชื่อ Avatar ใบนี้ POWER +2 \n- 7 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามจากการต่อสู้สำเร็จ : หงาย LIFE Card ฝ่ายตรงข้าม 1 ใบ\n- 10 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามไม่สามารถใช้งาน React Magic ได้ จนจบการต่อสู้นั้น\nสั่งใช้ สามารถส่ง Avatar \"แบงค์\" 4 ใบจากบน Avatar Zone ฝ่ายเรา ลงนรก อัญเชิญ Avatar ใบนี้จากในนรกเรา ลง Avatar Zone ฝ่ายเรา",
    cost: 7,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "แบงค์ผู้พิชิต",
    type: "Avatar",
    soi: 2,
    print: "BT06-022",
    rare: "PR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ ได้รับความสามารถเพิ่มตามจำนวน Avatar \"แบงค์\" ที่ชื่อต่างกันในนรกเรา\n- 5 ชื่อ Avatar ใบนี้ POWER +2 \n- 7 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามจากการต่อสู้สำเร็จ : หงาย LIFE Card ฝ่ายตรงข้าม 1 ใบ\n- 10 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามไม่สามารถใช้งาน React Magic ได้ จนจบการต่อสู้นั้น\nสั่งใช้ สามารถส่ง Avatar \"แบงค์\" 4 ใบจากบน Avatar Zone ฝ่ายเรา ลงนรก อัญเชิญ Avatar ใบนี้จากในนรกเรา ลง Avatar Zone ฝ่ายเรา",
    cost: 7,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "แบงค์ผู้พิชิต",
    type: "Avatar",
    soi: 2,
    print: "BT06-022",
    rare: "CBR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ ได้รับความสามารถเพิ่มตามจำนวน Avatar \"แบงค์\" ที่ชื่อต่างกันในนรกเรา\n- 5 ชื่อ Avatar ใบนี้ POWER +2 \n- 7 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามจากการต่อสู้สำเร็จ : หงาย LIFE Card ฝ่ายตรงข้าม 1 ใบ\n- 10 ชื่อ อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามไม่สามารถใช้งาน React Magic ได้ จนจบการต่อสู้นั้น\nสั่งใช้ สามารถส่ง Avatar \"แบงค์\" 4 ใบจากบน Avatar Zone ฝ่ายเรา ลงนรก อัญเชิญ Avatar ใบนี้จากในนรกเรา ลง Avatar Zone ฝ่ายเรา",
    cost: 7,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อู๊ด คุณแม่",
    type: "Avatar",
    soi: 2,
    print: "BT06-023",
    rare: "R",
    mainEffect: "สั่งใช้ เซ่นไหว้ Avatar ใบนี้ ธรณีสูบ 3 ใบ : อัญเชิญ Avatar \"แบงค์\" จากใน Deck เรา ที่ไม่ใช่ Only #1 1 ใบลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่หน่วง",
    type: "Avatar",
    soi: 2,
    print: "BT06-024",
    rare: "UR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดบนมือเรา 2 ใบ : เลือก Avatar ของฝ่ายตรงข้าม 1 ใบนำการ์ดที่เลือกและการ์ดใบนี้เข้าสู่ ช่อง Magic Zone ฝ่ายเรา เมื่อเริ่มต้น Main Phase ถัดไปของเรา อัญเชิญการ์ดใบนี้เข้าสู่ช่อง Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "เลอติ๊ก เด็กไม่ชอบแดรคคูลา",
    type: "Avatar",
    soi: 2,
    print: "BT06-025",
    rare: "R",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ ทำลาย Avatar ฝ่ายตรงข้าม จากการต่อสู้ : Avatar ที่ถูก การ์ดใบนี้ทำลาย จะถูกส่งกลับเข้า Deck แทนการ ส่งลงนรก",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: "ต่างชาติ",
    color: "ม่วง",
  },
  {
    name: "แอชวิคกับอโศกาบาร์พิศวง",
    type: "Avatar",
    soi: 2,
    print: "BT06-026",
    rare: "SR",
    mainEffect: "พอดี จุติ : อัญเชิญ จุติ Avatar Symbol ผี , เปรต หรือ เอเลี่ยน 1 ใบ ที่ Cost 5 หรือต่ำกว่าจากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 7,
    gem: 1,
    power: 3,
    symbol: "ผี",
    color: "ม่วง",
  },
  {
    name: "แอชวิคกับอโศกาบาร์พิศวง",
    type: "Avatar",
    soi: 2,
    print: "BT06-026",
    rare: "SCR",
    mainEffect: "พอดี จุติ : อัญเชิญ จุติ Avatar Symbol ผี , เปรต หรือ เอเลี่ยน 1 ใบ ที่ Cost 5 หรือต่ำกว่าจากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 7,
    gem: 1,
    power: 3,
    symbol: "ผี",
    color: "ม่วง",
  },
  {
    name: "สกัลด์ เทพธิดาแห่งวัลฮัลลา",
    type: "Avatar",
    soi: 2,
    print: "BT06-027",
    rare: "R",
    mainEffect: "ถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar symbol เทพ สีม่วง หรือ Magic Card : อัญเชิญ \"เทพธิดาแห่งวัลฮัลลา\" Cost 4 หรือต่ำกว่า และไม่ได้ชื่อ สกัลด์ เทพธิดาแห่งวัลฮัลลา 1 ใบ ในนรกเราลงบน Avatar Zone ฝ่ายเรา",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "เทพ",
    color: "ม่วง",
  },
  {
    name: "โอลรุน เทพธิดาแห่งวัลฮัลลา",
    type: "Avatar",
    soi: 2,
    print: "BT06-028",
    rare: "C",
    mainEffect: "ถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar symbol เทพ สีม่วง หรือ Magic Card : นำ Avatar ใบนี้กลับขึ้นมือ",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "เทพ",
    color: "ม่วง",
  },
  {
    name: "ซีกรุน เทพธิดาแห่งวัลฮัลลา",
    type: "Avatar",
    soi: 2,
    print: "BT06-029",
    rare: "SR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ธรณีสูบ 3 ใบ : Avatar ใบนี้ POWER +1",
    cost: 5,
    gem: 2,
    power: 5,
    symbol: "เทพ",
    color: "ม่วง",
  },
  {
    name: "อาม่อน No.7",
    type: "Avatar",
    soi: 2,
    print: "BT06-030",
    rare: "UR",
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้ถูก ธรณีสูบ อัญเชิญ Avatar ใบนี้ ลงบน Avatar Zone ของฝ่ายเรา \nอัตโนมัติ เมื่อ Avatar ใบนี้ ถูกทำลายจาก Avatar Zone ลงนรก นำ Avatar ใบนี้กลับเข้าใต้สุดของ Deck เราแทนการลงนรก",
    cost: 7,
    gem: 0,
    power: 7,
    symbol: "นรก",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "อาม่อน No.7",
    type: "Avatar",
    soi: 2,
    print: "BT06-030",
    rare: "SCR",
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้ถูก ธรณีสูบ อัญเชิญ Avatar ใบนี้ ลงบน Avatar Zone ของฝ่ายเรา \nอัตโนมัติ เมื่อ Avatar ใบนี้ ถูกทำลายจาก Avatar Zone ลงนรก นำ Avatar ใบนี้กลับเข้าใต้สุดของ Deck เราแทนการลงนรก",
    cost: 7,
    gem: 0,
    power: 7,
    symbol: "นรก",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "งี่เง่า และ งอแง",
    type: "Avatar",
    soi: 2,
    print: "BT06-031",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง เลือกปฎิบัติ :\n1) เซ่นไหว้ Avatar ใบนี้ จั่วการ์ด 2 ใบ\n2) ได้รับ ความสามารถ เตะไข่ จนจบเทิร์น จากนั้นทำลาย Avatar ใบนี้ ในช่วง End Phase",
    cost: 2,
    gem: 0,
    power: 1,
    symbol: "สัตว์",
    color: "ม่วง",
  },
  {
    name: "พีเจี้ยน 3000",
    type: "Avatar",
    soi: 2,
    print: "BT06-032",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : เลือก Avatar \"เครื่องบิน Super Air\" 1 ใบ บน Avatar Zone ฝ่ายเรา นำการ์ดใบนี้ไปสวมใส่ Avatar ใบนั้น\nAvatar ที่ถูกสวมใส่การ์ดใบนี้ ได้รับ ความสามารถ \"โล่มนุษย์\" และ POWER +1",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "เสาซินแสมงคล",
    type: "Avatar",
    soi: 2,
    print: "BT06-033",
    rare: "UR",
    mainEffect:
      "สามารถ ส่ง Avatar \"ซินแส\" และ \"เสามงคล\" อย่างละ 1 ใบ จาก Avatar Zone ฝ่ายเรา ลงนรก และ อัญเชิญ จุติ การ์ดใบนี้จากมือได้\nจุติ : นำ Avatar \"เสามงคล\" ได้สูงสุด 3 ใบจากนรกเรา ไปไว้ที่ Magic Zone ฝ่ายเรา\nต่อเนื่อง Avatar \"เสามงคล\" ฝ่ายเราสามารถใช้ความสามารถจาก Magic Zone ได้\nอัตโนมัติ เมื่อ Avatar ใบนี้ จะออกจากสนาม : สามารถส่ง Avatar \"เสามงคล\" ใบอื่นในสนามเรา 1 ใบ แทนการถูกนำออกจากสนามได้",
    cost: 7,
    gem: 4,
    power: 5,
    symbol: "ต้นไม้",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "เสาซินแสมงคล",
    type: "Avatar",
    soi: 2,
    print: "BT06-033",
    rare: "SCR",
    mainEffect:
      "สามารถ ส่ง Avatar \"ซินแส\" และ \"เสามงคล\" อย่างละ 1 ใบ จาก Avatar Zone ฝ่ายเรา ลงนรก และ อัญเชิญ จุติ การ์ดใบนี้จากมือได้\nจุติ : นำ Avatar \"เสามงคล\" ได้สูงสุด 3 ใบจากนรกเรา ไปไว้ที่ Magic Zone ฝ่ายเรา\nต่อเนื่อง Avatar \"เสามงคล\" ฝ่ายเราสามารถใช้ความสามารถจาก Magic Zone ได้\nอัตโนมัติ เมื่อ Avatar ใบนี้ จะออกจากสนาม : สามารถส่ง Avatar \"เสามงคล\" ใบอื่นในสนามเรา 1 ใบ แทนการถูกนำออกจากสนามได้",
    cost: 7,
    gem: 4,
    power: 5,
    symbol: "ต้นไม้",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "เสามงคล ทรงญี่ปุ่น",
    type: "Avatar",
    soi: 2,
    print: "BT06-034",
    rare: "R",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้โจมตีไม่ได้\nเทิร์นละครั้ง สั่งใช้ : อัญเชิญ Avatar \"ผู้เจริญ\" 1 ใบ จากมือเรา ลงบน Avatar Zone ฝ่ายเรา Avatar ใบนั้นได้รับ POWER +1 ในช่วง End Phase เรา ส่ง Avatar ที่ถูกอัญเชิญด้วยความสามารถนี้ลงนรกเรา",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "ต้นไม้",
    color: "เขียว",
  },
  {
    name: "จ่านุ้ย ทหารช่าง",
    type: "Avatar",
    soi: 2,
    print: "BT06-035",
    rare: "C",
    mainEffect: "จุติ : สอดแนม 5 ใบ เลือกการ์ด Construct 1 ใบ จากที่สอดแนม และนำขึ้นมือ จากนั้นนำการ์ดที่เหลือเรียงและนำไว้ใต้ Deck",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "เสนาธิการ อาณาจักรของแพง",
    type: "Avatar",
    soi: 2,
    print: "BT06-036",
    rare: "C",
    mainEffect: "จุติ เลือก Avatar \"ราชาอาณาจักรของแพง  พระเจ้านิโคไล\" บน Avatar Zone ฝ่ายเรา 1 ใบ : ทำลาย Avatar บนสนามฝ่ายตรงข้าม 1 ใบ ที่มี Cost น้อยกว่า Cost ของการ์ดที่เราเลือก",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "สว นาโนแมชชีน",
    type: "Avatar",
    soi: 2,
    print: "BT06-037",
    rare: "UR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ไม่ถูกทำลายจากการต่อสู้จาก Avatar ที่ POWER น้อยกว่า 10 และ ไม่ถูกทำลายจากความสามารถของ Magic Card  \nต่อเนื่อง Avatar ใบนี้ไม่สามารถถูกเปลี่ยนการควบคุมได้",
    cost: 8,
    gem: 1,
    power: 8,
    symbol: "หุ่นยนต์",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "สว นาโนแมชชีน",
    type: "Avatar",
    soi: 2,
    print: "BT06-037",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ไม่ถูกทำลายจากการต่อสู้จาก Avatar ที่ POWER น้อยกว่า 10 และ ไม่ถูกทำลายจากความสามารถของ Magic Card  \nต่อเนื่อง Avatar ใบนี้ไม่สามารถถูกเปลี่ยนการควบคุมได้",
    cost: 8,
    gem: 1,
    power: 8,
    symbol: "หุ่นยนต์",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "แมมมอธแช่แข็ง",
    type: "Avatar",
    soi: 2,
    print: "BT06-038",
    rare: "R",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ไม่สามารถ โจมตีได้\nต่อเนื่อง Avatar ใบนี้ไม่สามารถสวมใส่ Modification Magic ได้",
    cost: 5,
    gem: 1,
    power: 7,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "เรนะ นักล่าไดโนเสาร์",
    type: "Avatar",
    soi: 2,
    print: "BT06-039",
    rare: "SR",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar symbol กระปอม : ทำลาย Avatar ใบที่เป็นเป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ต่างชาติ",
    color: "เขียว",
  },
  {
    name: "เรนะ นักล่าไดโนเสาร์",
    type: "Avatar",
    soi: 2,
    print: "BT06-039",
    rare: "SCR",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar symbol กระปอม : ทำลาย Avatar ใบที่เป็นเป้าการโจมตี",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ต่างชาติ",
    color: "เขียว",
  },
  {
    name: "แมวเก็นไมฉะ",
    type: "Avatar",
    soi: 2,
    print: "BT06-040",
    rare: "C",
    mainEffect:
      "จุติ : เลือกปฏิบัติ \n1) อัญเชิญ Avatar แมวมัทฉะ 1 ใบ จากนรกเรา ลง Avatar Zone ฝ่ายเรา \n2) ถ้าใน Avatar Zone ฝ่ายเรา มี Avatar \"หมา\" หรือ \"แมว\" ใบอื่น 2 ใบขึ้นไป นำ Land Magic คาเฟ่หมาแมว 1 ใบ จาก Deck เราขึ้นมือ จากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "น้องมี่ 3.0",
    type: "Avatar",
    soi: 2,
    print: "BT06-041",
    rare: "R",
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "พ่อหนุ่มเทสดี",
    type: "Avatar",
    soi: 2,
    print: "BT06-042",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "พลเอกปั๊ดโธ่",
    type: "Avatar",
    soi: 2,
    print: "BT06-043",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 0,
    power: 2,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "พลเอกปักเป้า",
    type: "Avatar",
    soi: 2,
    print: "BT06-044",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 0,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "งานวิจัยของพระพรหม",
    type: "Magic",
    soi: 1,
    print: "BT06-045",
    rare: "R",
    mainEffect:
      "ทิ้งการ์ดจากบนมือเราทั้งหมด : ถ้าการ์ดที่ทิ้งมี 3 ใบขึ้นไป จั่วการ์ด 5 ใบ \nถ้าเราควบคุม Avatar \"พระพรหม\" ใน Avatar Zone เปลี่ยนความสามารถการ์ดใบนี้เป็น\nทิ้งการ์ดจากบนมือเราทั้งหมด : เลือกการ์ดที่ชอบจาก Deck เรา 1 ใบ และนำขึ้นมือ จากนั้นสับ Deck",
    subtype: "Normal",
    cost: 0,
    symbol: "เทพ",
  },
  {
    name: "คำสั่งของพระอิศวร",
    type: "Magic",
    soi: 1,
    print: "BT06-046",
    rare: "R",
    mainEffect:
      "เลือกปฏิบัติ :\n1) เลือก Avatar บน Avatar Zone ฝ่ายตรงข้าม 1 ใบ POWER -2\n2) เลือก Construct บน Construct Zone ฝ่ายตรงข้าม 1 ใบ POWER -2\nถ้าเราควบคุม Avatar \"พระอิศวร\" ใน Avatar Zone สามารถทำความสามารถ 1) และ 2)",
    subtype: "Normal",
    cost: 1,
    symbol: "เทพ",
  },
  {
    name: "จิตมุ่งมั่นของพระนารายณ์",
    type: "Magic",
    soi: 1,
    print: "BT06-047",
    rare: "R",
    mainEffect:
      "เลือก Avatar 1 ใบใน Avatar Zone ฝ่ายเราได้รับ : POWER +1 จนจบเทิร์น \nถ้าเราควบคุม Avatar \"พระนารายณ์\" ใน Avatar Zone สามารถเลือก Avatar ได้ สูงสุด 3 ใบ",
    subtype: "Normal",
    cost: 2,
    symbol: "เทพ",
  },
  {
    name: "เฮือกสุดท้าย",
    type: "Magic",
    soi: 2,
    print: "BT06-048",
    rare: "C",
    mainEffect: "สามารถใช้การ์ดนี้ได้เมื่ออยู่ในสถานะสาหัสเท่านั้น : จั่วการ์ด 4 ใบ จาก Deck เรา และ ในเทิร์นนี้สามารถใช้ Nomal Magic ที่ไม่ใช่ เฮือกสุดท้าย ได้อีก 1 ใบ",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "แผนลับของเหล่าพลเอก",
    type: "Magic",
    soi: 2,
    print: "BT06-049",
    rare: "R",
    mainEffect: "ส่ง Avatar \"พลเอก\" ที่ชื่อไม่ซ้ำกัน 3 ใบ จาก Avatar Zone ฝ่ายเราลงนรก : ส่งการ์ดบนสนามและบนมือของฝ่ายตรงข้ามทั้งหมดลงนรก และอัญเชิญ Avatar \"ทหาร\"  หรือ \"รด.\" ที่ชื่อไม่ซ้ำกัน จาก Deck เรา ได้มากสุด 3 ใบ ลงบน Avatar Zone ฝ่ายเรา จากนั้น สับ Deck",
    subtype: "Normal",
    cost: 4,
    symbol: "ทหาร",
  },
  {
    name: "ช่างมาแล้วววว",
    type: "Magic",
    soi: 2,
    print: "BT06-050",
    rare: "C",
    mainEffect: "เมื่อ Constuct Card จะถูกทำลาย : Construct ใบนั้น จะไม่ถูกทำลาย",
    subtype: "React",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "ธาตุไฟแตก ๆ",
    type: "Magic",
    soi: 2,
    print: "BT06-051",
    rare: "C",
    mainEffect:
      "ส่ง Avatar บน Avatar Zone ฝ่ายเราลงนรก : ทอยลูกเต๋า 1 ครั้ง จากนั้นแสดงผลตามผลลัพธ์ที่ได้\n- ออกคู่ ทำลาย Avatar ฝ่ายตรงข้าม 2 ใบ\n- ออกคี่ ทำลาย Avatar ฝ่ายเรา 1 ใบ",
    subtype: "React",
    cost: 1,
    symbol: "เทพ",
  },
  {
    name: "เสียงเรียกแห่งวัลฮัลลา",
    type: "Magic",
    soi: 2,
    print: "BT06-052",
    rare: "C",
    mainEffect:
      "ใช้ได้เมื่ออยู่ในสถานะ สาหัส เท่านั้น \nเมื่อฝ่ายตรงข้ามประกาศโจมตี ธรณีสูบ  5 ใบ : ยกเลิกการโจมตีนั้น และ อัญเชิญ \"เทพธิดาแห่งวัลฮัลลา\" ได้สูงสุด 4 ใบ จากนรกเราลงบน Avatar Zone ฝ่ายเรา\nถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar symbol เทพ สีม่วง หรือ Magic Card : นำการ์ดใบนี้ขึ้นมือ",
    subtype: "React",
    cost: 2,
    symbol: "เทพ",
  },
  {
    name: "พลังแฝง",
    type: "Magic",
    soi: 2,
    print: "BT06-053",
    rare: "R",
    mainEffect: "เมื่อ Avatar ฝ่ายเราต่อสู้ : Avatar ใบนั้น POWER +2 จนจบเทิร์น",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ลูกแก้วนาคา",
    type: "Magic",
    soi: 2,
    print: "BT06-054",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"นาค\" ที่เป็น Symbol สัตว์มหัศจรรย์ เท่านั้น\nAvatar ที่สวมใส่การ์ดใบนี้ POWER +2",
    subtype: "Modification",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "ไสยเวท ย้อนกลับ",
    type: "Magic",
    soi: 2,
    print: "BT06-055",
    rare: "SR",
    mainEffect: "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตี : ธรณีสูบ 2 ใบ ถ้า 1 ในนั้น เป็นการ์ด Magic เปลี่ยน สภาพ Avatar ที่สวมใส่การ์ดใบนี้จากนอนเป็นตื่น ความสามารถนี้สามารถใช้ได้ 4 ครั้ง ใน 1 เทิร์น",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ไสยเวท ย้อนกลับ",
    type: "Magic",
    soi: 2,
    print: "BT06-055",
    rare: "SCR",
    mainEffect: "เมื่อ Avatar ที่สวมใส่การ์ดใบนี้โจมตี : ธรณีสูบ 2 ใบ ถ้า 1 ในนั้น เป็นการ์ด Magic เปลี่ยน สภาพ Avatar ที่สวมใส่การ์ดใบนี้จากนอนเป็นตื่น ความสามารถนี้สามารถใช้ได้ 4 ครั้ง ใน 1 เทิร์น",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "เท่ระเบิด !!!!",
    type: "Magic",
    soi: 2,
    print: "BT06-056",
    rare: "C",
    mainEffect:
      "สวมใส่ได้ เฉพาะ Avatar \"ทหาร\" หรือ \"รด.\" เท่านั้น\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้ สั่งโจมตี : POWER +5 จนจบการต่อสู้ หลังจากนั้นทำลาย Avatar ที่สวมใส่การ์ดใบนี้",
    subtype: "Modification",
    cost: 2,
    symbol: "ทหาร",
  },
  {
    name: "กองถ่ายฤาษี",
    type: "Magic",
    soi: 2,
    print: "BT06-057",
    rare: "R",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar Symbol ฤาษี เท่านั้น\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้ต่อสู้ : Avatar ฝ่ายตรงข้ามที่ต่อสู้ด้วย POWER -1 จนจบการต่อสู้นั้น",
    subtype: "Modification",
    cost: 2,
    symbol: "ฤษี",
  },
  {
    name: "ดาบศักดิ์สิทธิ์ แกลลาติน",
    type: "Magic",
    soi: 2,
    print: "BT06-058",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"อัศวินโต๊ะกลม\" เท่านั้น \nAvatar ที่สวมใส่การ์ดใบนี้ จะไม่ถูกทำลายด้วยผลของ Magic Card ถ้าอยู่ในสภาพตื่น\nถ้าในเทิร์นนี้ ยังไม่ได้ใช้ Modification Magic สามารถธรณีสูบ 1 ใบ และนำการ์ดใบนี้ที่อยู่ในนรก ไปสวมใส่ให้ \"อัศวินโต๊ะกลม\" ใน Avatar Zone ฝ่ายเรา และนับว่าเป็นการใช้ Modification Magic",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "นรกในกรง",
    type: "Magic",
    soi: 2,
    print: "BT06-059",
    rare: "C",
    mainEffect:
      "ผู้เล่นทุกคนสามารถควบคุม Avatar ใน Avatar Zone ได้เพียง 3 ใบ \nเมื่อการ์ดใบนี้ถูกใช้บน Land Magic Zone ผู้เล่นใดก็ตามที่ควบคุม Avatar บน Avatar Zone มากกว่า 3 ใบ ให้ส่ง Avatar ลงนรก จนเหลือ Avatar บน Avatar Zone แค่ 3 ใบ",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "คาเฟ่หมาแมว",
    type: "Magic",
    soi: 2,
    print: "BT06-060",
    rare: "SR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ในช่วง End Phase ของเรา : นำ Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ ใน Avatar Zone ฝ่ายเรากลับเข้า Deck และ อัญเชิญ Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ  จาก Deck เรา ที่ชื่อไม่ซ้ำกับ Avatar ที่กลับเข้า Deck ไป ด้วยความสามารถนี้ลงบน Avatar Zone ฝ่ายเรา และ สับ Deck จากนั้น Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ บน Avatar Zone ฝ่ายเรา POWER +1",
    subtype: "Land",
    cost: 3,
    symbol: "สัตว์",
  },
  {
    name: "คาเฟ่หมาแมว",
    type: "Magic",
    soi: 2,
    print: "BT06-060",
    rare: "SCR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ในช่วง End Phase ของเรา : นำ Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ ใน Avatar Zone ฝ่ายเรากลับเข้า Deck และ อัญเชิญ Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ  จาก Deck เรา ที่ชื่อไม่ซ้ำกับ Avatar ที่กลับเข้า Deck ไป ด้วยความสามารถนี้ลงบน Avatar Zone ฝ่ายเรา และ สับ Deck จากนั้น Avatar \"หมา\" หรือ \"แมว\" ที่เป็น Symbol สัตว์ 1 ใบ บน Avatar Zone ฝ่ายเรา POWER +1",
    subtype: "Land",
    cost: 3,
    symbol: "สัตว์",
  },
  {
    name: "สภาแบงค์",
    type: "Magic",
    soi: 2,
    print: "BT06-061",
    rare: "SR",
    mainEffect:
      "Avatar \"แบงค์\" ทุกใบบนมือ Cost -1\nGem ของ Avatar \"แบงค์\" ทุกใบบนมือ จะกลายเป็น Gem ไร้สี",
    subtype: "Land",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "สภาแบงค์",
    type: "Magic",
    soi: 2,
    print: "BT06-061",
    rare: "SCR",
    mainEffect:
      "Avatar \"แบงค์\" ทุกใบบนมือ Cost -1\nGem ของ Avatar \"แบงค์\" ทุกใบบนมือ จะกลายเป็น Gem ไร้สี",
    subtype: "Land",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ถ้ำนาคา",
    type: "Magic",
    soi: 2,
    print: "BT06-062",
    rare: "R",
    mainEffect: "Avatar \"นาค\" ที่เป็น Symbol สัตว์มหัศจรรย์ POWER +1",
    subtype: "Land",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ประตูวัลฮัลลา",
    type: "Magic",
    soi: 2,
    print: "BT06-063",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ธรณีสูบ 2 ใบ : เลือก Avatar \"เทพธิดาแห่งวัลฮัลลา\" 1 ใบ ในนรกฝ่ายเรานำกลับขึ้นมือ",
    subtype: "Land",
    cost: 2,
    symbol: "เทพ",
  },
  {
    name: "เวทีเพื่อชีวิต",
    type: "Construct",
    soi: 2,
    print: "BT06-064",
    rare: "C",
    mainEffect: "ต่อเนื่อง ใน Battle Phase ฝ่ายเรา Avatar ทุกใบใน Avatar Zone ฝ่ายเรา POWER +1",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "สิ่งก่อสร้าง",
    color: "แดง",
  },
  {
    name: "รูปปั้นพระอิศวร",
    type: "Construct",
    soi: 2,
    print: "BT06-065",
    rare: "SR",
    mainEffect: "ในช่วง Draw Phase ของเรา สามารถสอดแนม 2 ใบ และนำการ์ด Symbol เทพ 1 ใบ จากที่สอดแนม ขึ้นมือ แทนการจั่วปกติ การ์ดที่เหลือนำไว้ล่างสุดของ Deck",
    cost: 5,
    gem: 1,
    power: 4,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "ยานสำรวจ R18",
    type: "Construct",
    soi: 2,
    print: "BT06-066",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ถ้าเราควบคุม Avatar \"มนุษย์ดาว R18\" ใน Avatar Zone : นำการ์ด Avatar 1 ใบ ใน นรกฝ่ายตรงข้าม ที่ Cost 5 หรือมากกว่า มาไว้ที่ Magic Zone ฝ่ายเรา จากนั้น เปลี่ยนชื่อ Avatar ใบนั้นเป็น \"ข้ารับใช้ของ มนุษย์ดาว R18\" และเปลี่ยนเป็น Symbol เอเลี่ยน",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "ฟ้า",
  },
  {
    name: "กองไฟลูกเสือ",
    type: "Construct",
    soi: 2,
    print: "BT06-067",
    rare: "R",
    mainEffect: "Avatar ที่มี Cost 2 หรือน้อยกว่า ทุกใบใน Avatar Zone ฝ่ายเราได้รับ สามัคคี",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "สิ่งก่อสร้าง",
    color: "ฟ้า",
  },
  {
    name: "ป้อมยาม",
    type: "Construct",
    soi: 2,
    print: "BT06-068",
    rare: "R",
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Construct ใบนี้ อยู่บน Construct Zone ฝ่ายตรงข้ามไม่สามารถโจมตี LIFE Card เราได้",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "สิ่งก่อสร้าง",
    color: "ม่วง",
  },
  {
    name: "หุบเขา 3 พลเอก",
    type: "Construct",
    soi: 2,
    print: "BT06-069",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่อยู่ใน Construct Zone เปลี่ยนความสามารถ Magic Card ใบดำใบแดง เป็น\nสอดแนม 3 ใบ : เลือกการ์ด Avatar {Symbol : คน} Cost ไม่เกิน 4 สีเขียว 1 ใบ จากที่สอดแนม อัญเชิญลงบน Avatar Zone ฝ่ายเรา การ์ดที่เหลือเรียงและนำไว้ใต้ Deck\nต่อเนื่อง ตราบเท่าที่อยู่ใน Construct Zone สามารถใช้ Magic Card ใบดำใบแดง เทิร์นละกี่ใบก็ได้",
    cost: 3,
    gem: 2,
    power: 4,
    symbol: "ทหาร",
    color: "เขียว",
  },
  {
    name: "ตู้วารีบำบัด",
    type: "Construct",
    soi: 2,
    print: "BT06-070",
    rare: "SR",
    mainEffect: "สั่งใช้ ในช่วง Draw Phase ฝ่ายเรา สามารถทำลายการ์ดใบนี้ : เลือก LIFE Card 1 ใบของเราที่หงายอยู่ จากนั้นคว่ำการ์ดใบนั้น",
    cost: 5,
    gem: 1,
    power: 1,
    symbol: "สิ่งก่อสร้าง",
    color: "เขียว",
  },
  {
    name: "ตู้วารีบำบัด",
    type: "Construct",
    soi: 2,
    print: "BT06-070",
    rare: "SCR",
    mainEffect: "สั่งใช้ ในช่วง Draw Phase ฝ่ายเรา สามารถทำลายการ์ดใบนี้ : เลือก LIFE Card 1 ใบของเราที่หงายอยู่ จากนั้นคว่ำการ์ดใบนั้น",
    cost: 5,
    gem: 1,
    power: 1,
    symbol: "สิ่งก่อสร้าง",
    color: "เขียว",
  },
];
