import { Card } from "@/src/types/cards";

export const CARDS_BT07: Card[] = [
  {
    name: "วันชัยเปรตรุ่นพ่อ",
    type: "Avatar",
    soi: 2,
    print: "BT07-001",
    rare: "UR",
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้จะเพิ่ม POWER ตามจำนวน LIFE Card ของทั้ง 2 ฝ่าย ที่ถูกหงายอยู่ใบละ 1\nเทิร์นละครั้ง สั่งใช้ หงาย LIFE Card เรา ใบบนสุด : สั่งใช้ผลความสามารถ LIFE Card ใบนั้น จนจบเทิร์น หากความสามารถนั้นระบุว่า \"ใน Main Phase ถัดไป\" ให้ทำความสามารถในเทิร์นนี้ทันที",
    cost: 4,
    gem: 0,
    power: 1,
    symbol: "เปรต",
    color: "แดง",
  },
  {
    name: "วันชัยเปรตรุ่นพ่อ",
    type: "Avatar",
    soi: 2,
    print: "BT07-001",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง การ์ดใบนี้จะเพิ่ม POWER ตามจำนวน LIFE Card ของทั้ง 2 ฝ่าย ที่ถูกหงายอยู่ใบละ 1\nเทิร์นละครั้ง สั่งใช้ หงาย LIFE Card เรา ใบบนสุด : สั่งใช้ผลความสามารถ LIFE Card ใบนั้น จนจบเทิร์น หากความสามารถนั้นระบุว่า \"ใน Main Phase ถัดไป\" ให้ทำความสามารถในเทิร์นนี้ทันที",
    cost: 4,
    gem: 0,
    power: 1,
    symbol: "เปรต",
    color: "แดง",
  },
  {
    name: "พระแม่อุมาเทวี",
    type: "Avatar",
    soi: 2,
    print: "BT07-002",
    rare: "R",
    mainEffect:
      "จุติ ทิ้งการ์ดบนมือ 1 ใบ : นำการ์ด Symbol เทพ ยกเว้น {only} จากในนรกเรา 1 ใบ ขึ้นมือ \nสั่งใช้ ในเทิร์นใครก็ได้  ถ้าฝ่ายตรงข้ามมี Avatar \"พระอิศวร\" ที่เจ้าของดั้งเดิมไม่ใช่ของตนเองบน Avatar Zone ส่ง Avatar ใบนี้ จาก Avatar Zone ลงนรก : อัญเชิญ จุติ เจ้าแม่กาลี จากใน Deck หรือ บนมือเรา ลงบน Avatar Zone ฝ่ายเรา ถ้าอัญเชิญจาก Deck ให้สับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "พระแม่อุมาเทวี",
    type: "Avatar",
    soi: 2,
    print: "BT07-002",
    rare: "SCR",
    mainEffect:
      "จุติ ทิ้งการ์ดบนมือ 1 ใบ : นำการ์ด Symbol เทพ ยกเว้น {only} จากในนรกเรา 1 ใบ ขึ้นมือ \nสั่งใช้ ในเทิร์นใครก็ได้  ถ้าฝ่ายตรงข้ามมี Avatar \"พระอิศวร\" ที่เจ้าของดั้งเดิมไม่ใช่ของตนเองบน Avatar Zone ส่ง Avatar ใบนี้ จาก Avatar Zone ลงนรก : อัญเชิญ จุติ เจ้าแม่กาลี จากใน Deck หรือ บนมือเรา ลงบน Avatar Zone ฝ่ายเรา ถ้าอัญเชิญจาก Deck ให้สับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "เจ้าแม่กาลี",
    type: "Avatar",
    soi: 2,
    print: "BT07-003",
    rare: "UR",
    mainEffect: "จุติ : ทำลาย Avatar {symbol เทพ} 1 ใบบน Avatar Zone ของฝ่ายตรงข้าม ถ้าไม่ได้ทำลายให้ จั่วการ์ด 1 ใบ",
    cost: 8,
    gem: 1,
    power: 7,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "เจ้าแม่กาลี",
    type: "Avatar",
    soi: 2,
    print: "BT07-003",
    rare: "SCR",
    mainEffect: "จุติ : ทำลาย Avatar {symbol เทพ} 1 ใบบน Avatar Zone ของฝ่ายตรงข้าม ถ้าไม่ได้ทำลายให้ จั่วการ์ด 1 ใบ",
    cost: 8,
    gem: 1,
    power: 7,
    symbol: "เทพ",
    color: "แดง",
  },
  {
    name: "พรีวิวบอย",
    type: "Avatar",
    soi: 2,
    print: "BT07-004",
    rare: "SR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เลือก Avatar บน Avatar Zone ฝ่ายเรา 1 ใบ : Avatar ใบนี้จะมี POWER เพิ่มขึ้นเท่ากับ POWER ของ Avatar ที่เลือก จนจบเทิร์น",
    cost: 4,
    gem: 2,
    power: 0,
    symbol: "คน",
    color: "แดง",
    ex: "โดนใจ",
  },
  {
    name: "ฤๅษีพระเจ้าตา",
    type: "Avatar",
    soi: 2,
    print: "BT07-005",
    rare: "R",
    mainEffect: "พอดี จุติ : นำ Magic Card ที่เป็น Symbol ฤๅษี จาก Deck เรา 1 ใบ ขึ้นมือ จากนั้นสับ Deck",
    cost: 2,
    gem: 0,
    power: 2,
    symbol: "ฤษี",
    color: "แดง",
  },
  {
    name: "อนันตวดี ราชินีแห่งนาค",
    type: "Avatar",
    soi: 2,
    print: "BT07-006",
    rare: "C",
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ Avatar \"นาค\" ที่เป็น {symbol สัตว์มหัศจรรย์} : POWER + 3 ให้กับ Avatar ที่อัญเชิญ จนจบเทิร์น \nเมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ อนันต์ ราชาแห่งนาค Avatar ใบนี้จะถือว่ามี 6 GEM สีแดง\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol สัตว์มหัศจรรย์} เท่านั้น",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
  },
  {
    name: "สัตว์ทดลอง #1",
    type: "Avatar",
    soi: 2,
    print: "BT07-007",
    rare: "C",
    mainEffect: "ถ้าในนรกฝ่ายเรา มี Avatar ที่ชื่อไม่ซ้ำกัน 10 ใบขึ้นไป Avatar ใบนี้ จะถือว่ามี Gem 8 ไร้สี",
    cost: 0,
    gem: 0,
    power: 0,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
  },
  {
    name: "ตำรวจไซบอร์ค จ่านิ่ง",
    type: "Avatar",
    soi: 2,
    print: "BT07-008",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ : ฝ่ายตรงข้ามจั่วการ์ด 1 ใบ จากนั้น ฝ่ายตรงข้ามแสดงการ์ด 1 ใบ จากบนมือ นำการ์ดที่แสดงไปไว้บนสุดของ Deck",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "เจมี่ ขยะสังคม",
    type: "Avatar",
    soi: 2,
    print: "BT07-009",
    rare: "C",
    mainEffect:
      "จุติ : สอดแนม 7 ใบ นำ อาวุธชีวภาพ เอ็มตัวเต็ง 1 ใบ จากที่สอดแนม และนำขึ้นมือ การ์ดที่เหลือเรียงและนำไว้ในใต้Deck เรา\nคำสั่งเสีย : สอดแนม 3 ใบ นำ อาวุธชีวภาพ เอ็มตัวเต็ง 1 ใบ จากที่สอดแนม และนำขึ้นมือ การ์ดที่เหลือเรียงและนำไว้ใต้ Deck เรา",
    cost: 2,
    gem: 2,
    power: 3,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "น้องไอซ์ จี่สมอง",
    type: "Avatar",
    soi: 2,
    print: "BT07-010",
    rare: "R",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ประกาศโจมตี Avatar ที่มี POWER เท่ากับ หรือ น้อยกว่า 3 : ทำลาย Avatar ใบที่เป็นเป้าการโจมตี",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ไอ้แม๊ก ขยะสังคม",
    type: "Avatar",
    soi: 2,
    print: "BT07-011",
    rare: "C",
    mainEffect: "คำสั่งเสีย : นำการ์ดที่อยู่ใน Magic Zone ของฝ่ายตรงข้าม 1 ใบ กลับขึ้นมือเจ้าของ",
    cost: 2,
    gem: 0,
    power: 2,
    symbol: "กะปอม",
    color: "ฟ้า",
  },
  {
    name: "ครุฑสุบรรณ เจ้าเวหา",
    type: "Avatar",
    soi: 2,
    print: "BT07-012",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar \"ครุฑ\" หรือ \"ขนมณี แฟลร์\" รวมกันสูงสุด 3 ใบ กลับเข้า Deck จากนั้นทำความสามารถตามจำนวนการ์ดที่นำกลับเข้า Deck : \n- 1 ใบ อัญเชิญ \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone Avatar ใบนั้น ได้รับ \"เมื่อจบเทิร์น นำ Avatar ใบนี้ขึ้นมือ\" \n- 2 ใบ อัญเชิญ \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone \n- 3 ใบ อัญเชิญ \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone Avatar ใบนั้น ได้รับ POWER+2 จนจบเทิร์น\nจากนั้นสับ Deck",
    cost: 6,
    gem: 4,
    power: 5,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "ครุฑสุบรรณ เจ้าเวหา",
    type: "Avatar",
    soi: 2,
    print: "BT07-012",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar \"ครุฑ\" หรือ \"ขนมณี แฟลร์\" รวมกันสูงสุด 3 ใบ กลับเข้า Deck จากนั้นทำความสามารถตามจำนวนการ์ดที่นำกลับเข้า Deck : \n- 1 ใบ อัญเชิญ \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone Avatar ใบนั้น ได้รับ \"เมื่อจบเทิร์น นำ Avatar ใบนี้ขึ้นมือ\" \n- 2 ใบ อัญเชิญ \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone \n- 3 ใบ อัญเชิญ \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone Avatar ใบนั้น ได้รับ POWER+2 จนจบเทิร์น\nจากนั้นสับ Deck",
    cost: 6,
    gem: 4,
    power: 5,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "ครุฑเวนไตย เจ้ากำลัง",
    type: "Avatar",
    soi: 2,
    print: "BT07-013",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar \"ครุฑ\" ที่ไม่ใช่ ครุฑเวนไตย เจ้ากำลัง 1ใบ  หรือ \"ขนมณี แฟลร์\"  1 ใบในนรกเรา กลับใต้ Deck :\nPOWER +3 จนจบเทิร์น",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
  },
  {
    name: "ครุฑวัสสวัส เจ้าโลก",
    type: "Avatar",
    soi: 2,
    print: "BT07-014",
    rare: "SR",
    mainEffect:
      "จุติ นำ Avatar \"ครุฑ\" หรือ \"ขนมณี แฟลร์\" จากในนรก 1 ใบ กลับใต้ Deck : \nอัญเชิญ Avatar \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 5,
    gem: 2,
    power: 5,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
  },
  {
    name: "ครุฑวัสสวัส เจ้าโลก",
    type: "Avatar",
    soi: 2,
    print: "BT07-014",
    rare: "SCR",
    mainEffect:
      "จุติ นำ Avatar \"ครุฑ\" หรือ \"ขนมณี แฟลร์\" จากในนรก 1 ใบ กลับใต้ Deck : \nอัญเชิญ Avatar \"ครุฑ\" จากใน Deck Cost 4 หรือต่ำกว่า 1 ใบ ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 5,
    gem: 2,
    power: 5,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
  },
  {
    name: "ครุฑสัจจะ เจ้าแห่งแสง",
    type: "Avatar",
    soi: 2,
    print: "BT07-015",
    rare: "R",
    mainEffect:
      "จุติ ทิ้ง Avatar \"ครุฑ\" หรือ \"ขนมณี แฟลร์\" 1 ใบ จากมือ ลงนรก : \nอัญเชิญ Avatar \"ครุฑ\" Cost 4 หรือต่ำกว่า 1 ใบ จากใน Deck ลง Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
  },
  {
    name: "ครุฑปรเมศวร เจ้าสมบัติ",
    type: "Avatar",
    soi: 2,
    print: "BT07-016",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
  },
  {
    name: "บึงทมิฬ  People - คุณตะพาบ",
    type: "Avatar",
    soi: 2,
    print: "BT07-017",
    rare: "R",
    mainEffect: "คำสั่งเสีย : นำ วอเตอร์แมน จากใน นรก กลับเข้า Deck แล้วสับ จากนั้น จั่วการ์ด 1 ใบ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "ปลา",
    color: "ฟ้า",
  },
  {
    name: "ราชาหิมะ บิง",
    type: "Avatar",
    soi: 2,
    print: "BT07-018",
    rare: "R",
    mainEffect: "Cost ของการ์ดใบนี้บนมือ จะลดลงตามจำนวน Avatar \"ทหารหิมะ\" ในนรกเรา ใบละ 1",
    cost: 10,
    gem: 2,
    power: 6,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "ราชินีหิมะ ชีหลิน",
    type: "Avatar",
    soi: 2,
    print: "BT07-019",
    rare: "SR",
    mainEffect:
      "ต่อเนื่อง POWER +2 ตามจำนวน \"ทหารหิมะ\" ใน Avatar Zone ฝ่ายเรา\nต่อเนื่อง POWER +3 ตามจำนวน \"ราชาหิมะ\" ใน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "ราชินีหิมะ ชีหลิน",
    type: "Avatar",
    soi: 2,
    print: "BT07-019",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง POWER +2 ตามจำนวน \"ทหารหิมะ\" ใน Avatar Zone ฝ่ายเรา\nต่อเนื่อง POWER +3 ตามจำนวน \"ราชาหิมะ\" ใน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "พลทหารหิมะ",
    type: "Avatar",
    soi: 2,
    print: "BT07-020",
    rare: "C",
    mainEffect: "สามารถใส่การ์ดใบนี้ใน Deck ได้มากสุด 12 ใบ",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
    customLimit: 12,
  },
  {
    name: "อัศวินแบงค์",
    type: "Avatar",
    soi: 2,
    print: "BT07-021",
    rare: "R",
    mainEffect: "สั่งใช้ จากบนมือ แสดงการ์ดใบนี้ และ ทิ้งการ์ดใบอื่นจากมือกี่ใบก็ได้ให้ GEM รวมกันให้เท่ากับ 3 (ไม่สามารถทิ้งการ์ดที่ไม่มี GEM ได้) : อัญเชิญการ์ดใบนี้ ลงบน Avatar Zone ฝ่ายเรา โดยที่ POWER ตั้งต้นของการ์ดใบนี้จะเท่ากับ 3",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "ชาช่าจัง ไอดอลคนเก่ง",
    type: "Avatar",
    soi: 2,
    print: "BT07-022",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ไม่สามารถโจมตีได้ และ สามารถสวมใส่การ์ดได้เฉพาะการ์ด \"โอตะ\"\nเทิร์นละครั้ง สั่งใช้ ทำลาย การ์ด \"โอตะ\" ที่สวมใส่อยู่ให้กับ Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเรา 1 ใบ : ในเทิร์นนี้ Avatar ใบนี้จะสามารถโจมตีได้",
    cost: 4,
    gem: 2,
    power: 6,
    symbol: "คน",
    color: "ฟ้า",
  },
  {
    name: "พี่หน่วง พิธีกรผมสวย",
    type: "Avatar",
    soi: 2,
    print: "BT07-023",
    rare: "UR",
    mainEffect:
      "จุติ : นำ \"ยานรายการ เถียงทันหน่วง\" จาก Deck หรือ นรก 1 ใบขึ้นมือ หากนำจาก Deck ให้สับ Deck\nเทิร์นละครั้ง สั่งใช้ ถ้าใน Construct Zone ฝ่ายเรามี \"ยานรายการ เถียงทันหน่วง\" ทิ้งการ์ดบนมือ 1 ใบ : เลือก Avatar ฝ่ายตรงข้าม 1 ใบ ใน Avatar Zone ที่มี สามัคคี , เตะไข่ , โล่มนุษย์ หรือ คำสั่งเสีย นำ Avatar ใบนั้น มาไว้ที่ Magic Zone ฝ่ายเรา\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar ที่อยู่ใน Magic Zone ฝ่ายเรา 1 ใบ กลับขึ้นมือเจ้าของาของ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่หน่วง พิธีกรผมสวย",
    type: "Avatar",
    soi: 2,
    print: "BT07-023",
    rare: "SCR",
    mainEffect:
      "จุติ : นำ \"ยานรายการ เถียงทันหน่วง\" จาก Deck หรือ นรก 1 ใบขึ้นมือ หากนำจาก Deck ให้สับ Deck\nเทิร์นละครั้ง สั่งใช้ ถ้าใน Construct Zone ฝ่ายเรามี \"ยานรายการ เถียงทันหน่วง\" ทิ้งการ์ดบนมือ 1 ใบ : เลือก Avatar ฝ่ายตรงข้าม 1 ใบ ใน Avatar Zone ที่มี สามัคคี , เตะไข่ , โล่มนุษย์ หรือ คำสั่งเสีย นำ Avatar ใบนั้น มาไว้ที่ Magic Zone ฝ่ายเรา\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar ที่อยู่ใน Magic Zone ฝ่ายเรา 1 ใบ กลับขึ้นมือเจ้าของาของ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่หน่วง พิธีกรผมสวย",
    type: "Avatar",
    soi: 2,
    print: "BT07-023",
    rare: "PR",
    mainEffect:
      "จุติ : นำ \"ยานรายการ เถียงทันหน่วง\" จาก Deck หรือ นรก 1 ใบขึ้นมือ หากนำจาก Deck ให้สับ Deck\nเทิร์นละครั้ง สั่งใช้ ถ้าใน Construct Zone ฝ่ายเรามี \"ยานรายการ เถียงทันหน่วง\" ทิ้งการ์ดบนมือ 1 ใบ : เลือก Avatar ฝ่ายตรงข้าม 1 ใบ ใน Avatar Zone ที่มี สามัคคี , เตะไข่ , โล่มนุษย์ หรือ คำสั่งเสีย นำ Avatar ใบนั้น มาไว้ที่ Magic Zone ฝ่ายเรา\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar ที่อยู่ใน Magic Zone ฝ่ายเรา 1 ใบ กลับขึ้นมือเจ้าของาของ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่หน่วง พิธีกรผมสวย",
    type: "Avatar",
    soi: 2,
    print: "BT07-023",
    rare: "CBR",
    mainEffect:
      "จุติ : นำ \"ยานรายการ เถียงทันหน่วง\" จาก Deck หรือ นรก 1 ใบขึ้นมือ หากนำจาก Deck ให้สับ Deck\nเทิร์นละครั้ง สั่งใช้ ถ้าใน Construct Zone ฝ่ายเรามี \"ยานรายการ เถียงทันหน่วง\" ทิ้งการ์ดบนมือ 1 ใบ : เลือก Avatar ฝ่ายตรงข้าม 1 ใบ ใน Avatar Zone ที่มี สามัคคี , เตะไข่ , โล่มนุษย์ หรือ คำสั่งเสีย นำ Avatar ใบนั้น มาไว้ที่ Magic Zone ฝ่ายเรา\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar ที่อยู่ใน Magic Zone ฝ่ายเรา 1 ใบ กลับขึ้นมือเจ้าของาของ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "คุณเก่งพลังช้าง",
    type: "Avatar",
    soi: 2,
    print: "BT07-024",
    rare: "R",
    mainEffect:
      "จุติ ทำลาย Avatar ฝ่ายตรงข้ามที่อยู่ใน Magic Zone ฝ่ายเรา : Avatar ใบนี้ POWER +3\nต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี \"พี่หน่วง\" Avatar ใบนี้ POWER +1",
    cost: 5,
    gem: 3,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "ทนายเตะปาก",
    type: "Avatar",
    soi: 2,
    print: "BT07-025",
    rare: "C",
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี \"พี่หน่วง\" Avatar ใบนี้ได้รับ เตะไข่",
    cost: 3,
    gem: 4,
    power: 1,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "ทนายกิ๊บ",
    type: "Avatar",
    soi: 2,
    print: "BT07-026",
    rare: "C",
    mainEffect: "ต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี \"พี่หน่วง\" Avatar ใบนี้ POWER +2",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่วัฒน์ BGN",
    type: "Avatar",
    soi: 2,
    print: "BT07-027",
    rare: "UR",
    mainEffect:
      "พอดี จุติ : ผู้เล่นทุกคน จั่วหรือทิ้งการ์ดบนมือ จนมีมือเท่ากับ 5 ใบ จากนั้น แสดงการ์ดบนมือทั้งหมด นำผลรวมของ GEM มารวมกัน ผู้เล่นที่มี GEM น้อยกว่า มีสิทธิ์ เลือกปฏิบัติ 1 อย่าง\n1) นำการ์ด 2 ใบ จากใต้ Deck เรา ขึ้นมือ\n2) Avatar บน Avatar Zone ฝ่ายเราทุกใบ ณ ขณะนั้น POWER +2 \n3) ควบคุม Avatar ฝ่ายตรงข้าม 1 ใบ จนจบ Draw Phase ถัดไปของเจ้าของ Avatar ใบนั้น\n#สามารถใช้ความของ Avatar ชื่อ พี่วัฒน์ BGN ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 5,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่วัฒน์ BGN",
    type: "Avatar",
    soi: 2,
    print: "BT07-027",
    rare: "SCR",
    mainEffect:
      "พอดี จุติ : ผู้เล่นทุกคน จั่วหรือทิ้งการ์ดบนมือ จนมีมือเท่ากับ 5 ใบ จากนั้น แสดงการ์ดบนมือทั้งหมด นำผลรวมของ GEM มารวมกัน ผู้เล่นที่มี GEM น้อยกว่า มีสิทธิ์ เลือกปฏิบัติ 1 อย่าง\n1) นำการ์ด 2 ใบ จากใต้ Deck เรา ขึ้นมือ\n2) Avatar บน Avatar Zone ฝ่ายเราทุกใบ ณ ขณะนั้น POWER +2 \n3) ควบคุม Avatar ฝ่ายตรงข้าม 1 ใบ จนจบ Draw Phase ถัดไปของเจ้าของ Avatar ใบนั้น\n#สามารถใช้ความของ Avatar ชื่อ พี่วัฒน์ BGN ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 5,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
    ex: "โดนใจ",
  },
  {
    name: "ไอ้ดำ จากนรก",
    type: "Avatar",
    soi: 2,
    print: "BT07-028",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ หลังจากจบการต่อสู้ที่ Avatar ใบนี้โจมตี เซ่นไหว้ Avatar ใบอื่นบน Avatar Zone ฝ่ายเรา 1 ใบ : เปลี่ยนสภาพ Avatar ใบนี้เป็นสภาพตื่น",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "จอมเวท กาลู",
    type: "Avatar",
    soi: 2,
    print: "BT07-029",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดบนมือ 1 ใบ : นำ Magic Card \"คาถา\" 1 ใบ จากใน Deck หรือ นรก ขึ้นมือ หากนำจาก Deck ให้สับ Deck\nอัตโนมัติ เทิร์นละครั้ง เมื่อมีการใช้ \"คาถา\" : จั่วการ์ด 1 ใบ\n#สามารถใช้ความสามารถของ Avatar ชื่อ จอมเวท กาลู ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ม่วง",
  },
  {
    name: "จอมเวท กาลู",
    type: "Avatar",
    soi: 2,
    print: "BT07-029",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดบนมือ 1 ใบ : นำ Magic Card \"คาถา\" 1 ใบ จากใน Deck หรือ นรก ขึ้นมือ หากนำจาก Deck ให้สับ Deck\nอัตโนมัติ เทิร์นละครั้ง เมื่อมีการใช้ \"คาถา\" : จั่วการ์ด 1 ใบ\n#สามารถใช้ความสามารถของ Avatar ชื่อ จอมเวท กาลู ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ม่วง",
  },
  {
    name: "จอมเวท อะปัด",
    type: "Avatar",
    soi: 2,
    print: "BT07-030",
    rare: "R",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : ในเทิร์นนี้ผู้เล่นที่สั่งใช้ความสามารถนี้ สามารถใช้ Normal Magic \"คาถา\" เพิ่มได้ 1 ใบ นอกเหนือจากการใช้ Normal Magic ปกติ\n#สามารถใช้ความสามารถของ Avatar ชื่อ จอมเวท อะปัด ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "จอมเวท เบล่า",
    type: "Avatar",
    soi: 2,
    print: "BT07-031",
    rare: "SR",
    mainEffect:
      "จุติ ถ้า Avatar Zone ฝ่ายเรามี Avatar \"จอมเวทย์\" ชื่ออื่น : เลือก Normal Magic Card \"คาถา\" 1 ใบ จากในนรกฝ่ายเรา และ สั่งใช้ผลความสามารถของการ์ดใบนั้น\n#สามารถใช้ความสามารถของ Avatar ชื่อ จอมเวท เบล่า ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ม่วง",
  },
  {
    name: "จอมเวท เบล่า",
    type: "Avatar",
    soi: 2,
    print: "BT07-031",
    rare: "SCR",
    mainEffect:
      "จุติ ถ้า Avatar Zone ฝ่ายเรามี Avatar \"จอมเวทย์\" ชื่ออื่น : เลือก Normal Magic Card \"คาถา\" 1 ใบ จากในนรกฝ่ายเรา และ สั่งใช้ผลความสามารถของการ์ดใบนั้น\n#สามารถใช้ความสามารถของ Avatar ชื่อ จอมเวท เบล่า ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ม่วง",
  },
  {
    name: "อาวุธชีวภาพ เอ็มตัวเต็ง",
    type: "Avatar",
    soi: 2,
    print: "BT07-032",
    rare: "SR",
    mainEffect:
      "ต่อเนื่อง Avatar ใบนี้ไม่สามารถโจมตีได้\nเทิร์นละครั้ง สั่งใช้ ในช่วง End Phase เรา : ทำลาย Avatar ของฝ่ายตรงข้าม 1 ใบ หลังจากนั้น ทำความเสียหายใส่ LIFE Card ใบบนสุดของ ฝ่ายตรงข้าม 1 ครั้ง",
    cost: 6,
    gem: 3,
    power: 0,
    symbol: "คน",
    color: "ม่วง",
    ex: "Only #1",
  },
  {
    name: "เดซี่ แห่งสายรุ้ง",
    type: "Avatar",
    soi: 2,
    print: "BT07-033",
    rare: "SR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ในช่วง End Phase : อัญเชิญ Avatar \"ผีเสื้อ\" ที่เป็น Symbol สัตว์มหัศจรรย์ 1 ใบ จาก Deck ลง Avatar Zone ฝ่ายเรา จากนั้น สับ Deck\nต่อเนื่อง Avatar \"ผีเสื้อ\" ที่เป็น Symbol สัตว์มหัศจรรย์ ทุกใบ บน Avatar Zone ฝ่ายเรา POWER +1 และได้รับ โล่มนุษย์",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "สัตว์มหัศจรรย์",
    color: "ม่วง",
  },
  {
    name: "เดซี่ แห่งสายรุ้ง",
    type: "Avatar",
    soi: 2,
    print: "BT07-033",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ในช่วง End Phase : อัญเชิญ Avatar \"ผีเสื้อ\" ที่เป็น Symbol สัตว์มหัศจรรย์ 1 ใบ จาก Deck ลง Avatar Zone ฝ่ายเรา จากนั้น สับ Deck\nต่อเนื่อง Avatar \"ผีเสื้อ\" ที่เป็น Symbol สัตว์มหัศจรรย์ ทุกใบ บน Avatar Zone ฝ่ายเรา POWER +1 และได้รับ โล่มนุษย์",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "สัตว์มหัศจรรย์",
    color: "ม่วง",
  },
  {
    name: "ตำรวจนอกเครื่องแบบ ไซเฮย์",
    type: "Avatar",
    soi: 2,
    print: "BT07-034",
    rare: "SR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ จากบนมือ : ประกาศประเภทของการ์ดใบบนสุดของ Deck ฝ่ายตรงข้าม จากนั้น สอดแนม Deck ฝ่ายตรงข้าม 1 ใบ \n- ถ้าการ์ดใบนั้นเป็นประเภทที่เราประกาศไว้ข้างต้น อัญเชิญ การ์ดใบนี้โดยไม่ต้องจ่าย Cost และส่งการ์ดที่ สอดแนม ลงนรก\n- ถ้าการ์ดที่สอดแนมไม่ใช่ประเภทการ์ดที่ประกาศนำการ์ดที่ สอดแนม ไว้ที่เดิมและทิ้งการ์ดใบนี้",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "ตำรวจนอกเครื่องแบบ ไซเฮย์",
    type: "Avatar",
    soi: 2,
    print: "BT07-034",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ จากบนมือ : ประกาศประเภทของการ์ดใบบนสุดของ Deck ฝ่ายตรงข้าม จากนั้น สอดแนม Deck ฝ่ายตรงข้าม 1 ใบ \n- ถ้าการ์ดใบนั้นเป็นประเภทที่เราประกาศไว้ข้างต้น อัญเชิญ การ์ดใบนี้โดยไม่ต้องจ่าย Cost และส่งการ์ดที่ สอดแนม ลงนรก\n- ถ้าการ์ดที่สอดแนมไม่ใช่ประเภทการ์ดที่ประกาศนำการ์ดที่ สอดแนม ไว้ที่เดิมและทิ้งการ์ดใบนี้",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "ตำรวจไฟแรง เอนโว่",
    type: "Avatar",
    soi: 2,
    print: "BT07-035",
    rare: "R",
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี Avatar : ประกาศประเภทของการ์ดใบบนสุดของ Deck ฝ่ายตรงข้าม จากนั้น สอดแนม Deck ฝ่ายตรงข้าม 1 ใบ  \n- ถ้าการ์ดใบนั้นเป็นประเภทที่เราประกาศไว้ข้างต้น ทำลาย Avatar ที่การ์ดใบนี้โจมตี และส่งการ์ดที่ สอดแนม ลงนรก\n- ถ้าการ์ดที่สอดแนมไม่ใช่ประเภทการ์ดที่ประกาศนำการ์ดที่ สอดแนม ไว้ที่เดิม",
    cost: 5,
    gem: 1,
    power: 4,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "ตั๊กแตนหยิน",
    type: "Avatar",
    soi: 2,
    print: "BT07-036",
    rare: "UR",
    mainEffect:
      "จุติ : หงาย LIFE Card ใบบนสุดของเรา 1 ใบ จากนั้นเลือกคว่ำ LIFE Card ของเรา 1 ใบ ความสามารถนี้สามารถคว่ำ LIFE Card ได้ แม้อยู่ในสถานะสาหัส\nเทิร์นละครั้ง สั่งใช้ ถ้าในสนามฝ่ายเรามี บัลลังก์ตั๊กแตนศตวรรษ ทิ้งการ์ดบนมือ 1 ใบ : เลือก LIFE Card ที่หงายอยู่ของเรา 1 ใบ สั่งใช้ผลความสามารถนั้น จนจบเทิร์น หากความสามารถนั้นระบุว่า \"ใน Main Phase ถัดไป\" ให้ทำความสามารถในเทิร์นนี้ทันที",
    cost: 5,
    gem: 0,
    power: 4,
    symbol: "แมลง",
    color: "เขียว",
  },
  {
    name: "ตั๊กแตนหยิน",
    type: "Avatar",
    soi: 2,
    print: "BT07-036",
    rare: "SCR",
    mainEffect:
      "จุติ : หงาย LIFE Card ใบบนสุดของเรา 1 ใบ จากนั้นเลือกคว่ำ LIFE Card ของเรา 1 ใบ ความสามารถนี้สามารถคว่ำ LIFE Card ได้ แม้อยู่ในสถานะสาหัส\nเทิร์นละครั้ง สั่งใช้ ถ้าในสนามฝ่ายเรามี บัลลังก์ตั๊กแตนศตวรรษ ทิ้งการ์ดบนมือ 1 ใบ : เลือก LIFE Card ที่หงายอยู่ของเรา 1 ใบ สั่งใช้ผลความสามารถนั้น จนจบเทิร์น หากความสามารถนั้นระบุว่า \"ใน Main Phase ถัดไป\" ให้ทำความสามารถในเทิร์นนี้ทันที",
    cost: 5,
    gem: 0,
    power: 4,
    symbol: "แมลง",
    color: "เขียว",
  },
  {
    name: "ตั๊กแตนหยาง",
    type: "Avatar",
    soi: 2,
    print: "BT07-037",
    rare: "UR",
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี \"ตั๊กแตนหยิน\" Avatar ใบนี้ จะเพิ่ม POWER ตามจำนวน LIFE Card ของเราที่หงายอยู่ ใบละ 1 หากเราอยู่ในสถานะสาหัส Avatar นี้ได้รับ ลูกฮึด และ โล่มนุษย์\nต่อเนื่อง Avatar ใบนี้สามารถสวมใส่การ์ดได้เฉพาะการ์ดที่เป็น Symbol แมลง",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "แมลง",
    color: "เขียว",
  },
  {
    name: "ตั๊กแตนหยาง",
    type: "Avatar",
    soi: 2,
    print: "BT07-037",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี \"ตั๊กแตนหยิน\" Avatar ใบนี้ จะเพิ่ม POWER ตามจำนวน LIFE Card ของเราที่หงายอยู่ ใบละ 1 หากเราอยู่ในสถานะสาหัส Avatar นี้ได้รับ ลูกฮึด และ โล่มนุษย์\nต่อเนื่อง Avatar ใบนี้สามารถสวมใส่การ์ดได้เฉพาะการ์ดที่เป็น Symbol แมลง",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "แมลง",
    color: "เขียว",
  },
  {
    name: "วาฬทมิฬ ก้า",
    type: "Avatar",
    soi: 2,
    print: "BT07-038",
    rare: "C",
    mainEffect: "จุติ ถ้าเราควบคุม Avatar \"ตั๊กแตน\" อยู่ และ LIFE Card เรา หงาย 2 ใบ หรือ มากกว่า : นำการ์ด \"ตั๊กแตน\" 1 ใบ จากนรกเรา ขึ้นมือ",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "ปลา",
    color: "เขียว",
  },
  {
    name: "ตั๊กแตนหญิง",
    type: "Avatar",
    soi: 2,
    print: "BT07-039",
    rare: "R",
    mainEffect: "จุติ หงาย LIFE Card ใบบนสุดของเรา 1 ใบ : นำ การ์ด \"ตั๊กแตน\" 1 ใบ จาก Deck เรา ขึ้นมือ จากนั้นสับ Deck",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "แมลง",
    color: "เขียว",
  },
  {
    name: "ตั๊กแตนหญิง",
    type: "Avatar",
    soi: 2,
    print: "BT07-039",
    rare: "SCR",
    mainEffect: "จุติ หงาย LIFE Card ใบบนสุดของเรา 1 ใบ : นำ การ์ด \"ตั๊กแตน\" 1 ใบ จาก Deck เรา ขึ้นมือ จากนั้นสับ Deck",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "แมลง",
    color: "เขียว",
  },
  {
    name: "หมอเลิฟ ฟันเหยิน",
    type: "Avatar",
    soi: 2,
    print: "BT07-040",
    rare: "R",
    mainEffect: "จุติ : นำการ์ดประเภทใดก็ได้ 1 ใบ จาก Deck เรา แสดงให้ฝ่ายตรงข้ามดู จากนั้นส่งลงนรก การ์ดใบนั้นไม่สามารถถูกนำออกจากนรกได้ทุกกรณี เมื่อถึง Draw Phase ที่ 2 ของเรา หลังจากที่ความสามารถนี้ทำงาน นำการ์ดใบนั้นขึ้นมือ",
    cost: 4,
    gem: 4,
    power: 3,
    symbol: "คน",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "คาบู ช่วยด้วย",
    type: "Avatar",
    soi: 2,
    print: "BT07-041",
    rare: "C",
    mainEffect: "อัตโนมัติ สั่งใช้ จากบนมือ เมื่อ Avatar {symbol สัตว์} 1 ใบ บน Avatar Zone ฝ่ายเราจะถูกทำลาย ทิ้งการ์ด 1 ใบ : อัญเชิญการ์ดใบนี้จากบนมือ และ ยกเลิกการทำลายนั้น",
    cost: 5,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "บัวนิด วานรแห่งสวนสัตว์",
    type: "Avatar",
    soi: 2,
    print: "BT07-042",
    rare: "C",
    mainEffect: "ต่อเนื่อง Avatar ใบนี้สามารถโจมตีได้ต่อเมื่อเราควบคุม Avatar \"วานร\" ใบอื่นอยู่บน Avatar Zone ฝ่ายเราเท่านั้น",
    cost: 3,
    gem: 2,
    power: 5,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "แมรี่ พนักงานต้อนรับ",
    type: "Avatar",
    soi: 2,
    print: "BT07-043",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ในช่วง End Phase : ทอยลูกเต๋า 1 ครั้ง สอดแนม ตามจำนวน ผลลัพธ์ ที่ได้ สามารถนำ Avatar 1 ใบ จากที่สอดแนมขึ้นมือ นำการ์ดที่เหลือเรียง และ นำไว้ใต้สุดของ Deck",
    cost: 4,
    gem: 0,
    power: 2,
    symbol: "ต่างชาติ",
    color: "เขียว",
  },
  {
    name: "หุ่นสนับสนุนผู้กล้า Dเพรส",
    type: "Avatar",
    soi: 2,
    print: "BT07-044",
    rare: "R",
    mainEffect: "",
    cost: 2,
    gem: 1,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "ข้ารับใช้มนุษย์ดาว R18",
    type: "Avatar",
    soi: 2,
    print: "BT07-045",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "ผีเสื้อของเดซี่",
    type: "Avatar",
    soi: 2,
    print: "BT07-046",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "สัตว์มหัศจรรย์",
  },
  {
    name: "เจ้าของร้านปลาทูน่า",
    type: "Avatar",
    soi: 2,
    print: "BT07-047",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "หยุด!! นี่ตำรวจ",
    type: "Magic",
    soi: 2,
    print: "BT07-048",
    rare: "R",
    mainEffect:
      "สามารถใช้การ์ดใบนี้ได้เมื่อเราควบคุม Avatar \"ตำรวจ\" เท่านั้น\nแสดงการ์ด \"ตำรวจ\" บนมือของเรา 1 ใบ ให้ฝ่ายตรงข้ามดู จากนั้นนำ Avatar บน Avatar Zone ของฝ่ายตรงข้าม 1 ใบ ไปไว้ที่บนสุดของ Deck ฝ่ายตรงข้าม",
    subtype: "Normal",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "เพ้อเจ้อ",
    type: "Magic",
    soi: 2,
    print: "BT07-049",
    rare: "R",
    mainEffect:
      "เลือก Avatar 1 ใบ บนสนาม : ปรับ POWER ของ Avatar ใบนั้น ให้กลับเป็น POWER ตั้งต้น\nหากบน Avatar Zone ฝ่ายเรามี \"ตำรวจ\" การ์ดใบนี้สามารถใช้ในเทิร์นฝ่ายตรงข้ามได้ โดยถือว่าเป็นการใช้ React Magic",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ราคาชาติที่คุณขาย",
    type: "Magic",
    soi: 2,
    print: "BT07-050",
    rare: "C",
    mainEffect: "ส่ง \"ทหารหิมะ\" 2 ใบ จาก Deck เรา ลงนรก จากนั้นสับ Deck หากในนรกเรา มี Avatar \"หิมะ\" ตั้งแต่ 10 ใบขึ้นไป จั่วการ์ด 1 ใบ",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "คาถา ปลดอาวุสสิวะ",
    type: "Magic",
    soi: 2,
    print: "BT07-051",
    rare: "R",
    mainEffect: "สามารถใช้ได้เมื่อมี Avatar \"จอมเวท\" อยู่บน Avatar Zone ฝ่ายเรา เท่านั้น เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ : Avatar ใบที่เลือก POWER -3 ถ้า Avatar ใบนั้น POWER เหลือ 0 ทำลาย Avatar ใบนั้น",
    subtype: "Normal",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "คาถา สัตตูหลีกปาย",
    type: "Magic",
    soi: 2,
    print: "BT07-052",
    rare: "SR",
    mainEffect: "สามารถใช้ได้เมื่อมี Avatar \"จอมเวท\" อยู่บน Avatar Zone ฝ่ายเรา ตั้งแต่ 2 ใบขึ้นไป เท่านั้น  เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ ที่มี POWER 5 หรือมากกว่า  : นำ Avatar ใบที่เลือก ส่งไปยัง Magic Zone ของฝ่ายตรงข้าม",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "คาถา สัตตูหลีกปาย",
    type: "Magic",
    soi: 2,
    print: "BT07-052",
    rare: "SCR",
    mainEffect: "สามารถใช้ได้เมื่อมี Avatar \"จอมเวท\" อยู่บน Avatar Zone ฝ่ายเรา ตั้งแต่ 2 ใบขึ้นไป เท่านั้น  เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ ที่มี POWER 5 หรือมากกว่า  : นำ Avatar ใบที่เลือก ส่งไปยัง Magic Zone ของฝ่ายตรงข้าม",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ชะตาไม่มีวันจบลง",
    type: "Magic",
    soi: 2,
    print: "BT07-053",
    rare: "SR",
    mainEffect: "สามารถใช้การ์ดนี้ได้เมื่อ อยู่ในสถานะ สาหัส เท่านั้น : อัญเชิญ \"ตั๊กแตนหยิน\" หรือ \"ตั๊กแตนหยาง\" 1 ใบ จากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    subtype: "Normal",
    cost: 4,
    symbol: "จอมเวทย์",
  },
  {
    name: "พลังแห่งควางสิริมงคง",
    type: "Magic",
    soi: 2,
    print: "BT07-054",
    rare: "UR",
    mainEffect: "ใช้ได้เมื่อบน Avatar Zone ฝ่ายเรามี \"เสาซินแสมงคล\" เท่านั้น ทิ้งการ์ดบนมือ 7 ใบ : นำ Avatar \"เสามงคล\" 1 ใบ จากนรก มาไว้ที่ Magic Zone ฝ่ายเรา",
    subtype: "Normal",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "พลังแห่งควางสิริมงคง",
    type: "Magic",
    soi: 2,
    print: "BT07-054",
    rare: "SCR",
    mainEffect: "ใช้ได้เมื่อบน Avatar Zone ฝ่ายเรามี \"เสาซินแสมงคล\" เท่านั้น ทิ้งการ์ดบนมือ 7 ใบ : นำ Avatar \"เสามงคล\" 1 ใบ จากนรก มาไว้ที่ Magic Zone ฝ่ายเรา",
    subtype: "Normal",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "เปลี่ยนเมน",
    type: "Magic",
    soi: 2,
    print: "BT07-055",
    rare: "C",
    mainEffect: "เลือก Avatar \"ไอดอล\" 1 ใบ บน Avatar Zone ฝ่ายเรา ที่มีการ์ด \"โอตะ\"  สวมใส่อยู่ : นำ Avatar ใบนั้น กลับเข้า Deck อัญเชิญ Avatar \"ไอดอล\" 1 ใบ จาก Deck เรา ที่คนละชื่อกับ Avatar ที่เลือก และนำการ์ด \"โอตะ\" ที่สวมใส่อยู่ทั้งหมด ของ Avatar ที่เลือก ไปสวมใส่ให้ Avatar ที่ถูกอัญเชิญมาด้วยความสามารถนี้แทน จากนั้นสับ Deck",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "กลับบ้านเก่า",
    type: "Magic",
    soi: 2,
    print: "BT07-056",
    rare: "C",
    mainEffect: "ทำลาย Avatar ทุกใบ บน Avatar Zone ที่ถูกอัญเชิญมาจากนรก",
    subtype: "Normal",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "ลิสต์แผนการ",
    type: "Magic",
    soi: 2,
    print: "BT07-057",
    rare: "C",
    mainEffect: "นำการ์ด Magic \"แผนการ\" ที่ไม่ได้ชื่อ ลิสต์แผนการ 1 ใบ จาก Deck เรา ขึ้นมือ จากนั้น สับ Deck",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "แบงค์ Portal",
    type: "Magic",
    soi: 2,
    print: "BT07-058",
    rare: "C",
    mainEffect:
      "ใช้ได้เมื่อบน Avatar Zone ฝ่ายเรา มี \"แบงค์\" อยู่เท่านั้น\nสอดแนม 5 ใบ เลือก Avatar \"แบงค์\" 2 ใบ จากที่ สอดแนม 1 ใบลง นรก อีก 1 ใบ นำขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ",
    subtype: "Normal",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "พันปักษา",
    type: "Magic",
    soi: 2,
    print: "BT07-059",
    rare: "SR",
    mainEffect:
      "เมื่อฝ่ายตรงข้ามประกาศโจมตี เลือก Avatar \"ครุฑ\" บน Avatar Zone ฝ่ายเรา 1 ใบ ทำลาย Avatar ใบนั้น : \nทำลาย Avatar บน Avatar Zone ฝ่ายตรงข้ามสูงสุด 2 ใบ",
    subtype: "React",
    cost: 0,
    symbol: "สัตว์มหัศจรรย์",
  },
  {
    name: "พันปักษา",
    type: "Magic",
    soi: 2,
    print: "BT07-059",
    rare: "SCR",
    mainEffect:
      "เมื่อฝ่ายตรงข้ามประกาศโจมตี เลือก Avatar \"ครุฑ\" บน Avatar Zone ฝ่ายเรา 1 ใบ ทำลาย Avatar ใบนั้น : \nทำลาย Avatar บน Avatar Zone ฝ่ายตรงข้ามสูงสุด 2 ใบ",
    subtype: "React",
    cost: 0,
    symbol: "สัตว์มหัศจรรย์",
  },
  {
    name: "คาถา สตอปปุ",
    type: "Magic",
    soi: 2,
    print: "BT07-060",
    rare: "C",
    mainEffect: "สามารถใช้ได้เมื่อมี Avatar \"จอมเวท\" อยู่บน Avatar Zone ฝ่ายเรา เท่านั้น เมื่อ Avatar \"จอมเวทย์\" ตกเป็นเป้าหมายการโจมตี นำ \"คาถา\" จากในนรก 1 ใบ กลับเข้าใต้ Deck เรา : ยกเลิกการโจมตีนั้น",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ขอจบรายการแต่เพียงเท่านี้",
    type: "Magic",
    soi: 2,
    print: "BT07-061",
    rare: "C",
    mainEffect: "เมื่อ Avatar \"พี่หน่วง\" จะถูกทำลาย นำ \"ยานรายการ เถียงทันหน่วง\" จาก Construct Zone ฝ่ายเรา ลงนรก : นำ Avatar \"พี่หน่วง\" ขึ้นมือแทนการถูกทำลาย",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ขนมณี แฟลร์",
    type: "Magic",
    soi: 2,
    print: "BT07-062",
    rare: "C",
    mainEffect:
      "สวมใส่ได้แค่ Avatar \"ครุฑ\" ที่เป็น Symbol สัตว์มหัศจรรย์ เท่านั้น \nเมื่อ Avatar ที่สวมใส่จะถูกนำออกจากสนามด้วยความสามารถของการ์ด สามารถส่งการ์ดใบนี้ในสภาพสวมใส่ลงนรก : Avatar ที่เคยสวมใส่การ์ดใบนี้จะไม่ถูกนำออกจากสนาม",
    subtype: "Modification",
    cost: 2,
    symbol: "สัตว์มหัศจรรย์",
  },
  {
    name: "ไม้กายสิทธิ์",
    type: "Magic",
    soi: 2,
    print: "BT07-063",
    rare: "C",
    mainEffect:
      "สวมใส่ได้แค่ Avatar \"จอมเวท\" เท่านั้น \nเมื่อมีการใช้ Magic Card \"คาถา\" Avatar ที่สวมใส่การ์ดใบนี้ POWER +1",
    subtype: "Modification",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "เก้าอี้ เฟิร์สคลาส",
    type: "Magic",
    soi: 2,
    print: "BT07-064",
    rare: "C",
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ ได้รับชื่อ \"Super Air",
    subtype: "Modification",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "ปลอกคอซื่อสัตย์",
    type: "Magic",
    soi: 2,
    print: "BT07-065",
    rare: "C",
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้จะไม่ถูกเปลี่ยนการควบคุม",
    subtype: "Modification",
    cost: 4,
    symbol: "จอมเวทย์",
  },
  {
    name: "อาคารผู้โดยสารชั้นต่ำ",
    type: "Magic",
    soi: 2,
    print: "BT07-066",
    rare: "SR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ถ้าเรามี \"เครื่องบิน Super Air\" อยู่บน Avatar Zone ฝ่ายเรา ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ \"ผู้โดยสาร Super Air\" 1 ใบ จากนรกหรือ Deck เรา ลงบน Avatar Zone ฝ่ายเรา ถ้านำจาก Deck ให้สับ Deck",
    subtype: "Land",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "หมู่บ้านเห็ด",
    type: "Magic",
    soi: 2,
    print: "BT07-067",
    rare: "C",
    mainEffect: "Avatar ทุกใบ ลด POWER ลงครึ่งหนึ่ง หากหารแล้วมีเศษให้ปัดลง",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "หมู่บ้านเห็ด",
    type: "Magic",
    soi: 2,
    print: "BT07-067",
    rare: "SCR",
    mainEffect: "Avatar ทุกใบ ลด POWER ลงครึ่งหนึ่ง หากหารแล้วมีเศษให้ปัดลง",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ดินแดนหิมะสีเทา",
    type: "Magic",
    soi: 2,
    print: "BT07-068",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เลือก Avatar \"หิมะ\" ที่เป็น Symbol ชาวต่างชาติ 1 ใบ : Avatar ใบที่เลือก POWER +1 ต่อจำนวน \"ทหารหิมะ\" ทุกๆ 2 ใบ ในนรกฝ่ายเรา จนจบเทิร์น",
    subtype: "Land",
    cost: 2,
    symbol: "ต่างชาติ",
  },
  {
    name: "สถานีตำรวจ",
    type: "Magic",
    soi: 2,
    print: "BT07-069",
    rare: "R",
    mainEffect:
      "Avatar \"ตำรวจ\" ได้รับความสามารถ ตาม Symbol ของ Avatar ใบนั้น\nAvatar {symbol คน} POWER +2\nAvatar {symbol หุ่นยนต์} ได้รับ สามัคคี\nAvatar {symbol ผี} ได้รับ โล่มนุษย์",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "งานเลี้ยงโดนใจ หัวใจโดนเธอ",
    type: "Magic",
    soi: 2,
    print: "BT07-070",
    rare: "UR",
    mainEffect: "Avatar ที่มีโดนใจ POWER +1",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "เสาธง",
    type: "Construct",
    soi: 2,
    print: "BT07-071",
    rare: "C",
    mainEffect: "ต่อเนื่อง Avatar ทุกใบบน Avatar Zone ฝ่ายเราได้รับ ลูกฮึด",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "สิ่งก่อสร้าง",
    color: "แดง",
  },
  {
    name: "ยานรายการ เถียงทันหน่วง",
    type: "Construct",
    soi: 2,
    print: "BT07-072",
    rare: "SR",
    mainEffect:
      "ถ้าเรามี \"พี่หน่วง\" อยู่บน Avatar Zone ฝ่ายเรา Cost ของการ์ดใบนี้จะเท่ากับ 0 \nต่อเนื่อง ถ้าเรามี \"พี่หน่วง\" อยู่บน Avatar Zone ฝ่ายเรา และ ใน Magic Zone ฝ่ายเรา มี Avatar ของฝ่ายตรงข้ามอยู่ : ในช่วง End Phase เรา จั่วการ์ด 1 ใบ\nเทิร์นละครั้ง สั่งใช้ เลือก Avatar 1 ใบ บน Avatar Zone : Avatar ใบที่เลือก ได้รับ โล่มนุษย์ จนจบเทิร์นถัดไป ของฝ่ายตรงข้าม",
    cost: 3,
    gem: 4,
    power: 2,
    symbol: "หุ่นยนต์",
    color: "ม่วง",
  },
  {
    name: "ยานรายการ เถียงทันหน่วง",
    type: "Construct",
    soi: 2,
    print: "BT07-072",
    rare: "SCR",
    mainEffect:
      "ถ้าเรามี \"พี่หน่วง\" อยู่บน Avatar Zone ฝ่ายเรา Cost ของการ์ดใบนี้จะเท่ากับ 0 \nต่อเนื่อง ถ้าเรามี \"พี่หน่วง\" อยู่บน Avatar Zone ฝ่ายเรา และ ใน Magic Zone ฝ่ายเรา มี Avatar ของฝ่ายตรงข้ามอยู่ : ในช่วง End Phase เรา จั่วการ์ด 1 ใบ\nเทิร์นละครั้ง สั่งใช้ เลือก Avatar 1 ใบ บน Avatar Zone : Avatar ใบที่เลือก ได้รับ โล่มนุษย์ จนจบเทิร์นถัดไป ของฝ่ายตรงข้าม",
    cost: 3,
    gem: 4,
    power: 2,
    symbol: "หุ่นยนต์",
  },
  {
    name: "บัลลังก์ตั๊กแตนศตวรรษ",
    type: "Construct",
    soi: 2,
    print: "BT07-073",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : นำการ์ดใบนี้ ไปสวมใส่ ให้ Avatar \"ตั๊กแตน\" หรือ Avatar ที่มี \"ตั๊กแตน\" ใน Text Box 1 ใบ\nAvatar ที่สวมใส่การ์ดใบนี้ POWER +2 และ ไม่สามารถโจมตีได้ และ ได้รับ \"Avatar \"ตั๊กแตน\" หรือ Avatar ที่มี \"ตั๊กแตน\" ใน Text Box ใบอื่น ใน Avatar Zone ฝ่ายเรา POWER +1\"",
    cost: 2,
    gem: 4,
    power: 2,
    symbol: "แมลง",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "ไม่นะ มณโท !",
    type: "Life",
    soi: 2,
    print: "BT07-074",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป อัญเชิญ Avatar 1 ใบ จากนรก ที่มี Cost ไม่เกิน 2 ลงบน Avatar Zone ฝ่ายเรา",
    favorText: "",
  },
  {
    name: "ไม่นะ พี่หน่วง !",
    type: "Life",
    soi: 2,
    print: "BT07-075",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "",
  },
];
