import { Card } from "@/src/types/cards";

export const CARDS_BT08: Card[] = [
  {
    name: "หุ่นนักรบผู้กล้าปีศาจ : อีวิลไมเกรน",
    type: "Avatar",
    soi: 2,
    print: "BT08-001",
    rare: "UR",
    mainEffect:
      "จุติ ธรณีสูบ 5 ใบ : นำ \"อาวุธหุ่นนักรบผู้กล้า\" จากในนรกเรา 1 ใบ ขึ้นมือ \nเทิร์นละครั้ง สั่งใช้ เมื่อมีการใช้ Modification Magic \"อาวุธหุ่นนักรบผู้กล้า\" : สอดแนม Deck ฝ่ายตรงข้าม 1 ใบ ถ้าเป็น Magic Card ส่งลงนรก แต่ถ้าไม่ใช่ ให้นำไว้ใต้ Deck",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "หุ่นนักรบผู้กล้าปีศาจ : อีวิลไมเกรน",
    type: "Avatar",
    soi: 2,
    print: "BT08-001",
    rare: "SCR",
    mainEffect:
      "จุติ ธรณีสูบ 5 ใบ : นำ \"อาวุธหุ่นนักรบผู้กล้า\" จากในนรกเรา 1 ใบ ขึ้นมือ \nเทิร์นละครั้ง สั่งใช้ เมื่อมีการใช้ Modification Magic \"อาวุธหุ่นนักรบผู้กล้า\" : สอดแนม Deck ฝ่ายตรงข้าม 1 ใบ ถ้าเป็น Magic Card ส่งลงนรก แต่ถ้าไม่ใช่ ให้นำไว้ใต้ Deck",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "แดง",
  },
  {
    name: "ไอ้ชิด อโยธยา Express",
    type: "Avatar",
    soi: 2,
    print: "BT08-002",
    rare: "R",
    mainEffect: "ต่อเนื่อง ค่า Cost ในการทิ้งมือเพื่อใช้ความสามารถของการ์ดที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ของฝ่ายเราจะหายไป",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "เณรคู ศิษย์เอกพระอาจารย์",
    type: "Avatar",
    soi: 2,
    print: "BT08-003",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ถ้าบน Construct Zone ฝ่ายเรามี \"ค่ายบางระจัน\" ทิ้งการ์ดบนมือ 1 ใบ :  Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ทุกใบใน Avatar Zone ฝ่ายเรา จะไม่รับผล React Magic Card ของฝ่ายตรงข้าม จนจบเทิร์น",
    cost: 1,
    gem: 4,
    power: 0,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "น้าเอี๊ยด นักบรรเลง",
    type: "Avatar",
    soi: 2,
    print: "BT08-004",
    rare: "SR",
    mainEffect:
      "ต่อเนื่อง Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ใบอื่นบน Avatar Zone ฝ่ายเรา POWER+1 และ  Construct \"ค่ายบางระจัน\" บน Construct Zone ฝ่ายเรา POWER+2\nต่อเนื่อง Modification Magic ฝ่ายเรา ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ทุกใบได้รับ \"Avatar ที่สวมใส่การ์ดใบนี้ POWER+1",
    cost: 4,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "ซุนกวน ผู้นำพยัคฆ์แห่งง่อก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-005",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้  นำ Avatar \"ง่อก๊ก\" หรือ \"พลเดินทัพ\" ในนรกเรา 2 ใบ กลับใต้ Deck : ทำลาย การ์ดบนสนาม 1 ใบ\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 4,
    gem: 2,
    power: 6,
    symbol: "ต่างชาติ",
    color: "แดง",
    ex: "Only #1",
  },
  {
    name: "ซุนกวน ผู้นำพยัคฆ์แห่งง่อก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-005",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้  นำ Avatar \"ง่อก๊ก\" หรือ \"พลเดินทัพ\" ในนรกเรา 2 ใบ กลับใต้ Deck : ทำลาย การ์ดบนสนาม 1 ใบ\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 4,
    gem: 2,
    power: 6,
    symbol: "ต่างชาติ",
    color: "แดง",
    ex: "Only #1",
  },
  {
    name: "จิวยี่ กุนซือสำอางแห่งง่อก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-006",
    rare: "R",
    mainEffect:
      "จุติ : สอดแนม 5 ใบ สามารถ เลือก Construct \"เรือรบโบราณ\" 1 ใบ จากที่ สอดแนม และทำการก่อสร้าง ลงบน Constrct Zone ฝ่ายเรา การ์ดที่เหลือเรียงและนำไว้ใต้ Deck\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "จิวท่าย ขุนพลคนเหล็กแห่งง่อก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-007",
    rare: "C",
    mainEffect: "สั่งใช้ จากบนมือ เมื่อ Avatar \"ขุนพล\" สีแดง ที่เป็น Symbol ชาวต่างชาติ บน Avatar Zone ฝ่ายเรา จะออกจากสนามโดยความสามารถของการ์ด ทิ้งการ์ดใบนี้ : Avatar ใบนั้นจะไม่ถูกนำออกจากสนาม หาก Avatar ใบนั้นคือ ซุนกวน ผู้นำพยัคฆ์แห่งง่อก๊ก จั่วการ์ด 1 ใบ",
    cost: 3,
    gem: 4,
    power: 3,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "กาลาฮัด อัศวินโต๊ะกลมแห่งความกล้าหาญ",
    type: "Avatar",
    soi: 2,
    print: "BT08-008",
    rare: "C",
    mainEffect:
      "ตราบเท่าที่ Magic Zone ฝ่ายเรา มี Modification \"ดาบศักดิ์สิทธิ์\" 2 ใบหรือมากกว่า Cost ของการ์ดใบนี้จะเท่ากับ 4\nต่อเนื่อง POWER +1 ตามจำนวน Modification \"ดาบศักดิ์สิทธิ์\" ที่ชื่อไม่ซ้ำกัน ใน Magic Zone ฝ่ายเรา",
    cost: 6,
    gem: 2,
    power: 3,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "เอเจ้นท์สมูท",
    type: "Avatar",
    soi: 2,
    print: "BT08-009",
    rare: "C",
    mainEffect:
      "คำสั่งเสีย : สอดแนม 3 ใบ นำ เอเจ้นท์สมูท 1 ใบ จากที่สอดแนม ขึ้นมือ การ์ดที่เหลือเรียงแล้วนำไว้ใต้ Deck \nต่อเนื่อง ใน Battle Phase ฝ่ายเรา Avatar ใบนี้ จะมี POWER เท่ากับ 1 ต่อจำนวน เอเจ้นท์สมูท ทุกๆ 2 ใบ ในนรกเรา \n#การ์ดใบนี้ สามารถใส่ใน Deck จำนวนได้มากสุด 50 ใบ",
    cost: 3,
    gem: 2,
    power: 0,
    symbol: "เอเลี่ยน",
    color: "แดง",
    customLimit: 50,
  },
  {
    name: "เซอร์นัท ดาบแห่งแสงอรุณ",
    type: "Avatar",
    soi: 2,
    print: "BT08-010",
    rare: "UR",
    mainEffect:
      "จุติ : นำ \"ไอ้นัท\" 1 ใบ จากนรกเรามาสวมใส่การ์ดใบนี้\nอัตโนมัติ เมื่อ Avatar ใบนี้ ต่อสู้กับ Avatar สีม่วง : POWER +3 จนจบการต่อสู้นั้น\nต่อเนื่อง Avatar เลอติ๊ก เด็กไม่ชอบแดรคคูลา ทุกใบบน Avatar Zone ฝ่ายเรา POWER +2 และ ถ้า Avatar ใบนี้สวมใส่ \"ไอ้นัท\" อยู่ จะได้รับ ความสามารถของการ์ด \"ไอ้นัท\" ที่สวมใส่อยู่ด้วย",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "เซอร์นัท ดาบแห่งแสงอรุณ",
    type: "Avatar",
    soi: 2,
    print: "BT08-010",
    rare: "SCR",
    mainEffect:
      "จุติ : นำ \"ไอ้นัท\" 1 ใบ จากนรกเรามาสวมใส่การ์ดใบนี้\nอัตโนมัติ เมื่อ Avatar ใบนี้ ต่อสู้กับ Avatar สีม่วง : POWER +3 จนจบการต่อสู้นั้น\nต่อเนื่อง Avatar เลอติ๊ก เด็กไม่ชอบแดรคคูลา ทุกใบบน Avatar Zone ฝ่ายเรา POWER +2 และ ถ้า Avatar ใบนี้สวมใส่ \"ไอ้นัท\" อยู่ จะได้รับ ความสามารถของการ์ด \"ไอ้นัท\" ที่สวมใส่อยู่ด้วย",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
  },
  {
    name: "ซาบะริว นักกวาดล้างมือเก๋า",
    type: "Avatar",
    soi: 2,
    print: "BT08-011",
    rare: "R",
    mainEffect:
      "ลูกฮึด  \nถ้า Avatar Zone ฝ่ายตรงข้ามมี เจค นักฆ่ามือเก๋า Cost บนมือของการ์ดใบนี้จะเป็น 0\n#เราสามารถควบคุม ซาบะริว นักกวาดล้างมือเก๋าใน Avatar Zone ได้เพียง 1 ใบเท่านั้น",
    cost: 7,
    gem: 1,
    power: 7,
    symbol: "ต่างชาติ",
    color: "แดง",
  },
  {
    name: "หมอเสริมศักดิ์",
    type: "Avatar",
    soi: 2,
    print: "BT08-012",
    rare: "C",
    mainEffect:
      "จุติ : สอดแนม 5 ใบ นำการ์ด Magic  หมอมาแล้วววว จากที่ สอดแนม 1 ใบ ขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ\nคำสั่งเสีย : เลือก Avatar 1 ใบ ที่ Cost ไม่เกิน 2 หรือ พยาบาล เอ๋ 1 ใบ ในนรกเรา อัญเชิญ Avatar ใบที่เลือก ลง Avatar Zone ฝ่ายเรา",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "คน",
    color: "แดง",
  },
  {
    name: "เปรตรัททาทุย",
    type: "Avatar",
    soi: 2,
    print: "BT08-013",
    rare: "C",
    mainEffect:
      "เมื่อการ์ดใบนี้ถูกอัญเชิญ เซ่นไหว้ รัททาทุย นางพญา หรือ รัททาทุย พ่อพันธุ์ 1 ใบ : อัญเชิญ Avatar Symbol รัททาทุย จากนรก 1 ใบ ที่ไม่ใช่ รัททาทุย นางพญา หรือ รัททาทุย พ่อพันธุ์ ลงบน Avatar Zone ฝ่ายเรา\nต่อเนื่อง Avatar ใบนี้ POWER +1 ตามจำนวน LIFE Card ของเราที่หงายอยู่",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "รัททาทุย",
    color: "ฟ้า",
  },
  {
    name: "ริกกี้ ฆาตกรถลกหนัง",
    type: "Avatar",
    soi: 2,
    print: "BT08-014",
    rare: "SR",
    mainEffect: "สั่งใช้ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ส่ง Avatar ใบนี้ลงนรก อัญเชิญ จุติ Avatar \"ริกกี้\" ที่เป็น Symbol แมลง และชื่อไม่ซ้ำกับการ์ดใบนี้ 1 ใบ จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "แมลง",
    color: "ฟ้า",
  },
  {
    name: "ริกกี้ ฆาตกรถลกหนัง",
    type: "Avatar",
    soi: 2,
    print: "BT08-014",
    rare: "SCR",
    mainEffect: "สั่งใช้ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ส่ง Avatar ใบนี้ลงนรก อัญเชิญ จุติ Avatar \"ริกกี้\" ที่เป็น Symbol แมลง และชื่อไม่ซ้ำกับการ์ดใบนี้ 1 ใบ จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "แมลง",
  },
  {
    name: "ริกกี้ เชฟมัมมามิย่า",
    type: "Avatar",
    soi: 2,
    print: "BT08-015",
    rare: "C",
    mainEffect: "จุติ : เลือก Avatar บน Avatar Zone ฝ่ายตรงข้าม 1 ใบ Avatar ใบที่เลือก POWER -2",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "แมลง",
    color: "ฟ้า",
  },
  {
    name: "ริกกี้ คุณหมอ",
    type: "Avatar",
    soi: 2,
    print: "BT08-016",
    rare: "C",
    mainEffect: "สั่งใช้ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : สามารถนำ การ์ด Magic \"หนังมนุษย์ ชุดแก้แค้น\" จากใน Deck เรา 1 ใบ ขึ้นมือ จากนั้นสับ Deck",
    cost: 5,
    gem: 0,
    power: 5,
    symbol: "แมลง",
    color: "ฟ้า",
  },
  {
    name: "มอเดรด อัศวินโต๊ะกลมแห่งการทรยศ",
    type: "Avatar",
    soi: 2,
    print: "BT08-017",
    rare: "SR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เมื่อมีการนำ Modification \"ดาบศักดิ์สิทธิ์\" มาสวมใส่ Avatar ใบนี้  : เซ่นไหว้ Avatar ใบอื่นบน Avatar Zone ฝ่ายเรา 1 ใบ อัญเชิญ จุติ Avatar \"อัศวินโต๊ะกลม\" สีฟ้า 1 ใบ จากในนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 0,
    power: 3,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "มอเดรด อัศวินโต๊ะกลมแห่งการทรยศ",
    type: "Avatar",
    soi: 2,
    print: "BT08-017",
    rare: "SCR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เมื่อมีการนำ Modification \"ดาบศักดิ์สิทธิ์\" มาสวมใส่ Avatar ใบนี้  : เซ่นไหว้ Avatar ใบอื่นบน Avatar Zone ฝ่ายเรา 1 ใบ อัญเชิญ จุติ Avatar \"อัศวินโต๊ะกลม\" สีฟ้า 1 ใบ จากในนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 0,
    power: 3,
    symbol: "ต่างชาติ",
  },
  {
    name: "โจโฉ ผู้นำเบ็ดเสร็จแห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-018",
    rare: "UR",
    mainEffect:
      "จุติ : อัญเชิญ จุติ Avatar \"ขุนพล\" สีฟ้า ที่เป็น Symbol ชาวต่างชาติ 1 ใบ จากมือเรา\nสั่งใช้ เมื่อ Avatar ฝ่ายตรงข้ามโจมตี Avatar \"ขุนพล\" สีฟ้า ที่เป็น Symbol ชาวต่างชาติ ฝ่ายเรา : หงาย LIFE Card ใบบนสุดของเรา 1 ใบ และยกเลิกการโจมตีนั้น\nอัตโนมัติ เทิร์นละครั้ง เมื่อ LIFE Card เราถูกหงาย : สอดแนม ตามจำนวน LIFE Card ฝ่ายเราที่หงายอยู่ ใบละ 1 อัญเชิญ Avatar \"วุยก๊ก\" 1 ใบ จากที่สอดแนม ลง Avatar Zone ฝ่ายเรา การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
    ex: "Only #1",
  },
  {
    name: "โจโฉ ผู้นำเบ็ดเสร็จแห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-018",
    rare: "SCR",
    mainEffect:
      "จุติ : อัญเชิญ จุติ Avatar \"ขุนพล\" สีฟ้า ที่เป็น Symbol ชาวต่างชาติ 1 ใบ จากมือเรา\nสั่งใช้ เมื่อ Avatar ฝ่ายตรงข้ามโจมตี Avatar \"ขุนพล\" สีฟ้า ที่เป็น Symbol ชาวต่างชาติ ฝ่ายเรา : หงาย LIFE Card ใบบนสุดของเรา 1 ใบ และยกเลิกการโจมตีนั้น\nอัตโนมัติ เทิร์นละครั้ง เมื่อ LIFE Card เราถูกหงาย : สอดแนม ตามจำนวน LIFE Card ฝ่ายเราที่หงายอยู่ ใบละ 1 อัญเชิญ Avatar \"วุยก๊ก\" 1 ใบ จากที่สอดแนม ลง Avatar Zone ฝ่ายเรา การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "ต่างชาติ",
    ex: "Only #1",
  },
  {
    name: "สุมาอี้ กุนซือเจ้าเล่ห์แห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-019",
    rare: "SR",
    mainEffect:
      "แทงหลัง\nต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี โจโฉ ผู้นำเบ็ดเสร็จแห่งวุยก๊ก โดยที่ Avatar ใบอื่น ทั้งหมดบน Avatar Zone ฝ่ายเรา เป็น \"ขุนพล\" สีฟ้า ที่เป็น Symbol ชาวต่างชาติ ผู้เล่นฝ่ายตรงข้าม จะต้องสั่ง Avatar โจมตี อย่างน้อย 1 ครั้งเสมอ ถ้าทำได้",
    cost: 4,
    gem: 1,
    power: 1,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "สุมาอี้ กุนซือเจ้าเล่ห์แห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-019",
    rare: "SCR",
    mainEffect:
      "แทงหลัง\nต่อเนื่อง ตราบเท่าที่ Avatar Zone ฝ่ายเรามี โจโฉ ผู้นำเบ็ดเสร็จแห่งวุยก๊ก โดยที่ Avatar ใบอื่น ทั้งหมดบน Avatar Zone ฝ่ายเรา เป็น \"ขุนพล\" สีฟ้า ที่เป็น Symbol ชาวต่างชาติ ผู้เล่นฝ่ายตรงข้าม จะต้องสั่ง Avatar โจมตี อย่างน้อย 1 ครั้งเสมอ ถ้าทำได้",
    cost: 4,
    gem: 1,
    power: 1,
    symbol: "ต่างชาติ",
  },
  {
    name: "เตียวเลี้ยว ขุนพลมือปราบแห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-020",
    rare: "C",
    mainEffect:
      "จุติ : สอดแนม 5 ใบ เลือก Avatar \"ขุนพล\" ที่เป็น Symbol ต่างชาติ ที่มีสีเดียวกันกับ Avatar ใบนี้ 1 ใบ จากที่สอดแนม และนำขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ\n#Avatar ใบนี้ถือว่าเป็น Avatar สีม่วง ด้วย",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "โอตะท๊อปโดเนท",
    type: "Avatar",
    soi: 2,
    print: "BT08-021",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง เลือกปฏิบัติ :\n  1) นำการ์ดใบนี้ที่อยู่ใน Avatar Zone ไปสวมใส่ให้ Avatar ชื่อ\"ไอดอล\" บนสนามฝ่ายเรา \n  2) อัญเชิญการ์ดใบนี้ที่อยู่ในสภาพสวมใส่ไปที่ Avatar Zone \nเมื่อการ์ดนี้ถูกใช้เป็น Cost เพื่อใช้ความสามารถของ เนียจัง ไอดอลอินฟลูเอนเซอร์ จะถือว่าเท่ากับเป็นการ์ด 2 ใบ",
    cost: 0,
    gem: 2,
    power: 0,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "นายพลทหารหิมะ หลินอัน",
    type: "Avatar",
    soi: 2,
    print: "BT08-022",
    rare: "C",
    mainEffect:
      "ถ้าในนรกเรามี \"ทหารหิมะ\" 10 ใบ ขึ้นไป Cost บนมือของการ์ดใบนี้ -2\nต่อเนื่อง ผลจากความสามารถของ Avatar ฝ่ายตรงข้าม ที่ลด POWER และส่งผลต่อ Avatar \"หิมะ\" บน Avatar Zone ฝ่ายเรา จะถูกเปลี่ยนเป็น เพิ่ม POWER แทน",
    cost: 0,
    gem: 2,
    power: 0,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "มฤตยูเทวี",
    type: "Avatar",
    soi: 2,
    print: "BT08-023",
    rare: "SR",
    mainEffect: "จุติ : เลือก Avatar Symbol นรก Cost 5 จำนวน 1 ใบ ในนรกฝ่ายเรา Avatar ใบนี้ได้รับ ความสามารถของการ์ดใบที่เลือก หากการ์ดใบที่เลือกมีความสามารถจุติให้แสดงผลความสามารถทันที",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "นรก",
    color: "ม่วง",
  },
  {
    name: "มฤตยูเทวี",
    type: "Avatar",
    soi: 2,
    print: "BT08-023",
    rare: "SCR",
    mainEffect: "จุติ : เลือก Avatar Symbol นรก Cost 5 จำนวน 1 ใบ ในนรกฝ่ายเรา Avatar ใบนี้ได้รับ ความสามารถของการ์ดใบที่เลือก หากการ์ดใบที่เลือกมีความสามารถจุติให้แสดงผลความสามารถทันที",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "นรก",
  },
  {
    name: "มฤตยูเทวี",
    type: "Avatar",
    soi: 2,
    print: "BT08-023",
    rare: "PR",
    mainEffect: "จุติ : เลือก Avatar Symbol นรก Cost 5 จำนวน 1 ใบ ในนรกฝ่ายเรา Avatar ใบนี้ได้รับ ความสามารถของการ์ดใบที่เลือก หากการ์ดใบที่เลือกมีความสามารถจุติให้แสดงผลความสามารถทันที",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "นรก",
  },
  {
    name: "มฤตยูเทวี",
    type: "Avatar",
    soi: 2,
    print: "BT08-023",
    rare: "CBR",
    mainEffect: "จุติ : เลือก Avatar Symbol นรก Cost 5 จำนวน 1 ใบ ในนรกฝ่ายเรา Avatar ใบนี้ได้รับ ความสามารถของการ์ดใบที่เลือก หากการ์ดใบที่เลือกมีความสามารถจุติให้แสดงผลความสามารถทันที",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "นรก",
  },
  {
    name: "อีสานสลิงเกอร์ ปิ๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-024",
    rare: "C",
    mainEffect:
      "ลูกฮึด\nจุติ ธรณีสูบ 3 ใบ : นำ Land Magic โคกอีสานนูน 1 ใบ จากใน Deck หรือ นรกเรา และนำขึ้นมือ ถ้านำจาก Deck ให้สับ Deck",
    cost: 3,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อีสานสลิงเกอร์ ปิ่น",
    type: "Avatar",
    soi: 2,
    print: "BT08-025",
    rare: "R",
    mainEffect: "สั่งใช้ เมื่อ Avatar ใบนี้โจมตีใน Battle Phase หากบน Land Magic Zone มี โคกอีสานนูน : ธรณีสูบ 3 ใบ จากนั้น ย้ายเป้าหมายการโจมตีของการ์ดใบนี้ไปที่ LIFE Card ของฝ่ายตรงข้ามแทนได้",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อีสานสลิงเกอร์ เปอร์",
    type: "Avatar",
    soi: 2,
    print: "BT08-026",
    rare: "SR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ถ้าบน Land Magic Zone มี โคกอีสานนูน ธรณีสูบ 3 ใบ : Avatar ใบนี้ POWER +2 จนจบเทิร์น \nอัตโนมัติ เมื่อ Avatar ใบนี้ทำลาย Avatar ของฝ่ายตรงข้ามในช่วง Main Phase และบน Land Magic Zone มี โคกอีสานนูน : หงาย LIFE Card ใบบนสุดของ ฝ่ายตรงข้าม",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "อีสานสลิงเกอร์ เปอร์",
    type: "Avatar",
    soi: 2,
    print: "BT08-026",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ถ้าบน Land Magic Zone มี โคกอีสานนูน ธรณีสูบ 3 ใบ : Avatar ใบนี้ POWER +2 จนจบเทิร์น \nอัตโนมัติ เมื่อ Avatar ใบนี้ทำลาย Avatar ของฝ่ายตรงข้ามในช่วง Main Phase และบน Land Magic Zone มี โคกอีสานนูน : หงาย LIFE Card ใบบนสุดของ ฝ่ายตรงข้าม",
    cost: 3,
    gem: 1,
    power: 3,
    symbol: "คน",
  },
  {
    name: "กัฟแดน ผู้อำนวยการจอมเวทย์",
    type: "Avatar",
    soi: 2,
    print: "BT08-027",
    rare: "C",
    mainEffect: "ต่อเนื่อง ตราบเท่าที่บน Land Magic Zone มี โรงเรียนเวทย์มนต์ ฝ่ายตรงข้ามจะไม่สามารถใช้ การ์ด Land Magic ได้",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พี่ไท่ น้องเฟิง นักดาบวายุ",
    type: "Avatar",
    soi: 2,
    print: "BT08-028",
    rare: "R",
    mainEffect:
      "จุติ ทิ้งการ์ดบนมือ 2 ใบ : อัญเชิญ Avatar Cost 1 หรือต่ำกว่า ที่มี Symbol ไม่ซ้ำกันจากใน Deck 3 ใบ ลงมาบน Avatar Zone ฝ่ายเรา จากนั้น สับ Deck\n#ความสามารถของ Avatar พี่ไท่ น้องเฟิง นักดาบวายุ สามารถใช้ได้แค่ 1 ครั้งต่อเกมเท่านั้น และสามารถใช้ได้ในเทิร์นแรกสุดของผู้ใช้เท่านั้น",
    cost: 4,
    gem: 0,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ม่วง",
  },
  {
    name: "เนียจัง ไอดอลอินฟลูเอนเซอร์",
    type: "Avatar",
    soi: 2,
    print: "BT08-029",
    rare: "SR",
    mainEffect:
      "จุติ ถ้า LIFE Card เรา หงายตั้งแต่ 3 ใบขึ้นไป หรือ มี \"มยุราซัง\" บน Avatar Zone ฝ่ายเรา : อัญเชิญ พอดี จุติ Avatar \"ทัตดนัยซัง\" 1 ใบ จาก มือ หรือ Deck เรา ลงบน Avatar Zone ฝ่ายเรา\nเทิร์นละครั้ง สั่งใช้ ทำลายการ์ด \"โอตะ\" ที่สวมใส่อยู่ให้กับการ์ด Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเรา 2 ใบ : เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ เปลี่ยน ชื่อ ของ Avatar ใบนั้นเป็น \"โอตะ\" และ นำมาสวมใส่ให้ Avatar ใบนี้ หากบน Avatar Zone ฝ่ายเรามี \"ทัตดนัยซัง\" สามารถใช้ความสามารถนี้ เทิร์นละ 2 ครั้ง",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "เนียจัง ไอดอลอินฟลูเอนเซอร์",
    type: "Avatar",
    soi: 2,
    print: "BT08-029",
    rare: "SCR",
    mainEffect:
      "จุติ ถ้า LIFE Card เรา หงายตั้งแต่ 3 ใบขึ้นไป หรือ มี \"มยุราซัง\" บน Avatar Zone ฝ่ายเรา : อัญเชิญ พอดี จุติ Avatar \"ทัตดนัยซัง\" 1 ใบ จาก มือ หรือ Deck เรา ลงบน Avatar Zone ฝ่ายเรา\nเทิร์นละครั้ง สั่งใช้ ทำลายการ์ด \"โอตะ\" ที่สวมใส่อยู่ให้กับการ์ด Avatar \"ไอดอล\" บน Avatar Zone ฝ่ายเรา 2 ใบ : เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ เปลี่ยน ชื่อ ของ Avatar ใบนั้นเป็น \"โอตะ\" และ นำมาสวมใส่ให้ Avatar ใบนี้ หากบน Avatar Zone ฝ่ายเรามี \"ทัตดนัยซัง\" สามารถใช้ความสามารถนี้ เทิร์นละ 2 ครั้ง",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "คน",
  },
  {
    name: "เต่า",
    type: "Avatar",
    soi: 2,
    print: "BT08-030",
    rare: "UR",
    mainEffect:
      "จุติ ถ้า LIFE Card Zone เรา มี อ่อ กระต่ายตาย หงายอยู่ ถ้าไม่มี เปิด LIFE Card ที่คว่ำอยู่ทั้งหมดฝ่ายเรา ค้นหา อ่อ กระต่ายตาย และหงาย LIFE Card ใบนั้น การ์ดที่เหลือสับและนำกลับไปคว่ำ : เลือกปฏิบัติ\n1) ทำลาย Avatar ฝ่ายตรงข้าม 1 ใบ ที่มี POWER น้อยกว่า การ์ดใบนี้\n2) นำ Modification Magic เนยถั่ว 1 ใบ จาก Deck มา สวมใส่การ์ดใบนี้ จากนั้น สับ Deck",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "เอเลี่ยน",
    color: "เขียว",
    ex: "โดนใจ",
  },
  {
    name: "เต่า",
    type: "Avatar",
    soi: 2,
    print: "BT08-030",
    rare: "SCR",
    mainEffect:
      "จุติ ถ้า LIFE Card Zone เรา มี อ่อ กระต่ายตาย หงายอยู่ ถ้าไม่มี เปิด LIFE Card ที่คว่ำอยู่ทั้งหมดฝ่ายเรา ค้นหา อ่อ กระต่ายตาย และหงาย LIFE Card ใบนั้น การ์ดที่เหลือสับและนำกลับไปคว่ำ : เลือกปฏิบัติ\n1) ทำลาย Avatar ฝ่ายตรงข้าม 1 ใบ ที่มี POWER น้อยกว่า การ์ดใบนี้\n2) นำ Modification Magic เนยถั่ว 1 ใบ จาก Deck มา สวมใส่การ์ดใบนี้ จากนั้น สับ Deck",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "เอเลี่ยน",
    ex: "โดนใจ",
  },
  {
    name: "พูรินอล Overdose",
    type: "Avatar",
    soi: 2,
    print: "BT08-031",
    rare: "UR",
    mainEffect:
      "ต่อเนื่อง ถ้า LIFE Card ฝ่ายเรา หงายตั้งแต่ 3 ใบหรือมากกว่า Avatar นี้จะเข้าสู่สถานะ Overdose\nต่อเนื่อง ถ้าการ์ดใบนี้อยู่ในสถานะ Overdose : ความสามารถ จุติ และ คำสั่งเสีย ของ Avatar ฝ่ายตรงข้ามจะไม่สามารถทำได้     \nอัตโนมัติ เมื่อ Avatar นี้ทำลาย Avatar ฝ่ายตรงข้ามที่มีความสามารถ จุติ หรือ คำสั่งเสีย : สุ่มคว่ำ LIFE Card ของฝ่ายเราได้ 1 ใบ\n#Avatar ทุกใบในสนามฝ่ายเราจะไม่สามารถใช้ความสามารถได้ยกเว้น Avatar \"Overdose",
    cost: 5,
    gem: 1,
    power: 3,
    symbol: "หุ่นยนต์",
    color: "เขียว",
  },
  {
    name: "พูรินอล Overdose",
    type: "Avatar",
    soi: 2,
    print: "BT08-031",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง ถ้า LIFE Card ฝ่ายเรา หงายตั้งแต่ 3 ใบหรือมากกว่า Avatar นี้จะเข้าสู่สถานะ Overdose\nต่อเนื่อง ถ้าการ์ดใบนี้อยู่ในสถานะ Overdose : ความสามารถ จุติ และ คำสั่งเสีย ของ Avatar ฝ่ายตรงข้ามจะไม่สามารถทำได้     \nอัตโนมัติ เมื่อ Avatar นี้ทำลาย Avatar ฝ่ายตรงข้ามที่มีความสามารถ จุติ หรือ คำสั่งเสีย : สุ่มคว่ำ LIFE Card ของฝ่ายเราได้ 1 ใบ\n#Avatar ทุกใบในสนามฝ่ายเราจะไม่สามารถใช้ความสามารถได้ยกเว้น Avatar \"Overdose",
    cost: 5,
    gem: 1,
    power: 3,
    symbol: "หุ่นยนต์",
  },
  {
    name: "ชาโค่ล Overdose",
    type: "Avatar",
    soi: 2,
    print: "BT08-032",
    rare: "SR",
    mainEffect:
      "ต่อเนื่อง ถ้า LIFE Card ฝ่ายเรา หงายตั้งแต่ 3 ใบหรือมากกว่า Avatar นี้จะเข้าสู่สถานะ Overdose\nต่อเนื่อง ถ้าการ์ดใบนี้อยู่ในสถานะ Overdose : ความสามารถ ธรณีสูบ และ สอดแนม ของ Avatar ฝ่ายตรงข้ามจะไม่สามารถทำได้     \nอัตโนมัติ เมื่อ Avatar นี้ทำลาย Avatar ฝ่ายตรงข้ามที่มีความสามารถ ธรณีสูบ หรือ สอดแนม : Avatar \"Overdose\" ทุกใบบน Avatar Zone ฝ่ายเรา POWER +1\n#Avatar ทุกใบในสนามฝ่ายเราจะไม่สามารถใช้ความสามารถได้ยกเว้น Avatar \"Overdose",
    cost: 5,
    gem: 0,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "เขียว",
  },
  {
    name: "เซตาม่อน Overdose",
    type: "Avatar",
    soi: 2,
    print: "BT08-033",
    rare: "R",
    mainEffect:
      "ต่อเนื่อง ถ้า LIFE Card ฝ่ายเรา หงายตั้งแต่ 3 ใบหรือมากกว่า Avatar นี้จะเข้าสู่สถานะ Overdose\nต่อเนื่อง ถ้าการ์ดใบนี้อยู่ในสถานะ Overdose : ความสามารถ โล่มนุษย์ และ ลูกฮึด ของ Avatar ฝ่ายตรงข้ามจะไม่สามารถทำได้\nอัตโนมัติ เมื่อ Avatar นี้ทำลาย Avatar ฝ่ายตรงข้ามที่มีความสามารถ โล่มนุษย์ หรือ ลูกฮึด : หงาย LIFE Card ใบบนสุดของฝ่ายตรงข้าม 1 ใบ\n#Avatar ทุกใบในสนามฝ่ายเราจะไม่สามารถใช้ความสามารถได้ยกเว้น Avatar \"Overdose",
    cost: 4,
    gem: 2,
    power: 5,
    symbol: "หุ่นยนต์",
    color: "เขียว",
  },
  {
    name: "ฮากลิ้ง วานรกับหมา",
    type: "Avatar",
    soi: 2,
    print: "BT08-034",
    rare: "C",
    mainEffect: "จุติ : สอดแนม 7 ใบ นำการ์ดที่เป็น โดนใจ 1 ใบ จากที่ สอดแนม ขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "เล่าปี่ ผู้นำคุณธรรมแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-035",
    rare: "UR",
    mainEffect:
      "แทงหลัง \nต่อเนื่อง Avatar \"จ๊กก๊ก\" ใน Avatar Zone ฝ่ายเรา POWER +1\nต่อเนื่อง ตราบเท่าที่มี  Avatar \"ขุนพล\" สีเขียว ที่เป็น Symbol ชาวต่างชาติ ใบอื่น ใน Avatar Zone ฝ่ายเรา Avatar ใบนี้ จะไม่สามารถถูกโจมตีและไม่ถูกเลือกเป็นเป้าหมายของ Magic Card ฝ่ายตรงข้าม\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: "ต่างชาติ",
    color: "เขียว",
    ex: "Only #1",
  },
  {
    name: "เล่าปี่ ผู้นำคุณธรรมแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-035",
    rare: "SCR",
    mainEffect:
      "แทงหลัง \nต่อเนื่อง Avatar \"จ๊กก๊ก\" ใน Avatar Zone ฝ่ายเรา POWER +1\nต่อเนื่อง ตราบเท่าที่มี  Avatar \"ขุนพล\" สีเขียว ที่เป็น Symbol ชาวต่างชาติ ใบอื่น ใน Avatar Zone ฝ่ายเรา Avatar ใบนี้ จะไม่สามารถถูกโจมตีและไม่ถูกเลือกเป็นเป้าหมายของ Magic Card ฝ่ายตรงข้าม\n#Avatar ใบนี้ถือว่ามีชื่อ \"ขุนพล",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: "ต่างชาติ",
    ex: "Only #1",
  },
  {
    name: "ขงเบ้ง กุนซือซ่อนกายแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-036",
    rare: "R",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ในเทิร์นใครก็ได้ เมื่อฝ่ายตรงข้าม ใช้ Magic Card และบน Avatar Zone เรามี เล่าปี่ ผู้นำคุณธรรมแห่งจ๊กก๊ก โดยที่ Avatar ใบอื่น ทั้งหมดบน Avatar Zone ฝ่ายเรา เป็น \"ขุนพล\" สีเขียว ที่เป็น Symbol ชาวต่างชาติ ทิ้งการ์ดบนมือ 1 ใบ : ยกเลิกการใช้ Magic Card ใบนั้น\n#สามารถใช้ความสามารถของการ์ดชื่อ ขงเบ้ง กุนซือซ่อนกายแห่งจ๊กก๊ก ได้เทิร์นละ 1 ครั้งเท่านั้น",
    cost: 4,
    gem: 1,
    power: 1,
    symbol: "ต่างชาติ",
    color: "เขียว",
  },
  {
    name: "ขงเบ้ง กุนซือซ่อนกายแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-036",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ในเทิร์นใครก็ได้ เมื่อฝ่ายตรงข้าม ใช้ Magic Card และบน Avatar Zone เรามี เล่าปี่ ผู้นำคุณธรรมแห่งจ๊กก๊ก โดยที่ Avatar ใบอื่น ทั้งหมดบน Avatar Zone ฝ่ายเรา เป็น \"ขุนพล\" สีเขียว ที่เป็น Symbol ชาวต่างชาติ ทิ้งการ์ดบนมือ 1 ใบ : ยกเลิกการใช้ Magic Card ใบนั้น\n#สามารถใช้ความสามารถของการ์ดชื่อ ขงเบ้ง กุนซือซ่อนกายแห่งจ๊กก๊ก ได้เทิร์นละ 1 ครั้งเท่านั้น",
    cost: 4,
    gem: 1,
    power: 1,
    symbol: "ต่างชาติ",
  },
  {
    name: "จูล่ง ขุนพลสุภาพบุรุษแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-037",
    rare: "SR",
    mainEffect:
      "จุติ ถ้า Avatar Zone ฝ่ายเรา ไม่มี Avatar ใบอื่น : อัญเชิญ Avatar \"ขุนพล\" สีเขียว ที่เป็น Symbol ชาวต่างชาติ 1 ใบ ที่ไม่ได้ชื่อ จูล่ง ขุนพลสุภาพบุรุษแห่งจ๊กก๊ก จาก นรกเรา ลงบน Avatar Zone ฝ่ายเรา\nสั่งใช้ จากบนมือ เมื่อ Avatar \"จ๊กก๊ก\" บน Avatar Zone ฝ่ายเรา ถูกทำลาย : สามารถอัญเชิญ จุติ การ์ดใบนี้จากบนมือได้ โดยการจ่าย Cost",
    cost: 6,
    gem: 2,
    power: 5,
    symbol: "ต่างชาติ",
    color: "เขียว",
  },
  {
    name: "มณโฑ ราชินีเหล่ายักษ์",
    type: "Avatar",
    soi: 2,
    print: "BT08-038",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ เซ่นไหว้ Avatar Symbol ยักษ์ 1 ใบ : อัญเชิญ Avatar Symbol ยักษ์ 1 ใบ จากนรกเรา ที่มี POWER เท่ากับ Avatar ที่ เซ่นไหว้ ไป แต่คนละชื่อ ลงบน Avatar Zone ฝ่ายเรา Avatar ที่ถูกอัญเชิญ ด้วยความสามารถนี้ จะได้รับ POWER +2 จนจบเทิร์น\n#Avatar ใบนี้ นับว่าเป็น Symbol ยักษ์ ด้วย",
    cost: 5,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "มณโฑ ราชินีเหล่ายักษ์",
    type: "Avatar",
    soi: 2,
    print: "BT08-038",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ เซ่นไหว้ Avatar Symbol ยักษ์ 1 ใบ : อัญเชิญ Avatar Symbol ยักษ์ 1 ใบ จากนรกเรา ที่มี POWER เท่ากับ Avatar ที่ เซ่นไหว้ ไป แต่คนละชื่อ ลงบน Avatar Zone ฝ่ายเรา Avatar ที่ถูกอัญเชิญ ด้วยความสามารถนี้ จะได้รับ POWER +2 จนจบเทิร์น\n#Avatar ใบนี้ นับว่าเป็น Symbol ยักษ์ ด้วย",
    cost: 5,
    gem: 1,
    power: 3,
    symbol: "คน",
  },
  {
    name: "ราชา รด.",
    type: "Avatar",
    soi: 2,
    print: "BT08-039",
    rare: "R",
    mainEffect:
      "อัตโนมัติ เมื่อมี Avatar \"ทหาร\" หรือ \"รด.\" เข้ามาใน Avatar Zone :  Avatar ใบนี้ POWER+1 \nเทิร์นละครั้ง สั่งใช้ : สอดแนม 2 ใบ นำ Avatar \"ทหาร\" หรือ \"รด.\" ที่เป็น {Symbol คน} และไม่ได้ชื่อ ราชา รด. จากที่สอดแนม 1 ใบ เข้ามาใน Avatar Zone ฝ่ายเรา การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ",
    cost: 3,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "จ่าอเวจี ทหารครูฝึก",
    type: "Avatar",
    soi: 2,
    print: "BT08-040",
    rare: "C",
    mainEffect: "ต่อเนื่อง Avatar {Symbol คน} สีเขียว ทุกใบบน Avatar Zone ฝ่ายเรา ได้รับชื่อ \"ทหาร",
    cost: 3,
    gem: 0,
    power: 4,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: "ศาสตราจารย์วานร",
    type: "Avatar",
    soi: 2,
    print: "BT08-041",
    rare: "C",
    mainEffect:
      "อัตโนมัติ ในช่วง End Phase หากบน Avatar Zone ฝ่ายเรามี \"วานร\" บนสนาม 3 ใบหรือมากกว่า : จั่วการ์ด 2 ใบ\n#สามารถใช้ความสามารถของ Avatar ชื่อ ศาสตราจารย์วานร ได้ เทิร์นละ 1 ครั้ง เท่านั้น",
    cost: 2,
    gem: 1,
    power: 3,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "ปีศาจวานร",
    type: "Avatar",
    soi: 2,
    print: "BT08-042",
    rare: "R",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เมื่อ Avatar ใบนี้ ทำลาย Avatar ของฝ่ายตรงข้ามจากการต่อสู้สำเร็จ และ Avatar Zone ฝ่ายเรามี \"วานร\" ใบอื่นอยู่  ทิ้งการ์ดบนมือ 1 ใบ  : เปลี่ยนสภาพ Avatar ใบนี้เป็นสภาพตื่น",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "รถถังเฟืองเหล็ก",
    type: "Avatar",
    soi: 2,
    print: "BT08-043",
    rare: "R",
    mainEffect: "ต่อเนื่อง ถ้าไม่มี Avatar สวมใส่ Avatar ใบนี้ 2 ใบ ขึ้นไปจะไม่สามารถโจมตีได้ และ Avatar ใบนี้ไม่สามารถสวมใส่การ์ดที่ไม่ใช่ \"Tank Ranger\" ได้",
    cost: 5,
    gem: 1,
    power: 6,
    symbol: "หุ่นยนต์",
    color: "เขียว",
  },
  {
    name: "ควายแบงค์",
    type: "Avatar",
    soi: 2,
    print: "BT08-044",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 0,
    power: 5,
    symbol: "สัตว์",
    color: "แดง",
  },
  {
    name: "หัวหน้าทหารหิมะ โจว",
    type: "Avatar",
    soi: 2,
    print: "BT08-045",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 1,
    power: 4,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "ตัวอะไรสักอย่างที่ใหญ่และน่ารัก",
    type: "Avatar",
    soi: 2,
    print: "BT08-046",
    rare: "C",
    mainEffect: "",
    cost: 8,
    gem: 2,
    power: 8,
    symbol: "เอเลี่ยน",
    color: "ฟ้า",
  },
  {
    name: "นกอีก๋อย",
    type: "Avatar",
    soi: 2,
    print: "BT08-047",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 3,
    power: 3,
    symbol: "สัตว์",
    color: "เขียว",
  },
  {
    name: "ขายแดก !!!",
    type: "Magic",
    soi: 2,
    print: "BT08-048",
    rare: "C",
    mainEffect: "ทิ้งการ์ด Modification Magic 1 ใบ จากมือ : จั่วการ์ด 2 ใบ",
    subtype: "Normal",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "แหมกำบ่อ้าย",
    type: "Magic",
    soi: 2,
    print: "BT08-049",
    rare: "C",
    mainEffect: "ถ้าการ์ดใน Deck มีเหลือ 15 ใบหรือต่ำกว่า เลือกการ์ดในนรก สูงสุด 5 ใบ ยกเว้น แหมกำบ่อ้าย : นำการ์ดที่เลือกกลับเข้า Deck แล้วสับ",
    subtype: "Normal",
    cost: 3,
    symbol: "จอมเวทย์",
  },
  {
    name: "ขอดูดดดดดด",
    type: "Magic",
    soi: 2,
    print: "BT08-050",
    rare: "R",
    mainEffect:
      "เลือก Avatar ของฝ่ายตรงข้าม 1 ใบ บน Avatar Zone Avatar ใบนั้น POWER-1 จนจบเทิร์น \nเลือก Avatar ของเรา 1 ใบ บน Avatar Zone Avatar ใบนั้น POWER+1 จนจบเทิร์น",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "หนังมนุษย์ ชุดแก้แค้น",
    type: "Magic",
    soi: 2,
    print: "BT08-051",
    rare: "R",
    mainEffect:
      "ส่ง Avatar \"ริกกี้\" 1 ใบ จาก Avatar Zone ฝ่ายเรา ลงนรก : อัญเชิญ จุติ Avatar \"ริกกี้\" 1 ใบจาก Deck เรา ที่มีชื่อแตกต่างกับ Avatar ที่ส่งไป\nสามารถใช้การ์ดใบนี้ในเทิร์นฝ่ายตรงข้ามหรือใน Battle Phase เราได้ โดยถือว่าเป็นการใช้ React Magic",
    subtype: "Normal",
    cost: 2,
    symbol: "แมลง",
  },
  {
    name: "หนังมนุษย์ ชุดแก้แค้น",
    type: "Magic",
    soi: 2,
    print: "BT08-051",
    rare: "SCR",
    mainEffect:
      "ส่ง Avatar \"ริกกี้\" 1 ใบ จาก Avatar Zone ฝ่ายเรา ลงนรก : อัญเชิญ จุติ Avatar \"ริกกี้\" 1 ใบจาก Deck เรา ที่มีชื่อแตกต่างกับ Avatar ที่ส่งไป\nสามารถใช้การ์ดใบนี้ในเทิร์นฝ่ายตรงข้ามหรือใน Battle Phase เราได้ โดยถือว่าเป็นการใช้ React Magic",
    subtype: "Normal",
    cost: 2,
    symbol: "แมลง",
  },
  {
    name: "Overdose",
    type: "Magic",
    soi: 2,
    print: "BT08-052",
    rare: "C",
    mainEffect: "หงาย LIFE Card ของเรา 2 ใบ จากนั้น อัญเชิญ Avatar \"Overdose\" Cost 5 หรือต่ำกว่า 1 ใบจาก Deck ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "การสละชีพของเทพธิดา",
    type: "Magic",
    soi: 2,
    print: "BT08-053",
    rare: "C",
    mainEffect:
      "ทำลาย Avatar \"เทพธิดาแห่งวัลฮัลลา\" ของเรา 1 ใบ : ทำลาย Avatar ของฝ่ายตรงข้าม 1 ใบ\nถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar symbol เทพ สีม่วง หรือ Magic Card : อัญเชิญ \"เทพธิดาแห่งวัลฮัลลา\" 1 ใบ จากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    subtype: "Normal",
    cost: 3,
    symbol: "เทพ",
  },
  {
    name: "การสละชีพของเทพธิดา",
    type: "Magic",
    soi: 2,
    print: "BT08-053",
    rare: "SCR",
    mainEffect:
      "ทำลาย Avatar \"เทพธิดาแห่งวัลฮัลลา\" ของเรา 1 ใบ : ทำลาย Avatar ของฝ่ายตรงข้าม 1 ใบ\nถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar symbol เทพ สีม่วง หรือ Magic Card : อัญเชิญ \"เทพธิดาแห่งวัลฮัลลา\" 1 ใบ จากนรกเรา ลงบน Avatar Zone ฝ่ายเรา",
    subtype: "Normal",
    cost: 3,
    symbol: "เทพ",
  },
  {
    name: "โจมตีตัวฉันให้โดนถ้าหากเธอทำได้",
    type: "Magic",
    soi: 2,
    print: "BT08-054",
    rare: "R",
    mainEffect: "เมื่อฝ่ายตรงข้ามโจมตี : เลือก Avatar 1 ใบบน Avatar Zone ฝ่ายเรา เปลี่ยนเป้าหมายการโจมตี ไปยัง Avatar ใบที่เลือก",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "แผนการ : ตอกฝาโลง",
    type: "Magic",
    soi: 2,
    print: "BT08-055",
    rare: "C",
    mainEffect: "เมื่อฝ่ายตรงข้ามใช้ความสามารถ คำสั่งเสีย : ยกเลิกความสามารถนั้น",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ลุ้นเยี่ยวเหนียว",
    type: "Magic",
    soi: 2,
    print: "BT08-056",
    rare: "C",
    mainEffect: "เมื่อฝ่ายตรงข้ามประกาศโจมตี และบน Avatar Zone ของทุกฝ่ายมี Avatar : เราและฝ่ายตรงข้ามทุกคน ทอยลูกเต๋าคนที่ทอยได้แต้มน้อยที่สุด ให้นำ Avatar บน สนามของตนเองทั้งหมดนำกลับเข้าใต้ Deck เจ้าของ",
    subtype: "React",
    cost: 0,
    symbol: "จอมเวทย์",
  },
  {
    name: "แหม่อ้ายก็~~~",
    type: "Magic",
    soi: 2,
    print: "BT08-057",
    rare: "C",
    mainEffect: "เมื่อฝ่ายตรงข้ามประกาศโจมตี : ยกเลิกการประกาศโจมตีนั้น",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "รัททาทุยเกาะหน้า",
    type: "Magic",
    soi: 2,
    print: "BT08-058",
    rare: "R",
    mainEffect: "เมื่อ Avatar Symbol รัททาทุย ถูกทำลาย : ทำลาย Avatar ของฝ่ายตรงข้าม ที่ Cost 5 หรือต่ำกว่า 1 ใบ จากนั้น อัญเชิญ Avatar Symbol รัททาทุย ที่มี Cost 1 Gem 1 POWER 1 จำนวน 1 ใบ จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    subtype: "React",
    cost: 1,
    symbol: "รัททาทุย",
  },
  {
    name: "ดาบศักดิ์สิทธิ์ คาเรนต์",
    type: "Magic",
    soi: 2,
    print: "BT08-059",
    rare: "R",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"อัศวินโต๊ะกลม\" เท่านั้น \nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้ทำลาย Avatar จากการต่อสู้ เลือก Magic Card บนสนาม ฝ่ายตรงข้าม 1 ใบ : ทำลายการ์ดใบนั้น  \nถ้า Avatar ที่สวมใส่การ์ดใบนี้คือ \"มอเดรด\" จะได้รับ เตะไข่ \nถ้าในเทิร์นนี้ ยังไม่ได้ใช้ Modification Magic สามารถ ธรณีสูบ 1 ใบ และนำการ์ดใบนี้ที่อยู่ในนรก ไปสวมใส่ให้ \"อัศวินโต๊ะกลม\" ใน Avatar Zone ฝ่ายเรา และนับว่าเป็นการใช้ Modification Magic",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "ดาบศักดิ์สิทธิ์ เอกซ์คาลิเบอร์",
    type: "Magic",
    soi: 2,
    print: "BT08-060",
    rare: "UR",
    mainEffect:
      "สวมใส่ได้เฉพาะ อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม เท่านั้น \nAvatar ที่สวมใส่การ์ดใบนี้ POWER +2\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้จะออกจาก Avatar Zone ฝ่ายเรา สามารถทำลายการ์ดใบนี้แทนได้ \nสั่งใช้ จากนรก สามารถนำการ์ดใบนี้ที่อยู่ในนรก ไปสวมใส่ให้ อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม ใน Avatar Zone ฝ่ายเรา และนับว่าเป็นการใช้ Modification Magic",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
    ex: "Only #1",
  },
  {
    name: "ดาบศักดิ์สิทธิ์ เอกซ์คาลิเบอร์",
    type: "Magic",
    soi: 2,
    print: "BT08-060",
    rare: "SCR",
    mainEffect:
      "สวมใส่ได้เฉพาะ อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม เท่านั้น \nAvatar ที่สวมใส่การ์ดใบนี้ POWER +2\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้จะออกจาก Avatar Zone ฝ่ายเรา สามารถทำลายการ์ดใบนี้แทนได้ \nสั่งใช้ จากนรก สามารถนำการ์ดใบนี้ที่อยู่ในนรก ไปสวมใส่ให้ อาเธอร์ ราชาแห่งอัศวินโต๊ะกลม ใน Avatar Zone ฝ่ายเรา และนับว่าเป็นการใช้ Modification Magic",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
    ex: "Only #1",
  },
  {
    name: "ขวาน 7 สี",
    type: "Magic",
    soi: 2,
    print: "BT08-061",
    rare: "SR",
    mainEffect:
      "ความสามารถของการ์ดใบนี้จะทำงานตามสีของ Avatar ที่สวมใส่การ์ดใบนี้\nสีแดง เมื่อ Avatar ที่สวมใส่การ์ดนี้ โจมตี : POWER +2 จนจบการต่อสู้\nสีฟ้า เมื่อ Avatar ที่สวมใส่การ์ดนี้ โจมตี : จั่วการ์ด 1 ใบ\nสีม่วง เมื่อ Avatar ที่สวมใส่การ์ดนี้ โจมตี : ธรณีสูบ 1 ใบ POWER +1 จนจบเทิร์น\nสีเขียว Avatar ใบนี้ได้รับ ลูกฮึด",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "เนยถั่ว",
    type: "Magic",
    soi: 2,
    print: "BT08-062",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ เต่า เท่านั้น \nAvatar ที่ต่อสู้กับ Avatar ที่สวมใส่การ์ดใบนี้ POWER -1",
    subtype: "Modification",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "บิฟร็อสต์ สะพานสายรุ้ง",
    type: "Magic",
    soi: 2,
    print: "BT08-063",
    rare: "R",
    mainEffect:
      "อัตโนมัติ เมื่อมีการ ธรณีสูบ : เลือก Avatar 1 ใบ บน Avatar Zone ฝ่ายเรา ได้รับ สามัคคี จนจบเทิร์น\nถ้าการ์ดใบนี้ถูก ธรณีสูบ ด้วยการ์ด Avatar symbol เทพ สีม่วง หรือ Magic Card : นำการ์ดใบนี้ขึ้นมือ\n#การ์ดใบนี้นับเป็นชื่อ แอสการ์ดคือสถานที่ไม่ใช่ผู้คน",
    subtype: "Land",
    cost: 2,
    symbol: "เทพ",
  },
  {
    name: "โรงเรียนเวทย์มนต์",
    type: "Magic",
    soi: 2,
    print: "BT08-064",
    rare: "R",
    mainEffect:
      "ทุกครั้งที่มีการใช้งานการ์ด \"คาถา\" นำ Magic Card 1 ใบจากในนรกเรา มาวางบน Magic Zone ฝ่ายเราแบบคว่ำ\nเทิร์นละครั้ง สั่งใช้ : อัญเชิญ Avatar \"จอมเวทย์\" 1 ใบ จากมือ โดยที่สามารถ นำ Magic Card ที่คว่ำอยู่ กี่ใบก็ได้ที่อยู่ใน Magic Zone ลงนรกเพื่อเป็น Gem ในการอัญเชิญ Avatar ได้ โดยที่ 1 ใบจะมีค่าเท่ากับ Gem 1",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "โคกอีสานนูน",
    type: "Magic",
    soi: 2,
    print: "BT08-065",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ถ้าเรามี Avatar \"อีสานสลิงเกอร์\" บน Avatar Zone เลือกการ์ดในนรกเรา 6 ใบ โดยสามารถเลือก Magic Card ได้ไม่เกิน 2 ใบ นำการ์ดที่เลือกกลับเข้า Deck และสับ : จั่วการ์ด 1 ใบ\nเทิร์นละครั้ง สั่งใช้ ถ้าในเทิร์นนี้มีการนำการ์ดจากนรกกลับเข้า Deck 6 ใบหรือมากกว่า  : เลือก Avatar \"อีสานสลิงเกอร์\" บน Avatar Zone ฝ่ายเรา และ Avatar บน Avatar Zone ของฝ่ายตรงข้าม อย่างละ 1 ใบ นำ Avatar ทั้ง 2 ใบ ทำการโจมตีใส่กันโดยไม่ต้องเปลี่ยนเป็น สภาพนอน ในระหว่างการทำการต่อสู้นี้ ผู้เล่นทั้ง 2 ฝ่ายไม่สามารถใช้ React Magic ได้",
    subtype: "Land",
    cost: 2,
    symbol: "ต้นไม้",
    ex: "Only #1",
  },
  {
    name: "โคกอีสานนูน",
    type: "Magic",
    soi: 2,
    print: "BT08-065",
    rare: "SCR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ ถ้าเรามี Avatar \"อีสานสลิงเกอร์\" บน Avatar Zone เลือกการ์ดในนรกเรา 6 ใบ โดยสามารถเลือก Magic Card ได้ไม่เกิน 2 ใบ นำการ์ดที่เลือกกลับเข้า Deck และสับ : จั่วการ์ด 1 ใบ\nเทิร์นละครั้ง สั่งใช้ ถ้าในเทิร์นนี้มีการนำการ์ดจากนรกกลับเข้า Deck 6 ใบหรือมากกว่า  : เลือก Avatar \"อีสานสลิงเกอร์\" บน Avatar Zone ฝ่ายเรา และ Avatar บน Avatar Zone ของฝ่ายตรงข้าม อย่างละ 1 ใบ นำ Avatar ทั้ง 2 ใบ ทำการโจมตีใส่กันโดยไม่ต้องเปลี่ยนเป็น สภาพนอน ในระหว่างการทำการต่อสู้นี้ ผู้เล่นทั้ง 2 ฝ่ายไม่สามารถใช้ React Magic ได้",
    subtype: "Land",
    cost: 2,
    symbol: "ต้นไม้",
    ex: "Only #1",
  },
  {
    name: "เรือรบโบราณ",
    type: "Construct",
    soi: 2,
    print: "BT08-066",
    rare: "R",
    mainEffect:
      "เทิร์นละครั้ง เลือกปฏิบัติ :\n1) สอดแนม 5 ใบ เลือก \"พลเดินทัพ\" หรือ \"ขุนพล\" ที่เป็น symbol ชาวต่างชาติ และมี POWER 2 หรือต่ำกว่า 1 ใบ จากที่สอดแนม นำการ์ดใบนั้นขึ้นมือ หรือ อัญเชิญลงบน Avatar Zone ฝ่ายเรา การ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck\n2) นำ \"พลเดินทัพ\" 1 ใบ จากนรกเรา กลับเข้า Deck แล้วสับ\n#สามารถมีการ์ดชื่อนี้ใน Construct Zone ได้สูงสุด 3 ใบ",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "ต้นไม้",
    color: "แดง",
  },
  {
    name: "สนามของนักวิ่งตัวจริง",
    type: "Construct",
    soi: 2,
    print: "BT08-067",
    rare: "C",
    mainEffect: "ต่อเนื่อง Avatar Cost 0 ทุกใบบน Avatar Zone ฝ่ายเรา POWER +1",
    cost: 0,
    gem: 1,
    power: 0,
    symbol: "สิ่งก่อสร้าง",
    color: "แดง",
  },
  {
    name: "ยิมทมิฬ",
    type: "Construct",
    soi: 2,
    print: "BT08-068",
    rare: "C",
    mainEffect: "ต่อเนื่อง Avatar \"บึงทมิฬ People\" ทุกใบ POWER +1 และได้รับ สามัคคี และ ถ้าบน Avatar Zone ฝ่ายเรามี วอเตอร์แมน การ์ดใบนี้จะไม่สามารถถูกเลือกเป็นเป้าหมายการโจมตีได้",
    cost: 4,
    gem: 2,
    power: 1,
    symbol: "หุ่นยนต์",
    color: "ฟ้า",
  },
  {
    name: "บัลลังก์โอดิน",
    type: "Construct",
    soi: 2,
    print: "BT08-069",
    rare: "SR",
    mainEffect:
      "ต่อเนื่อง ในช่วง Battle Phase ฝ่ายเรา Avatar {Symbol เทพ} สีม่วง ทุกใบของเรา POWER+1 \nแต่ถ้าเป็น \"โอดิน\" POWER +3 แทน\nเทิร์นละครั้ง สั่งใช้ ทำลายการ์ดใบนี้ : นำ \"โอดิน\" 1 ใบ จากในนรก กลับขึ้นมือ\nเมื่อการ์ดใบนี้ถูก ธรณีสูบ ก่อสร้าง การ์ดใบนี้ลงบน Construct Zone ฝ่ายเรา",
    cost: 3,
    gem: 2,
    power: 4,
    symbol: "เทพ",
    color: "ม่วง",
  },
  {
    name: "บัลลังก์โอดิน",
    type: "Construct",
    soi: 2,
    print: "BT08-069",
    rare: "SCR",
    mainEffect:
      "ต่อเนื่อง ในช่วง Battle Phase ฝ่ายเรา Avatar {Symbol เทพ} สีม่วง ทุกใบของเรา POWER+1 \nแต่ถ้าเป็น \"โอดิน\" POWER +3 แทน\nเทิร์นละครั้ง สั่งใช้ ทำลายการ์ดใบนี้ : นำ \"โอดิน\" 1 ใบ จากในนรก กลับขึ้นมือ\nเมื่อการ์ดใบนี้ถูก ธรณีสูบ ก่อสร้าง การ์ดใบนี้ลงบน Construct Zone ฝ่ายเรา",
    cost: 3,
    gem: 2,
    power: 4,
    symbol: "เทพ",
    color: "ม่วง",
  },
  {
    name: "อ่อ กระต่ายตาย",
    type: "Life",
    soi: 2,
    print: "BT08-070",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไม่นะ นายแพทย์ต่ายผู้ซื่อสัตย์และเป็นที่รักของทุกคนตายแล้ว ใครกันที่ทำร้ายต่ายได้ลงคอ มันช่างโหดร้าย ทารุณ ป่าเถื่อนเสียจริง",
  },
];
