import { Card } from "@/src/types/cards";

export const CARDS_FPRO: Card[] = [
  {
    name: "มณโฑ ราชินีเหล่ายักษ์",
    type: "Avatar",
    soi: 2,
    print: "FPRO-001",
    rare: "UR",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ เซ่นไหว้ Avatar {symbol ยักษ์} 1 ใบ : อัญเชิญ Avatar {symbol ยักษ์} 1 ใบ จากนรกเรา ที่มี POWER เท่ากับ Avatar ที่ เซ่นไหว้ ไป แต่คนละชื่อ ลงบน Avatar Zone ฝ่ายเรา Avatar ที่ถูกอัญเชิญ ด้วยความสามารถนี้ จะได้รับ POWER +2 จนจบเทิร์น\n#Avatar ใบนี้ นับว่าเป็น Symbol ยักษ์ ด้วย",
    cost: 5,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "เขียว",
  },
  {
    name: 'หุ่นนักรบผู้กล้า : ไมเกรน',
    type: 'Avatar',
    cost: 5,
    gem: 2,
    power: 4,
    symbol: 'หุ่นยนต์',
    print: 'FPRO-002',
    rare: 'UR',
    dropRate: '',
    soi: 3,
    mainEffect: 'จุติ : สอดแนม 5 ใบ เลือก Modification Magic "อาวุธหุ่นนักรบผู้กล้า" 1 ใบจากที่ สอดแนม และนำขึ้นมือ การ์ดที่เหลือเรียงและนำไว้ใต้ Deck\nเทิร์นละครั้ง อัตโนมัติ เมื่อมีการใช้ Modification Magic "อาวุธหุ่นนักรบผู้กล้า" : จั่วการ์ด 1 ใบ'
  },
  {
    name: "พี่หน่วง พิธีกรผมสวย",
    type: "Avatar",
    soi: 2,
    print: "FPRO-003",
    rare: "UR",
    mainEffect:
      "จุติ : นำ \"ยานรายการ เถียงทันหน่วง\" จาก Deck หรือ นรก 1 ใบขึ้นมือ หากนำจาก Deck ให้สับ Deck\nเทิร์นละครั้ง สั่งใช้ ถ้าใน Construct Zone ฝ่ายเรามี \"ยานรายการ เถียงทันหน่วง\" ทิ้งการ์ดบนมือ 1 ใบ : เลือก Avatar ฝ่ายตรงข้าม 1 ใบ ใน Avatar Zone ที่มี สามัคคี , เตะไข่ , โล่มนุษย์ หรือ คำสั่งเสีย นำ Avatar ใบนั้น มาไว้ที่ Magic Zone ฝ่ายเรา\nคำสั่งเสีย : ฝ่ายตรงข้าม เลือก Avatar ที่อยู่ใน Magic Zone ฝ่ายเรา 1 ใบ กลับขึ้นมือเจ้าของาของ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ม่วง",
  },
  {
    name: "พระอิศวร เทพผู้ทำลาย",
    type: "Avatar",
    soi: 1,
    print: "FPRO-004",
    rare: "UR",
    mainEffect:
      "จุติ : ทำลาย การ์ด บนสนาม 1 ใบ\nเทิร์นละครั้ง สั่งใช้ : สามารถทำลาย การ์ด บนสนาม 1 ใบ",
    cost: 8,
    gem: 1,
    gemColor: "แดง",
    power: 7,
    symbol: "เทพ",
    color: "แดง",
    ex: "Only #1",
  },
  {
    name: 'พระนารายณ์ เทพผู้พิทักษ์',
    type: 'Avatar',
    cost: 8,
    gem: 1,
    power: 8,
    symbol: 'เทพ',
    print: 'FPRO-005',
    rare: 'UR',
    dropRate: '',
    soi: 3,
    mainEffect: 'โล่มนุษย์ เตะไข่\nอัตโนมัติ เมื่อ Avatar ใบนี้จะถูกทำลาย : ปรับ POWER ตั้งต้นของ Avatar ใบนี้ลดลงครึ่งหนึ่งแทนการถูกทำลาย ความสามารถนี้ ใช้ได้เพียง 1 ครั้งต่อการอัญเชิญ',
    gemColor: 'แดง',
  },
  {
    name: "พญายักษ์ ทศกัณฐ์",
    type: "Avatar",
    soi: 1,
    print: "FPRO-006",
    rare: "UR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ Avatar {symbol ยักษ์} ที่มี POWER 3 ยกเว้น \"ทศกัณฐ์\" จาก Deck ฝ่ายเรา 1 ใบลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck",
    cost: 4,
    gem: 1,
    power: 5,
    symbol: "ยักษ์",
    color: "เขียว",
  },
  {
    name: "ไดโนกาฬสินธุ์ - สยามโมไทรันนัส",
    type: "Avatar",
    soi: 1,
    print: "FPRO-007",
    rare: "UR",
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : สอดแนม 5 ใบ นำ Avatar {symbol กะปอม} กี่ใบก็ได้ อัญเชิญ จุติ ลงบน Avatar zone ฝ่ายเรา นำการ์ดที่เหลือกลับเข้า Deck แล้วสับ",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "กะปอม",
    color: "ฟ้า",
    ex: "Only #1",
  },
];
