import { Card } from "@/src/types/cards";

export const CARDS_PRE0: Card[] = [
  {
    name: "ผู้เล่นยุคแรก",
    type: "Avatar",
    soi: 1,
    print: "PRE0-001",
    rare: "C",
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่ายCost) : ดูการ์ด 3 ใบจากใบล่างสุดของ Deck อีกฝ่ายหลังจากนั้นเลือก 1 ใบวางไว้ใบบนสุดของ Deck อีกฝ่าย การ์ดที่เหลือเรียงไว้ตำแหน่งเดิม",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ม่วง",
    ex: "ลำเอียง",
  },
  {
    name: "น้ำใจ",
    type: "Magic",
    soi: 1,
    print: "PRE0-001-2",
    rare: "C",
    mainEffect:
      "Avatar ที่สวมใส่การ์ดใบนี้ POWER +0",
    cost: 1,
    symbol: "จอมเวทย์",
    subtype: "Modification",
  },
  {
    name: "ผู้เล่นภักดี",
    type: "Avatar",
    soi: 1,
    print: "PRE0-002",
    rare: "C",
    mainEffect:
      "จุติ : สุ่มการ์ดบนมืออีกฝ่าย 1 ใบวางไว้ใบบนสุดของ Deck อีกฝ่าย",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
    ex: "ลำเอียง",
  },
  {
    name: "ผู้เล่นเหลี่ยม",
    type: "Avatar",
    soi: 1,
    print: "PRE0-003",
    rare: "C",
    mainEffect: "จุติ : ดูการ์ดบนมือฝ่ายตรงข้ามทั้งหมด",
    cost: 4,
    gem: 4,
    power: 4,
    symbol: "คน",
    color: "เขียว",
    ex: "ลำเอียง",
  },
  {
    name: "ผู้เล่นจำไม",
    type: "Avatar",
    soi: 1,
    print: "PRE0-004",
    rare: "C",
    mainEffect:
      "การ์ดใบนี้จะสามารถอัญเชิญได้โดยการทิ้งการ์ด GEM 1 5 ใบ เท่านั้น\nจุติ : ถามจำนวนการ์ดใน Deck ที่เหลือของ อีกฝ่ายว่า มีการ์ด Avatar กี่ใบ Magic กี่ใบ และ {only} คืออะไร",
    cost: 5,
    gem: 4,
    power: 5,
    symbol: "คน",
    color: "เขียว",
    ex: "ลำเอียง",
  },
  {
    name: "ผู้เล่นมั่ว",
    type: "Avatar",
    soi: 2,
    print: "PRE0-005",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง ถ้าใน นรกฝ่ายเรา มี Avatar ที่ชื่อไม่ซ้ำกัน 10 ใบขึ้นไป การ์ดใบนี้ POWER +2",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "เอเลี่ยน",
    color: "แดง",
  },
  {
    name: "ผู้เล่นโซเชียล",
    type: "Avatar",
    soi: 2,
    print: "PRE0-005-2",
    rare: "C",
    mainEffect:
      "จุติ : เลือก Avatar ฝ่ายตรงข้าม ที่ POWER น้อยกว่า Avatar ใบนี้ : นำมาไว้ที่ Magic Zone ของฝ่ายเรา",
    cost: 5,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "ม่วง",
  },
];
