import { Card } from "@/src/types/cards";

export const CARDS_SD02: Card[] = [
  {
    name: "กุ่ย",
    type: "Avatar",
    soi: 1,
    print: "SD02-001",
    rare: "C",
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"ฮอล\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ฮอล",
    type: "Avatar",
    soi: 1,
    print: "SD02-002",
    rare: "C",
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"นาย\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "นาย",
    type: "Avatar",
    soi: 1,
    print: "SD02-003",
    rare: "C",
    mainEffect:
      "สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น)\n\nจุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\" 1 ใบจาก Deck ขึ้นมือ หลังจากนั้นสับ Deck",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ริกกี้ เพื่อนรัก",
    type: "Avatar",
    soi: 1,
    print: "SD02-004",
    rare: "SR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำการ์ดชื่อ \"กุ่ย\" , \"ฮอล\" หรือ \"นาย\" ได้สูงสุด 3 ใบ จากนรกเรา กลับเข้า Deck หลังจากนั้นสับ Deck แล้วจั่วการ์ด 1 ใบ",
    cost: 3,
    gem: 2,
    power: 1,
    symbol: "แมลง",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "วีรบุรุษปากซอย",
    type: "Avatar",
    soi: 1,
    print: "SD02-005",
    rare: "UR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" ได้สูงสุด 3 ใบจากนรกเราขึ้นมือ",
    cost: 6,
    gem: 2,
    power: 6,
    symbol: "คน",
    color: "ฟ้า",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "วีรบุรุษปากซอย",
    type: "Avatar",
    soi: 1,
    print: "SD02-005",
    rare: "PR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" ได้สูงสุด 3 ใบจากนรกเราขึ้นมือ",
    cost: 6,
    gem: 2,
    power: 6,
    symbol: "คน",
    color: "ฟ้า",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "วีรบุรุษปากซอย",
    type: "Avatar",
    soi: 1,
    print: "SD02-005",
    rare: "CBR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : นำ Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" ได้สูงสุด 3 ใบจากนรกเราขึ้นมือ",
    cost: 6,
    gem: 2,
    power: 6,
    symbol: "คน",
    color: "ฟ้า",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ครูภาษาไทย",
    type: "Avatar",
    soi: 1,
    print: "SD02-006",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "นักเรียน แบงค์",
    type: "Avatar",
    soi: 1,
    print: "SD02-007",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 3,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "เด็กไม่ชอบแมลงสาบมากๆ",
    type: "Avatar",
    soi: 1,
    print: "SD02-008",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ตำรวจ",
    type: "Avatar",
    soi: 1,
    print: "SD02-009",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "เด็กไม่ชอบแมลงสาบ",
    type: "Avatar",
    soi: 1,
    print: "SD02-010",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ลุงข้างห้อง",
    type: "Avatar",
    soi: 1,
    print: "SD02-011",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 1,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "แท็กซี่ตีนเปล่า",
    type: "Avatar",
    soi: 1,
    print: "SD02-012",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ไอ้ดำ",
    type: "Avatar",
    soi: 1,
    print: "SD02-013",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: "สัตว์",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ปื๊ด เด็กติดยา",
    type: "Avatar",
    soi: 1,
    print: "SD02-014",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "รัททาทุย ผู้พิทักษ์ราชีนี",
    type: "Avatar",
    soi: 1,
    print: "SD02-015",
    rare: "C",
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: "รัททาทุย",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ระเบิดVery Fat Man",
    type: "Magic",
    soi: 1,
    print: "SD02-016",
    rare: "SR",
    mainEffect: "ส่ง Avatar \"กุ่ย\",\"ฮอล\" และ \"นาย\" อย่างละ 1 ใบ จากบนมือเรา และ,หรือ บนสนามเราลงนรก : ทำลาย Avatar ทุกใบบนสนามฝ่ายตรงข้าม",
    subtype: "React",
    cost: 0,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม้เกาหลัง",
    type: "Magic",
    soi: 1,
    print: "SD02-017",
    rare: "C",
    mainEffect: "Avatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ เตะไข่ (Avatar ใบนี้สามารถโจมตีไปที่ LIFE Card ได้โดยตรง แม้ว่า Avatar Zone ของอีกฝ่ายจะมี Avatar อยู่ก็ตาม)",
    subtype: "Modification",
    cost: 2,
    symbol: "รัททาทุย",
    dropRate: "2 / กล่อง",
  },
  {
    name: "บำเพ็ญประโยชน์",
    type: "Magic",
    soi: 1,
    print: "SD02-018",
    rare: "C",
    mainEffect: "ส่ง Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" 1 ใบ จากบนมือลงนรก : จั่วการ์ด 2 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "สละเพื่อนเพื่อช่วยเพื่อน",
    type: "Magic",
    soi: 1,
    print: "SD02-019",
    rare: "C",
    mainEffect: "ส่ง Avatar ชื่อ \"กุ่ย\",\"ฮอล\" หรือ \"นาย\" 1 ใบ จากบนมือเรา หรือ บนสนามเราลงนรก : นำ Avatar 1 ใบบนสนามกลับขึ้นมือ",
    subtype: "React",
    cost: 1,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "สมชาย ห้องเช่าถูกๆ",
    type: "Magic",
    soi: 1,
    print: "SD02-020",
    rare: "C",
    mainEffect: "POWER +2 ให้ Avatar \"กุ่ย\",\"ฮอล\" และ \"นาย\" ที่สั่งโจมตีจนจบการต่อสู้นั้น",
    subtype: "Land",
    cost: 1,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม่นะ กุ่ย !",
    type: "Life",
    soi: 1,
    print: "SD02-021",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "กุ่ยเป็นเด็กที่ขี้เล่น มีจินตนาการ และเป็นตัวโปรดในการ์ตูนผม แต่มึงก็ยังปล่อยให้กุ่ยตายแล้วตอนนี้การ์ตูนกูไม่สนุกละ",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ฮอล !",
    type: "Life",
    soi: 1,
    print: "SD02-022",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ถึงฮอลจะเป็นคนขี้กลัว แต่เขาก็พร้อมที่จะสู้เมื่อเพื่อนฝูงของเขากำลังตกอยู่ในอันตราย และโลกนี้ก็คงอบอุ่นน้อยลงที่ต้องขาดเพื่อนดีๆอย่างฮอล",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ นาย !",
    type: "Life",
    soi: 1,
    print: "SD02-023",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไอ้นายจะเป็นคนตรงๆและคุณอาจไม่ชอบมัน แต่คำเหล่านั้นมาจากใจของคนจริงใจที่คุณเพิ่งปล่อยตายไป นั้นก็เชิญอยู่กับพวกเพื่อนเทียมคำชมปลอมๆที่ยังไงคุณก็รู้ว่ามันกลวง",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ครู !",
    type: "Life",
    soi: 1,
    print: "SD02-024",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ครูอ้อยคือเครื่องผลิตอนาคตของชาติมายาวนานกว่า43ปีโดยไม่หยุดพัก และจุดจบของเธอครั้งนี้จะเป็นบทเรียนสุดท้ายให้ทุกคนรู้ว่า การทำดีที่ไม่มีใครเห็นค่ามันก็แบบนี้แหละ",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ จามาล !",
    type: "Life",
    soi: 1,
    print: "SD02-025",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "จามาล นักร้องนำของวงHeartz Boyz ที่ตลาดพลู จามาลใช้เงินรักษามะเร็งที่เหลือมาตั้งวงเพื่อทำตามฝันของเขา และดูเหมือนว่าตอนนี้เสียงของจามาลจะไม่ดังพอที่จะไปสู่หูของคนทั่วโลกหรือแม้แต่แม่ของเขา",
    dropRate: "1 / กล่อง",
  },
];
