import { Card } from "@/src/types/cards";

export const CARDS_SD03: Card[] = [
  {
    name: "พญายม",
    type: "Avatar",
    soi: 1,
    print: "SD03-001",
    rare: "SR",
    mainEffect: "จุติ (เมื่อ Avatar ตัวนี้ถูกอัญเชิญลงสนามแบบจ่าย Cost) : เลือก Avatar \"นายนิรยบาล\" ในนรกเรา 1 ใบ อัญเชิญลง Avatar Zone ฝ่ายเรา",
    cost: 5,
    gem: 1,
    power: 5,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "นายนิรยบาล พ่อจีจ้า",
    type: "Avatar",
    soi: 1,
    print: "SD03-002",
    rare: "C",
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้เป็นเป้าหมายโจมตีหรือสั่งโจมตี : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ POWER +1 จนจบเทิร์น",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "นายนิรยบาล แว่น",
    type: "Avatar",
    soi: 1,
    print: "SD03-003",
    rare: "C",
    mainEffect:
      "ถ้าการ์ดใบนี้ถูกส่งลงนรกด้วยผลของ ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) : สามารถอัญเชิญการ์ดใบนี้ลง Avatar Zone จากนรกได้\n\n#การ์ดใบนี้ไม่สามารถลงสนามจากบนมือได้",
    cost: 0,
    gem: 1,
    power: 4,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "นายนิรยบาล อ้วน",
    type: "Avatar",
    soi: 1,
    print: "SD03-004",
    rare: "C",
    mainEffect: "ต่อเนื่อง ตราบเท่าที่การ์ดใบนี้อยู่บน Avatar Zone แล้วมีการ ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) จากความสามารถของการ์ดฝ่ายเรา ยกเว้น \"นายนิรยบาล อ้วน\"  ธรณีสูบ เพิ่ม 2 ใบ",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "สุวาน",
    type: "Avatar",
    soi: 1,
    print: "SD03-005",
    rare: "UR",
    mainEffect: "ต่อเนื่อง Avatar ใบนี้จะ เพื่ม POWER ตามจำนวน Avatar \"นายนิรยบาล\" ที่ชื่อต่างกันในนรกเราชื่อละ 1",
    cost: 5,
    gem: 4,
    power: 0,
    symbol: "นรก",
    color: "ม่วง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "สุวาน",
    type: "Avatar",
    soi: 1,
    print: "SD03-005",
    rare: "PR",
    mainEffect: "Avatar ใบนี้จะ เพื่ม POWER ตามจำนวน Avatar \"นายนิรยบาล\" ที่ชื่อต่างกันในนรกตัวละ 1",
    cost: 5,
    gem: 4,
    power: 0,
    symbol: "นรก",
    color: "ม่วง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "สุวาน",
    type: "Avatar",
    soi: 1,
    print: "SD03-005",
    rare: "CBR",
    mainEffect: "Avatar ใบนี้จะ เพื่ม POWER ตามจำนวน Avatar \"นายนิรยบาล\" ที่ชื่อต่างกันในนรกตัวละ 1",
    cost: 5,
    gem: 4,
    power: 0,
    symbol: "นรก",
    color: "ม่วง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "นายนิรยบาล ชาวนา",
    type: "Avatar",
    soi: 1,
    print: "SD03-006",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "นายนิรยบาล ปฎิรูป",
    type: "Avatar",
    soi: 1,
    print: "SD03-007",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "นายนิรยบาล กล้าม",
    type: "Avatar",
    soi: 1,
    print: "SD03-008",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 3,
    power: 4,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "นายนิรยบาล แบงค์",
    type: "Avatar",
    soi: 1,
    print: "SD03-009",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 3,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "แม่นีโม่ขยับไม่ได้",
    type: "Avatar",
    soi: 1,
    print: "SD03-010",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 3,
    power: 0,
    symbol: "คน",
    color: "ม่วง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ปื้ด คนดี",
    type: "Avatar",
    soi: 1,
    print: "SD03-011",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "พวกบาปหนา",
    type: "Avatar",
    soi: 1,
    print: "SD03-012",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 3,
    symbol: "นรก",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เจ้าที่",
    type: "Avatar",
    soi: 1,
    print: "SD03-013",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 1,
    power: 1,
    symbol: "ผี",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ตำรวจสัมภเวสี ปวิณ",
    type: "Avatar",
    soi: 1,
    print: "SD03-014",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 3,
    symbol: "ผี",
    color: "ม่วง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ตำรวจสัมภเวสี นิวัต",
    type: "Avatar",
    soi: 1,
    print: "SD03-015",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "ผี",
    color: "ม่วง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "กระทะทองแดง",
    type: "Magic",
    soi: 1,
    print: "SD03-016",
    rare: "C",
    mainEffect: "ส่ง Avatar {symbol นรก} 1 ใบจากมือลงนรก : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ แล้วจั่วการ์ดจาก Deck 2 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "นรก",
    dropRate: "2 / กล่อง",
  },
  {
    name: "บัญชีหนังหมา",
    type: "Magic",
    soi: 1,
    print: "SD03-017",
    rare: "C",
    mainEffect: "นำ Avatar \"นายนิรยบาล\" Cost 4 หรือต่ำกว่า 1 ใบจาก Deck ขึ้นมือหลังจากนั้นสับ Deck  จนกว่าจะจบเกมนี้ Avatar ชื่อที่นำขึ้นมือมาด้วยความสามารถของการ์ดใบนี้จะไม่สามารถใช้เป็น Cost ในการอัญเชิญได้",
    subtype: "Normal",
    cost: 1,
    symbol: "นรก",
    dropRate: "2 / กล่อง",
  },
  {
    name: "หอกแหลมแทงทุกวัน",
    type: "Magic",
    soi: 1,
    print: "SD03-018",
    rare: "C",
    mainEffect:
      "POWER +1 ให้ Avatar {symbol นรก} ที่สวมใส่\n\nถ้าการ์ดใบนี้ถูกส่งลงนรกด้วยผลของ ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) และในเทิร์นนี้ยังไม่ได้ใช้ Modification Magic : สามารถใช้งานการ์ดใบนี้จากนรกได้",
    subtype: "Modification",
    cost: 1,
    symbol: "นรก",
    dropRate: "2 / กล่อง",
  },
  {
    name: "สิมพลีนรก",
    type: "Magic",
    soi: 1,
    print: "SD03-019",
    rare: "SR",
    mainEffect: "POWER +1 ให้ Avatar {symbol นรก} ทุกใบบนสนาม",
    subtype: "Land",
    cost: 2,
    symbol: "นรก",
    dropRate: "2 / กล่อง",
  },
  {
    name: "จิ้มมันเลย จิ้ม!",
    type: "Magic",
    soi: 1,
    print: "SD03-020",
    rare: "C",
    mainEffect: "เมื่อมี Avatar อัญเชิญมาบนสนาม ทิ้ง Avatar {symbol นรก} 1 ใบจากมือลงนรก ที่ Cost มากกว่าหรือเท่ากับ Avatar ใบนั้น : ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 2 ใบ และ ทำลาย Avatar ใบนั้น",
    subtype: "React",
    cost: 2,
    symbol: "นรก",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม่นะ แม่นีโม่ !",
    type: "Life",
    soi: 1,
    print: "SD03-021",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "แม่ของนีโม่ทนทุกข์มานานหลายปี ตั้งแต่ที่ต้องแต่งงานกับผัวขี้เหล้าที่ทิ้งเธอและลูกตั้งแต่นีโม่ยังเล็กและอุบัติเหตุบนทางด่วนอีกที่ทำให้เธอขยับไม่ได้ และนี้สินะคือวิธีส่งเธอไปสบายของคุณ",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ เต๋า !",
    type: "Life",
    soi: 1,
    print: "SD03-022",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "นายนิรยบาลเต๋า เขาอาจจะทำงานในนรกคุณเลยไม่ได้คิดไรมากที่จะส่งเขาไปตาย แต่เต๋าก็มีชีวิตและมีความฝันที่จะออกไปจากวงจรนรกเหมือนคนอื่นๆเหมือนกัน",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ไอ้ดำ !",
    type: "Life",
    soi: 1,
    print: "SD03-023",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "มึงปล่อยไอ้ดำตาย! อันนี้กุโกรธยิ่งกว่ามึงปล่อยหลวงพ่อตายอีก ทำไมวะเพราะว่าหมามันไม่ฟ้องมึงกลับหรอมึงเลยปล่อยหมาตายเป็นเรื่องเล่นอ่ะ?",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ แบงค์ !",
    type: "Life",
    soi: 1,
    print: "SD03-024",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไม่นะแบงค์! ไอ้แบงค์เป็นเพื่อนพี่สาวผมสมัยมหาลัยที่มักจะทำตัวน่าเกลียด แต่ทั้งหมดนั้นก็เพื่อสร้างเสียงหัวเราะเพื่อทุกคน และตอนนี้ ไม่มีใครขำแล้ว",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ พญายม !",
    type: "Life",
    soi: 1,
    print: "SD03-025",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "อันนี้ผมยินดีด้วย คุณเพิ่งฆ่าเผด็จการนรกที่ชอบใช้มาตราฐานตนเองมาตัดสินคนอื่น และตอนนี้นรกจะได้จัดการเลือกตั้งครั้งแรกตามวิถีประชาธิปไตย",
    dropRate: "1 / กล่อง",
  },
];
