import { Card } from "@/src/types/cards";

export const CARDS_SD04: Card[] = [
  {
    name: "กัปตันแบงค์ Tank Ranger",
    type: "Avatar",
    soi: 1,
    print: "SD04-001",
    rare: "SR",
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ลงสนามแบบจ่ายCost) : สอดแนม (แสดงการ์ดใบบนสุดของ Deck) 5 ใบ นำ \"จ่ามะนาว\" หรือ \"จ่าแดงเดือด\" จากที่ สอดแนม 1 มาสวมให้ Avatar รถถัง บน Avatar Zone ฝ่ายเรา 1 ใบ การ์ดที่เหลือเรียงและนำไว้ใต้ Deck\n\nเทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "คน",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "จ่ามะนาว Tank Ranger",
    type: "Avatar",
    soi: 1,
    print: "SD04-002",
    rare: "C",
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ลงสนามแบบจ่ายCost) ถ้ามี Avatar \"รถถัง\" บนสนามฝ่ายเรา สุ่มคว่ำ LIFE Card ฝ่ายเรา 1 ใบ\n\nเทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา\n\nเมื่อAvatar \"รถถัง\"ที่สวมใส่การ์ดใบนี้จะถูกทำลาย : ทำลายการ์ดใบนี้แทน",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "จ่าแดงเดือด Tank Ranger",
    type: "Avatar",
    soi: 1,
    print: "SD04-003",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้บน Avatar Zone ไปสวมให้ Avatar \"รถถัง\" ที่อยู่บน Avatar Zone ฝ่ายเรา\n\nAvatar รถถังที่สวมใบนี้ POWER +1\n\nสั่งใช้ เมื่อ Avatar ที่สวมใส่การ์ดนี้ทำลาย Avatar อีกฝ่ายจากการต่อสู้สำเร็จ ทำลายการ์ดใบนี้ที่สวมใส่อยู่  : Avatar ที่เคยสวมใส่การ์ดใบนี้จะกลับมาในสภาพตื่น",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "รถถัง \"Tank Ranger\"",
    type: "Avatar",
    soi: 1,
    print: "SD04-004",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง ถ้าไม่มี Avatar สวมใส่ Avatar ใบนี้ จะไม่สามารถโจมตีได้\n\nและไม่สามารถใช้ Avatar ชื่อซ้ำกันในการสวมใส่การ์ดใบนี้",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "หุ่นยนต์",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "MEGA ROR.DOR",
    type: "Avatar",
    soi: 1,
    print: "SD04-005",
    rare: "UR",
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ลงสนามแบบจ่ายCost) : นำ Avatar \"Tank Ranger\" จากใน Deck เรา 1 ใบ มาสวมใส่ให้กับ Avatar ใบนี้\n\n#Avatar ใบนี้ถือว่ามีชื่อ \"รถถัง\"",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "หุ่นยนต์",
    color: "เขียว",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "MEGA ROR.DOR",
    type: "Avatar",
    soi: 1,
    print: "SD04-005",
    rare: "PR",
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ลงสนามแบบจ่ายCost) : นำ Avatar \"Tank Ranger\" จากใน Deck เรา 1 ใบ มาสวมใส่ให้กับ Avatar ใบนี้\n\n#Avatar ใบนี้ถือว่ามีชื่อ \"รถถัง\"",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "หุ่นยนต์",
    color: "เขียว",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "MEGA ROR.DOR",
    type: "Avatar",
    soi: 1,
    print: "SD04-005",
    rare: "CBR",
    mainEffect:
      "จุติ (เมื่อ Avatar ตัวนี้ลงสนามแบบจ่ายCost) : นำ Avatar \"Tank Ranger\" จากใน Deck เรา 1 ใบ มาสวมใส่ให้กับ Avatar ใบนี้\n\n#Avatar ใบนี้ถือว่ามีชื่อ \"รถถัง\"",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "หุ่นยนต์",
    color: "เขียว",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "พลเอกปุ้มปุ้ย",
    type: "Avatar",
    soi: 1,
    print: "SD04-006",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 0,
    power: 0,
    symbol: "คน",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "สห ไล่จับเด็ก",
    type: "Avatar",
    soi: 1,
    print: "SD04-007",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "เขียว",
    dropRate: "4 / กล่อง",
  },
  {
    name: "อรุณีย์ ข้าวมันไก่เมียจ่า",
    type: "Avatar",
    soi: 1,
    print: "SD04-008",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "คน",
    color: "เขียว",
    dropRate: "4 / กล่อง",
  },
  {
    name: "พลทหาร",
    type: "Avatar",
    soi: 1,
    print: "SD04-009",
    rare: "C",
    mainEffect: "",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "คน",
    color: "เขียว",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ทหารฝูงบินต่ำ",
    type: "Avatar",
    soi: 1,
    print: "SD04-010",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "เขียว",
    dropRate: "4 / กล่อง",
  },
  {
    name: "คนจับใบดำ",
    type: "Avatar",
    soi: 1,
    print: "SD04-011",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "เขียว",
    dropRate: "4 / กล่อง",
  },
  {
    name: "คนจับใบแดง",
    type: "Avatar",
    soi: 1,
    print: "SD04-012",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 1,
    power: 1,
    symbol: "คน",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไอ้หนุ่มรด.",
    type: "Avatar",
    soi: 1,
    print: "SD04-013",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 0,
    symbol: "คน",
    color: "เขียว",
    dropRate: "3 / กล่อง",
  },
  {
    name: "รถถังลงถนน",
    type: "Magic",
    soi: 1,
    print: "SD04-014",
    rare: "SR",
    mainEffect: "อัญเชิญ Avatar \"รถถัง\" ที่มีค่า Cost ไม่เกิน 5 จาก Deck เราลงสนามฝั่งเรา 1 ตัว และ อีกฝ่ายอัญเชิญ Avatar ที่มีค่า Cost ไม่เกิน 5 จาก Deck อีกฝ่ายลงสนามอีกฝ่าย 1 ตัว",
    subtype: "Normal",
    cost: 2,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไอ นีด เมดิก",
    type: "Magic",
    soi: 1,
    print: "SD04-015",
    rare: "C",
    mainEffect: "สุ่มคว่ำ LIFE Card ของฝ่ายเราได้ 1 ใบ",
    subtype: "Normal",
    cost: 4,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ใบดำใบแดง",
    type: "Magic",
    soi: 1,
    print: "SD04-016",
    rare: "C",
    mainEffect: "สอดแนม 1 ใบ : ถ้าเป็น Avatar {Symbol : คน} Cost ไม่เกิน 3 ให้นำลงบน Avatar Zone ฝ่ายเรา แต่ถ้าไม่ใช่ให้ใส่ไว้ใต้ Deck",
    subtype: "Normal",
    cost: 1,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เพื่อชาติ",
    type: "Magic",
    soi: 1,
    print: "SD04-017",
    rare: "C",
    mainEffect: "เมื่ออีกฝ่ายประกาศโจมตี ทำลาย Avatar \"รถถัง\" บนสนามฝ่ายเรา 1 ใบ : ทำลาย Avatar ทั้งหมดบนสนามอีกฝ่าย",
    subtype: "React",
    cost: 3,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ขึ้นมาเร็ว ไอ้ลูกลิง !!",
    type: "Magic",
    soi: 1,
    print: "SD04-018",
    rare: "C",
    mainEffect: "เมื่อ Avatar รถถังเป็นเป้าโจมตี : สอดแนม (ดูการ์ดใบบนสุดของเด็ค) 5 ใบ เลือก Avatar {symbol คน} ที่ติดชื่อ \"Tank Ranger\" 1 ใบจากในนั้น ไปสวมใส่ให้ Avatar \"รถถัง\" บนสนามฝ่ายเรา และถ้านำการ์ดมาสวมใส่สำเร็จทำลาย Avatar ที่สั่งโจมตีนั้น",
    subtype: "React",
    cost: 3,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ถาดหลุม",
    type: "Magic",
    soi: 1,
    print: "SD04-019",
    rare: "C",
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง ใน Main phase เรา : ทอยเหรียญ ถ้าออกหัว Avatar ที่สวมใส่การ์ดใบนี้ POWER +2  , ถ้าออกก้อย Avatar ที่สวมการ์ดใบนี้ POWER -2",
    subtype: "Modification",
    cost: 2,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เขาชนไก่",
    type: "Magic",
    soi: 1,
    print: "SD04-020",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ ใน Main Phase สามารถเลือก Avatar {Symbol คน} บนสนามฝ่ายเรา 1 ใบ : เปลี่ยน Avatar ใบนั้นเป็นสภาพนอน หลังจากนั้น สอดแนม 1 ใบ และสามารถนำการ์ดใบนั้นไว้บนสุด หรือ ล่างสุด ของ Deckได้",
    subtype: "Land",
    cost: 1,
    symbol: "ทหาร",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม่นะ มะนาว !",
    type: "Life",
    soi: 1,
    print: "SD04-021",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "จ่ามะนาวคือตัวอย่างของสิ่งหายากในโลกที่เรียกว่าคนดี และคุณเพิ่งเลือกที่จะปล่อยคนดีสูญพันธุ์ไปต่อหน้าต่อต่อตา วันหลังมึงเอาปืนไปยิงเสือดำเหอะถ้ามึงจะมาลดประชากรคนดีในโลกเล่นๆอ่ะ",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ แดงเดือด !",
    type: "Life",
    soi: 1,
    print: "SD04-022",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "จ่าแดงเดือดไม่ได้ต้องการอะไรมากในชีวิต ขอแค่ประเทศชาติสงบเพื่อที่เพื่อนๆและครอบครัวของเขาจะมีกิน เขาก็พร้อมจะตายเพื่อชาติและพวกพ้องของเขา แต่แย่หน่อยที่แดงเดือดพลาดเองที่คิดว่าคุณเป็นเพื่อน",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ เจี๊ยบ !",
    type: "Life",
    soi: 1,
    print: "SD04-023",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "หลังจากที่เคยตัดยางโดดแฟนตัวเองสมัยเด็ก เจี๊ยบก็ได้เก็บความเจ็บปวดนี้มาตลอดและพอถึงเวลาที่เจี๊ยบรวมความกล้าจะไปบอกขอโทษ เขาก็ถูกเรียกตัวไปประจำการทหารบกและถูกครูฝึกซ้อมแต่ไม่ตาย….จนกระทั่งวันนี้",
    dropRate: "1 / กล่อง",
  },
  {
    name: "อ๋อ...ปุ้มปุ้ยตาย !",
    type: "Life",
    soi: 1,
    print: "SD04-024",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ก็  ตามที่เขียนอ่ะ… ปุ้มปุ้ยตายไง มามัวอ่านไร เล่นต่อดิวะเสียเวลาคนอื่น",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ พระอินทร์ !",
    type: "Life",
    soi: 1,
    print: "SD04-025",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "พระอินทร์คือเทพที่ถูกลืม เขาทำงาน เขาเก็บกวาดปัญหาบนโลกและสวรรค์นับไม่ถ้วน แต่สุดท้าย ก็ถูกจดจำว่าเป็นกระสอบทรายและตัวตลก นี้แหละปัญหาของการทำดีเป็นประจำ เพราะอะไรที่เป็นประจำ จะไม่มีใครเห็นค่ามัน",
    dropRate: "1 / กล่อง",
  },
];
