import { Card } from "@/src/types/cards";

export const CARDS_SD05: Card[] = [
  {
    name: "บึงทมิฬ  People - CEO คุณจิระ",
    type: "Avatar",
    soi: 1,
    print: "SD05-001",
    rare: "SR",
    mainEffect: "อัติโนมัติ เมื่อการ์ดใบนี้สั่งโจมตีหรือตกเป็นเป้าหมายการโจมตี : POWER ของการ์ดใบนี้จะเพิ่มขึ้นตาม Avatar ที่อยู่ในสภาพนอนบนสนามทั้ง 2 ฝ่าย ใบละ 1 จนจบเทิร์น",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "บึงทมิฬ  People - คุณเค้นท์",
    type: "Avatar",
    soi: 1,
    print: "SD05-002",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ เมื่อ Avatar ใบนี้สั่งโจมตีและไม่ถูกทำลายจากการต่อสู้\n\nถ้าบน Avatar Zone ฝ่ายเรา มี Avatar \"บึงทมิฬ People\" ใบอื่น : ทอยลูกเต๋า 1 ครั้ง\n\nถ้าผลออกมาเป็นเลขคี่ หลังจากจบการต่อสู้ของการ์ดใบนี้ นำการ์ดใบนี้ที่อยู่สภาพนอนเปลี่ยนเป็นสภาพตื่น",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "บึงทมิฬ  People - คุณฮาร์วี่",
    type: "Avatar",
    soi: 1,
    print: "SD05-003",
    rare: "C",
    mainEffect: "จุติ : แสดงการ์ดจากล่างสุดของ Deck ตามจำนวน Avatar ที่อยู่ในสภาพนอนทั้งสนาม เลือก Avatar Symbol {ปลา} 1 ใบจากที่แสดงนำขึ้นมือ จากนั้นนำการ์ดที่เหลือกลับ Deck แล้วสับ",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "บึงทมิฬ  People - คุณอังคณา",
    type: "Avatar",
    soi: 1,
    print: "SD05-004",
    rare: "C",
    mainEffect:
      "\"โล่มนุษย์\"\n\nอัติโนมัติ เมื่อการ์ดใบนี้ใช้ความสามารถ \"โล่มนุษย์\" POWER+2 จนจบการต่อสู้นั้น",
    cost: 2,
    gem: 1,
    power: 1,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "บึงทมิฬ  People - คุณพยาบาล",
    type: "Avatar",
    soi: 1,
    print: "SD05-005",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เปลี่ยนการ์ดใบนี้จากสภาพตื่นเป็นสภาพนอน เลือก Avatar \"บึงทมิฬ People\" ใบอื่นบนสนามฝ่ายเรา 1 ใบ : Avatar ใบที่เลือก จะไม่ถูกทำลาย 1 ครั้ง จนจบเทิร์นถัดไปของฝ่ายตรงข้าม",
    cost: 1,
    gem: 1,
    power: 1,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "วอเตอร์แมน",
    type: "Avatar",
    soi: 1,
    print: "SD05-006",
    rare: "UR",
    mainEffect:
      "จุติ : อัญเชิญ \"บึงทมิฬ  People\" จากใน Deck เรา 2 ใบ ในสภาพนอน แต่ถ้า Land Magic Zone มี \"บึงทมิฬ\" ให้เปลี่ยนเป็นสภาพตื่นแทน จากนั้นสับ Deck\n\nต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่ในสนาม จะนับว่าเป็น \"บึงทมิฬ People\" ด้วย\n\n#Avatar ใบนี้นับเป็น Symbol ปลา",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "วอเตอร์แมน",
    type: "Avatar",
    soi: 1,
    print: "SD05-006",
    rare: "PR",
    mainEffect:
      "จุติ : อัญเชิญ \"บึงทมิฬ  People\" จากใน Deck เรา 2 ใบ ในสภาพนอน แต่ถ้า Land Magic Zone มี \"บึงทมิฬ\" ให้เปลี่ยนเป็นสภาพตื่นแทน จากนั้นสับ Deck\n\nต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่ในสนาม จะนับว่าเป็น \"บึงทมิฬ People\" ด้วย\n\n#Avatar ใบนี้นับเป็น Symbol ปลา",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "วอเตอร์แมน",
    type: "Avatar",
    soi: 1,
    print: "SD05-006",
    rare: "CBR",
    mainEffect:
      "จุติ : อัญเชิญ \"บึงทมิฬ  People\" จากใน Deck เรา 2 ใบ ในสภาพนอน แต่ถ้า Land Magic Zone มี \"บึงทมิฬ\" ให้เปลี่ยนเป็นสภาพตื่นแทน จากนั้นสับ Deck\n\nต่อเนื่อง ตราบเท่าที่ Avatar ใบนี้อยู่ในสนาม จะนับว่าเป็น \"บึงทมิฬ People\" ด้วย\n\n#Avatar ใบนี้นับเป็น Symbol ปลา",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "ฟ้า",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "บึงทมิฬ People - คุณบึกบึน",
    type: "Avatar",
    soi: 1,
    print: "SD05-007",
    rare: "C",
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ปลาชโด กรามกุด",
    type: "Avatar",
    soi: 1,
    print: "SD05-008",
    rare: "C",
    mainEffect: "",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ปลาดาวกระจาย",
    type: "Avatar",
    soi: 1,
    print: "SD05-009",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "กระเบนหางแหลมมาก",
    type: "Avatar",
    soi: 1,
    print: "SD05-010",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "พิธีกรสารคดีดวงโบ๋",
    type: "Avatar",
    soi: 1,
    print: "SD05-011",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 1,
    power: 2,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ปลาแบงค์",
    type: "Avatar",
    soi: 1,
    print: "SD05-012",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "ปลา",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "เหยื่อปลอม",
    type: "Avatar",
    soi: 1,
    print: "SD05-013",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "หุ่นยนต์",
    color: "ฟ้า",
    dropRate: "4 / กล่อง",
  },
  {
    name: "บึงทมิฬ",
    type: "Magic",
    soi: 1,
    print: "SD05-014",
    rare: "SR",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เลือก Avatar 1 ใบ ใน Avatar Zone ฝ่ายเรา เปลี่ยนสภาพ Avatar ใบนั้นเป็นสภาพนอน : จั่วการ์ด 1 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "ปลา",
    dropRate: "2 / กล่อง",
  },
  {
    name: "กำเนิดจากน้ำ",
    type: "Magic",
    soi: 1,
    print: "SD05-015",
    rare: "C",
    mainEffect:
      "เลือก Avatar Symbol ปลาในนรกเรา 1 ใบ  : อัญเชิญลงบน Avatar Zone ฝ่ายเราในสภาพนอน\n\nถ้าบนสนามมี Land Magic \"บึงทมิฬ\" อัญเชิญลงบนสนามในสภาพตื่น",
    subtype: "Normal",
    cost: 2,
    symbol: "ปลา",
    dropRate: "2 / กล่อง",
  },
  {
    name: "น้ำวนชักโครก",
    type: "Magic",
    soi: 1,
    print: "SD05-016",
    rare: "C",
    mainEffect: "เมื่อ Avatar \"บึงทมิฬ People\" เป็นเป้าหมายการโจมตี : ยกเลิกการโจมตีนั้น และเปลี่ยน สภาพ Avatar ทุกใบบนสนาม ยกเว้น Avatar ใบที่สั่งโจมตี",
    subtype: "React",
    cost: 0,
    symbol: "ปลา",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ปืนฉมวก",
    type: "Magic",
    soi: 1,
    print: "SD05-017",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"บึงทมิฬ People\" เท่านั้น\n\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้ โจมตีใส่ Avatar ที่อยู่ในสภาพนอน : เพิ่ม POWER ให้ Avatar ที่สวมใส่การ์ดใบนี้ 1 และ ลด POWER ของ Avatar ตัวที่เป็นเป้าหมายโจมตี 1",
    subtype: "Modification",
    cost: 2,
    symbol: "ปลา",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ตรีศูล ไตรตัน",
    type: "Magic",
    soi: 1,
    print: "SD05-018",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"บึงทมิฬ People\" เท่านั้น\n\nสั่งใช้ ถ้าในเทิร์นนี้ยังไม่ได้ใช้การ์ด Land Magic ส่งการ์ดใบนี้ในสภาพสวมใส่ลงนรก : เลือก Land Magic \"บึงทมิฬ\" จากใน Deck 1 ใบ มาวางไว้บน Land Magic Zone ความสามารถนี้นับเป็นการใช้ Land Magic",
    subtype: "Modification",
    cost: 1,
    symbol: "ปลา",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ประมาทร่วม",
    type: "Magic",
    soi: 1,
    print: "SD05-019",
    rare: "C",
    mainEffect: "ผู้เล่นทุกคน ธรณีสูบ (ส่งการ์ดใบบนสุดจาก Deck ตกนรก) 3 ใบ",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ชายจากอนาคต",
    type: "Magic",
    soi: 1,
    print: "SD05-020",
    rare: "C",
    mainEffect: "เมื่อมีการใช้ Magic Card : ยกเลิกการใช้ Magic Card ใบนั้น",
    subtype: "Normal",
    cost: 0,
    symbol: "จอมเวทย์",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ กัปตันไกร !",
    type: "Life",
    soi: 1,
    print: "SD05-021",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "กัปตันไกร ชายผู้เสียแทบจะทุอย่างในชีวิตให้กับเจ้าปลาชะโดกรามกุดที่ชั่วร้าย แต่ต่อให้ต้องสูญเสียมากแค่ไหนสิ่งที่ชะโดไม่เคยเอาไปจากกัปตันไกรก็คือ \" ชีวิต \"\n\nสรุปง่ายๆคือ คุณเลวกว่าไอ้ชะโดที่แดกขาคนแก่พิการอีก",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ มาวิน !",
    type: "Life",
    soi: 1,
    print: "SD05-022",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "มาวินเป็นแค่ชาวประมงที่โหยหาความรัก เขาอยู่ทะเลมาครึ่งชีวิตและ ได้พบกับนางเงือกสาวแสนสวย พวกเขากำลังจะแต่งงานกันในวันพุธนี้ และทายซืใครจะไม่ได้ไปสวมแหวนให้เจ้าสาวในวันแต่งงาน ชื่อของเขาคือ \" มาวิน \"",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ วอเตอร์แมน !",
    type: "Life",
    soi: 1,
    print: "SD05-023",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "\"\" ไม่นะวอเตอร์แมน \"\" นี่ไม่ใช่คำพูดที่ใช้แสดงความเสียใจ แต่เป็นคำที่พูดด้วยความหวาดกลัวตอนวอเตอร์แมนบุกเข้าห้องนอนคุณตอนตีสอง เพราะคุณกำลังจะซวยที่หงายการ์ดวอเตอร์แมน\n\nและวอเตอร์แมนจะไปเล่นคุณตอนมึงหลับ",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ คุณจิระ !",
    type: "Life",
    soi: 1,
    print: "SD05-024",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "คุณพึ่งปล่อยคุณจิระ วาฬที่ซื่อสัตว์ สวยงามซึ่งก็มีไม่มากแล้วบนน่านน้ำมหาสมุทรอันกว้างใหญ่ นับเป็นเรื่องน่าเศร้ามากจริงๆ อ้อใช่ อ่ะนี่คำถามประจำวัน รู้หรือไม่\n\nวาฬไม่ใช่ปลา แต่เป็นสัตว์เลี้ยงลูกด้วยนม และ รู้ไหมอะไรเลี้ยงลูกด้วยนมอีก? แม่มึง..",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ไตรตั้น !",
    type: "Life",
    soi: 1,
    print: "SD05-025",
    rare: "C",
    mainEffect: "เมื่อการ์ดใบนี้ถูกหงายจากการโจมตี : ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "ไตรตั้นคือราชาแห่งท้องทะเล และเมื่อไม่มีเขา พวกสัตว์ทะเลทุกตัวก็บ้าคลั่งแย่งกันเป็นราชาคนต่อไป จนสุดท้ายปลาก็จะฆ่ากันเองจนตายหมดทะเลแล้วก็ไม่มีซีฟู้ดแดกอีกต่อไป...และกูไม่ชอบเลย",
    dropRate: "1 / กล่อง",
  },
];
