import { Card } from "@/src/types/cards";

export const CARDS_SD06: Card[] = [
  {
    name: "จัน หนวดเขี้ยว",
    type: "Avatar",
    soi: 2,
    print: "SD06-001",
    rare: "UR",
    mainEffect:
      "ลูกฮึด\n\nถ้าอยู่ใน สถานะสาหัส Avatar ใบนี้ POWER +1\n\nต่อเนื่อง Avatar ใบนี้ไม่สามารถถูกเปลี่ยนการควบคุมได้\n\nอัตโนมัติ ถ้าเราควบคุม \"ค่ายบางระจัน\" เมื่อ Avatar ใบนี้ถูกทำลาย : นำ Avatar ใบนี้กลับเข้า Deck แล้วสับ จากนั้นจั่วการ์ดจาก Deck 1 ใบ",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "แดง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "จัน หนวดเขี้ยว",
    type: "Avatar",
    soi: 2,
    print: "SD06-001",
    rare: "PR",
    mainEffect:
      "ลูกฮึด\n\nถ้าอยู่ใน สถานะสาหัส Avatar ใบนี้ POWER +1\n\nต่อเนื่อง Avatar ใบนี้ไม่สามารถถูกเปลี่ยนการควบคุมได้\n\nอัตโนมัติ ถ้าเราควบคุม \"ค่ายบางระจัน\" เมื่อ Avatar ใบนี้ถูกทำลาย : นำ Avatar ใบนี้กลับเข้า Deck แล้วสับ จากนั้นจั่วการ์ดจาก Deck 1 ใบ",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "แดง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "จัน หนวดเขี้ยว",
    type: "Avatar",
    soi: 2,
    print: "SD06-001",
    rare: "CBR",
    mainEffect:
      "ลูกฮึด\n\nถ้าอยู่ใน สถานะสาหัส Avatar ใบนี้ POWER +1\n\nต่อเนื่อง Avatar ใบนี้ไม่สามารถถูกเปลี่ยนการควบคุมได้\n\nอัตโนมัติ ถ้าเราควบคุม \"ค่ายบางระจัน\" เมื่อ Avatar ใบนี้ถูกทำลาย : นำ Avatar ใบนี้กลับเข้า Deck แล้วสับ จากนั้นจั่วการ์ดจาก Deck 1 ใบ",
    cost: 6,
    gem: 3,
    power: 6,
    symbol: "คน",
    color: "แดง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "อิน สไนเปอร์",
    type: "Avatar",
    soi: 2,
    print: "SD06-002",
    rare: "C",
    mainEffect:
      "เตะไข่\n\nต่อเนื่อง เมื่อ Avatar ใบนี้ใช้ความสามารถ เตะไข่ : ทำลาย Avatar 1 ใบบน Avatar Zone ฝ่ายเรา\n\nต่อเนื่อง ตราบเท่าที่เราควบคุม \"ค่ายบางระจัน\" Avatar ใบนี้ POWER +2",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ทองเหม็น ขวานคลั่ง",
    type: "Avatar",
    soi: 2,
    print: "SD06-003",
    rare: "SR",
    mainEffect:
      "อัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : POWER +2 จนจบเทิร์น\n\nต่อเนื่อง ตราบเท่าที่เราไม่ได้ควบคุม \"ค่ายบางระจัน\" บน Construct Zone Avatar ใบนี้ไม่สามารถโจมตี LIFE Card ได้",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "คน",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เมือง ช่างใหญ่",
    type: "Avatar",
    soi: 2,
    print: "SD06-004",
    rare: "C",
    mainEffect: "จุติ ทิ้งการ์ดบนมือ 2 ใบ : ก่อสร้าง Construct Card \"ค่ายบางระจัน\" 1 ใบ จาก Deck เรา จากนั้นสับ Deck",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "คน",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "พันเรือง ผู้พิทักษ์ไร้พ่าย",
    type: "Avatar",
    soi: 2,
    print: "SD06-005",
    rare: "C",
    mainEffect:
      "โล่มนุษย์\n\nต่อเนื่อง POWER +2 ในเทิร์นฝ่ายตรงข้าม\n\nต่อเนื่อง ตราบเท่าที่เราควบคุม \"ค่ายบางระจัน\" เมื่อ Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ใบอื่นบน Avatar Zone จะถูกทำลาย สามารถทำลายการ์ดใบนี้จากบนสนามแทนได้",
    cost: 4,
    gem: 3,
    power: 2,
    symbol: "คน",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "พ่อแท่น ผู้นำอาวุโส",
    type: "Avatar",
    soi: 2,
    print: "SD06-006",
    rare: "C",
    mainEffect: "คำสั่งเสีย : สอดแนม 5 ใบ เลือก Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box 1 ใบ ยกเว้น พ่อแท่น ผู้นำอาวุโส ขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ",
    cost: 3,
    gem: 1,
    power: 2,
    symbol: "คน",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "อาจารย์ธรรมโชติ",
    type: "Avatar",
    soi: 2,
    print: "SD06-007",
    rare: "C",
    mainEffect: "เทิร์นละครั้ง สั่งใช้ เมื่อ Construct \"ค่ายบางระจัน\" จะถูกทำลายจากความสามารถของ Avatar หรือ การ์ด Magic ส่งการ์ดใบนี้จากบนมือหรือ Avatar Zone กลับเข้าใต้ Deck : \"ค่ายบางระจัน\" จะไม่ถูกทำลายจาก ความสามารถของ Avatar หรือ การ์ด Magic",
    cost: 1,
    gem: 3,
    power: 1,
    symbol: "คน",
    color: "แดง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "บุญช่วย ควายรักชาติ",
    type: "Avatar",
    soi: 2,
    print: "SD06-008",
    rare: "C",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : นำ Avatar ใบนี้ ไปสวมใส่ให้ Avatar ใบอื่นบน Avatar Zone ฝ่ายเรา Avatar ที่สวมใส่การ์ดใบนี้ POWER +1\n\nตราบเท่าที่เราควบคุม \"ค่ายบางระจัน\" Avatar ที่สวมใส่ การ์ดใบนี้ POWER +2 แทนการ POWER +1",
    cost: 2,
    gem: 2,
    power: 2,
    symbol: "สัตว์",
    color: "แดง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "พม่าข้าศึก 2310",
    type: "Avatar",
    soi: 2,
    print: "SD06-009",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 0,
    power: 4,
    symbol: "ต่างชาติ",
    color: "แดง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "วีรชน แบงค์",
    type: "Avatar",
    soi: 2,
    print: "SD06-010",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 0,
    power: 3,
    symbol: "คน",
    color: "ม่วง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ลูก เมีย",
    type: "Avatar",
    soi: 2,
    print: "SD06-011",
    rare: "C",
    mainEffect: "",
    cost: 1,
    gem: 4,
    power: 1,
    symbol: "คน",
    color: "แดง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ผู้นำของเหล่าวีรชน",
    type: "Magic",
    soi: 2,
    print: "SD06-012",
    rare: "C",
    mainEffect: "ทิ้งการ์ดบนมือ 2 ใบ : เลือก Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box จากใน Deck เรา 1 ใบ ขึ้นมือ จากนั้นสับ Deck",
    subtype: "Normal",
    cost: 4,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "วิญญาณวีรชน",
    type: "Magic",
    soi: 2,
    print: "SD06-013",
    rare: "C",
    mainEffect:
      "ทิ้งการ์ดบนมือ 1 ใบ : อัญเชิญ จุติ Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box จากในนรกเรา 1 ใบ ลงบน Avatar Zone ฝ่ายเรา\n\nเมื่อจบเทิร์นถัดไปของฝ่ายตรงข้าม ส่ง Avatar ที่อัญเชิญด้วยความสามารถนี้ลงนรก",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ไปเลยมอนตี้",
    type: "Magic",
    soi: 1,
    print: "SD06-014",
    rare: "C",
    mainEffect: "เมื่อ Avatar อีกฝ่ายประกาศโจมตี : Avatar ที่โจมตี POWER ลดลงตามจำนวนการ์ดบนสนามและบนมือฝั่งเราใบละ 2",
    subtype: "Normal",
    cost: 1,
    symbol: "สัตว์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ปืนใหญ่ไทยประดิษฐ์",
    type: "Magic",
    soi: 2,
    print: "SD06-015",
    rare: "C",
    mainEffect:
      "เมื่อฝ่ายตรงข้ามอัญเชิญ Avatar และเราควบคุม Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box\n\nเลือก Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ของเรา 1 ใบ และ Avatar ของฝ่ายตรงข้าม 1 ใบ : ทำลาย Avatar ที่เลือกทั้ง 2 ใบ",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ยันต์ผ้าประเจียด",
    type: "Magic",
    soi: 2,
    print: "SD06-016",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box เท่านั้น\n\nAvatar ที่สวมใส่การ์ดใบนี้ได้รับความสามารถ ลูกฮึด",
    subtype: "Modification",
    cost: 3,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ดาบใบข้าว X",
    type: "Magic",
    soi: 2,
    print: "SD06-017",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box  เท่านั้น\n\nเมื่อ Avatar ที่สวมใส่การ์ดใบนี้ทำลาย Avatar ฝ่ายตรงข้ามสำเร็จ : จั่วการ์ด 1 ใบ",
    subtype: "Modification",
    cost: 3,
    symbol: "ต้นไม้",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ค่ายบางระจัน",
    type: "Construct",
    soi: 2,
    print: "SD06-018",
    rare: "SR",
    mainEffect:
      "ต่อเนื่อง ตราบเท่าที่การ์ดใบนี้อยู่บน Construct Zone ฝ่ายเรา Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box ทุกใบ POWER +1 และได้รับความสามารถ \"โล่มนุษย์\" และ \"สามัคคี\"\n\nเมื่อการ์ดใบนี้ถูกทำลาย ส่ง Avatar ทุกใบบน Avatar Zone ฝ่ายเรา ลงนรก",
    cost: 4,
    gem: 0,
    power: 6,
    symbol: "สิ่งก่อสร้าง",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "วัดคู่บ้านคู่เมือง",
    type: "Construct",
    soi: 2,
    print: "SD06-019",
    rare: "C",
    mainEffect: "ต่อเนื่อง ตราบเท่าที่การ์ดใบนี้อยู่บน Construct Zone ฝ่ายเรา ความสามารถ สอดแนม ของ Construct ฝ่ายเรา เพิ่มขึ้น 2 ใบ",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "สิ่งก่อสร้าง",
    color: "แดง",
    dropRate: "1 / กล่อง",
  },
  {
    name: "กำแพงด่านสุดท้าย",
    type: "Construct",
    soi: 2,
    print: "SD06-020",
    rare: "C",
    mainEffect: "อัตโนมัติ เทิร์นละครั้ง เมื่อ LIFE Card ของเราถูกหงาย และบน Avatar Zone ฝ่ายเรา ไม่มี Avatar อยู่ ทิ้งการ์ดบนมือ 1 ใบ : สอดแนม 1 ใบ ถ้าการ์ดเหล่านั้นเป็น Avatar ที่มี \"ค่ายบางระจัน\" อยู่ใน Text Box และ Cost ไม่เกิน 4 อัญเชิญ Avatar เหล่านั้น ลงบน Avatar Zone ฝ่ายเรา ถ้าไม่ใช่นำการ์ดเหล่านั้นขึ้นมือ",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "สิ่งก่อสร้าง",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม่นะ จัน!",
    type: "Life",
    soi: 2,
    print: "SD06-021",
    rare: "C",
    mainEffect: "ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ทองเหม็น!",
    type: "Life",
    soi: 2,
    print: "SD06-022",
    rare: "C",
    mainEffect: "ในช่วงเริ่มต้น Battle Phase ถัดไป Construct ทุกใบ บน Construct Zone ฝ่ายเรา POWER+1",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ บุญช่วย!",
    type: "Life",
    soi: 2,
    print: "SD06-023",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป นำ Construct 1 ใบ จาก นรกฝ่ายเราขึ้นมือ",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ท่านผู้นำตายแล้ว!",
    type: "Life",
    soi: 2,
    print: "SD06-024",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป สอดแนม 5 ใบ นำ Construct 1 ใบ จากที่สอดแนม ขึ้นมือ นำการ์ดที่เหลือเรียงแล้วนำไปไว้ใต้ Deck",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ลูก เมีย กู!!!",
    type: "Life",
    soi: 2,
    print: "SD06-025",
    rare: "C",
    mainEffect: "ใน main phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
];
