import { Card } from "@/src/types/cards";

export const CARDS_SD07: Card[] = [
  {
    name: "กวนอู ขุนพลภักดีแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SD07-001",
    rare: "SR",
    mainEffect:
      "ลูกฮึด\n\nต่อเนื่อง Avatar ใบนี้ไม่สามารถเปลี่ยนการควบคุมได้\n\nต่อเนื่อง ผู้เล่นฝ่ายตรงข้าม ไม่สามารถเลือกเป้าหมายของความสามารถการ์ดไปที่ Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ ฝ่ายเราได้ ยกเว้น \"กวนอู ขุนพลภักดีแห่งจ๊กก๊ก\"",
    cost: 4,
    gem: 1,
    power: 4,
    symbol: "ต่างชาติ",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เตียวหุย ขุนพลจอมบุกแห่งจ๊กก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SD07-002",
    rare: "C",
    mainEffect: "อัตโนมัติ เมื่อ Avatar ใบนี้ โจมตี : POWER +1",
    cost: 5,
    gem: 2,
    power: 4,
    symbol: "ต่างชาติ",
    color: "เขียว",
    dropRate: "2 / กล่อง",
  },
  {
    name: "แฮหัวตุ้น ขุนพลตาเดียวแห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SD07-003",
    rare: "C",
    mainEffect: "อัตโนมัติ เมื่อการ์ดใบนี้ถูกอัญเชิญมาด้วยความสามารถของ Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ : ทำลายการ์ดบนสนาม 1 ใบ",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "แฮหัวเอี๋ยน ขุนพลธนูแห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SD07-004",
    rare: "C",
    mainEffect:
      "แทงหลัง (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอน และนำ POWER การ์ดนี้ +1 ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น เมื่อจบการต่อสู้ ถ้า Avatar ที่สั่งโจมตี มีสีต่างกับ Avatar นี้ ทำลาย Avatar ที่สั่งโจมตี)\n\nอัตโนมัติ เมื่อการ์ดใบนี้ถูกอัญเชิญมาด้วยความสามารถของ Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ : จั่วการ์ด 1 ใบ",
    cost: 3,
    gem: 3,
    power: 1,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ซุนเกี๋ยน ขุนพลพยัคฆ์แห่งง่อก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SD07-005",
    rare: "C",
    mainEffect:
      "โล่มนุษย์\n\nคำสั่งเสีย : เลือก Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ 1 ใบ บน Avatar Zone ฝ่ายเรา Avatar ใบที่เลือก POWER +2 จนจบเทิร์นถัดไปของฝ่ายตรงข้าม",
    cost: 4,
    gem: 2,
    power: 3,
    symbol: "ต่างชาติ",
    color: "แดง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ซุนเซ็ก ขุนพลไฟแรงแห่งง่อก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SD07-006",
    rare: "C",
    mainEffect:
      "แทงหลัง (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอน และนำ POWER การ์ดนี้ +1 ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น เมื่อจบการต่อสู้ ถ้า Avatar ที่สั่งโจมตี มีสีต่างกับ Avatar นี้ ทำลาย Avatar ที่สั่งโจมตี)\n\nอัตโนมัติ เทิร์นละครั้ง เมื่อการ์ดใบนี้ใช้ความสามารถ แทงหลัง ให้ Avatar สีแดง : เปลี่ยน Avatar ใบนี้จากสภาพนอนเป็นสภาพตื่น",
    cost: 3,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "แดง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "ลิโป้ ขุนพลเทพสงคราม",
    type: "Avatar",
    soi: 2,
    print: "SD07-007",
    rare: "UR",
    mainEffect:
      "ต่อเนื่อง ในช่วง Battle Phase Avatar ฝ่ายตรงข้ามทุกใบได้รับ โล่มนุษย์\n\nอัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามจะต้องใช้ความสามารถ โล่มนุษย์ เสมอ\n\nอัตโนมัติ ในเทิร์นฝ่ายเรา เมื่อมีการเปลี่ยนเป้าหมายการโจมตี : สามารถทำลาย Avatar ฝ่ายตรงข้าม 1 ใบ",
    cost: 8,
    gem: 0,
    power: 7,
    symbol: "ต่างชาติ",
    color: "ม่วง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ลิโป้ ขุนพลเทพสงคราม",
    type: "Avatar",
    soi: 2,
    print: "SD07-007",
    rare: "PR",
    mainEffect:
      "ต่อเนื่อง ในช่วง Battle Phase Avatar ฝ่ายตรงข้ามทุกใบได้รับ โล่มนุษย์\n\nอัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามจะต้องใช้ความสามารถ โล่มนุษย์ เสมอ\n\nอัตโนมัติ ในเทิร์นฝ่ายเรา เมื่อมีการเปลี่ยนเป้าหมายการโจมตี : สามารถทำลาย Avatar ฝ่ายตรงข้าม 1 ใบ",
    cost: 8,
    gem: 0,
    power: 7,
    symbol: "ต่างชาติ",
    color: "ม่วง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ลิโป้ ขุนพลเทพสงคราม",
    type: "Avatar",
    soi: 2,
    print: "SD07-007",
    rare: "CBR",
    mainEffect:
      "ต่อเนื่อง ในช่วง Battle Phase Avatar ฝ่ายตรงข้ามทุกใบได้รับ โล่มนุษย์\n\nอัตโนมัติ เมื่อ Avatar ใบนี้โจมตี : ฝ่ายตรงข้ามจะต้องใช้ความสามารถ โล่มนุษย์ เสมอ\n\nอัตโนมัติ ในเทิร์นฝ่ายเรา เมื่อมีการเปลี่ยนเป้าหมายการโจมตี : สามารถทำลาย Avatar ฝ่ายตรงข้าม 1 ใบ",
    cost: 8,
    gem: 0,
    power: 7,
    symbol: "ต่างชาติ",
    color: "ม่วง",
    ex: "Only #1",
    dropRate: "1 / กล่อง",
  },
  {
    name: "อ้วนเสี้ยว ผู้นำขุนพล 18 หัวเมือง",
    type: "Avatar",
    soi: 2,
    print: "SD07-008",
    rare: "C",
    mainEffect:
      "แทงหลัง (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอน และนำ POWER การ์ดนี้ +1 ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น เมื่อจบการต่อสู้ ถ้า Avatar ที่สั่งโจมตี มีสีต่างกับ Avatar นี้ ทำลาย Avatar ที่สั่งโจมตี)\n\nจุติ : สอดแนม 3 ใบ เลือก Avatar \"ขุนพล\" ที่เป็น Avatar {symbol ต่างชาติ} 1 ใบ จากที่สอดแนม และนำขึ้นมือ ถ้า Avatar ใบที่เลือกเป็น Avatar สีฟ้า สามารถอัญเชิญ Avatar ใบนั้น ลงบน Avatar Zone ฝ่ายเราแทนได้ การ์ดที่เหลือนำกลับ Deck แล้วสับ",
    cost: 5,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ขุนศึกแบงค์ แซ่อู๋",
    type: "Avatar",
    soi: 2,
    print: "SD07-009",
    rare: "C",
    mainEffect: "แทงหลัง (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอนบน และนำ POWER การ์ดนี้ +1 ไปเพิ่มให้กับ  Avatar ที่สั่งโจมตี จนจบการต่อสู้นั้น เมื่อจบการต่อสู้ ถ้า Avatar ที่สั่งโจมตี มีสีต่างกับ Avatar นี้ ทำลาย Avatar ที่สั่งโจมตี)",
    cost: 4,
    gem: 2,
    power: 2,
    symbol: "ต่างชาติ",
    color: "ม่วง",
    dropRate: "3 / กล่อง",
  },
  {
    name: "พลเดินทัพ",
    type: "Avatar",
    soi: 2,
    print: "SD07-010",
    rare: "C",
    mainEffect: "",
    cost: 2,
    gem: 3,
    power: 2,
    symbol: "ต่างชาติ",
    color: "แดง",
    dropRate: "4 / กล่อง",
  },
  {
    name: "พลเสบียง",
    type: "Avatar",
    soi: 2,
    print: "SD07-011",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 4,
    power: 0,
    symbol: "สัตว์",
    color: "เขียว",
    dropRate: "4 / กล่อง",
  },
  {
    name: "ชาวบ้านจ้าน",
    type: "Avatar",
    soi: 2,
    print: "SD07-012",
    rare: "C",
    mainEffect: "",
    cost: 0,
    gem: 1,
    power: 1,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
    dropRate: "3 / กล่อง",
  },
  {
    name: "คำสาบานสวนท้อ",
    type: "Magic",
    soi: 2,
    print: "SD07-013",
    rare: "SR",
    mainEffect:
      "เลือกปฏิบัติ :\n\n1) เลือก Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ 1 ใบ บน Avatar Zone ฝ่ายเรา นำ Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ ที่ไม่ใช่ Only #1 1 ใบ จาก Deck เรา ที่มีสีเดียวกันกับ Avatar ที่เลือก แต่คนละชื่อกัน ขึ้นมือ จากนั้นสับ Deck\n\n2) เลือก Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ 2 ใบ บน Avatar Zone ฝ่ายเรา ที่มีสีเดียวกัน แต่ชื่อไม่ซ้ำกัน นำ Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ และเป็น Only #1 1 ใบ จาก Deck เรา ที่มีสีเดียวกันกับ Avatar ที่เลือก ขึ้นมือ จากนั้นสับ Deck",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ยืมมือสังหาร",
    type: "Magic",
    soi: 1,
    print: "SD07-014",
    rare: "C",
    mainEffect:
      "สามารถใช้การ์ดใบนี้ได้เมื่อ Avatar Zone ฝ่ายเรามี Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ เท่านั้น\n\nทิ้งการ์ดบนมือ 1 ใบ เลือก Avatar 1 ใบ ของฝ่ายตรงข้าม ที่มี Modification Magic ของฝ่ายตรงข้ามสวมใส่อยู่ : เปลี่ยนการควบคุม Avatar ใบที่เลือก มาบน Avatar Zone ฝ่ายเรา จนจบเทิร์น และเปลี่ยนเป็นสภาพตื่น Avatar ใบที่เลือก จะไม่สามารถโจมตีไปที่ LIFE Card ได้",
    subtype: "Normal",
    cost: 0,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เสบียงหลวง",
    type: "Magic",
    soi: 2,
    print: "SD07-015",
    rare: "C",
    mainEffect:
      "ผู้เล่นทุกคน จั่วการ์ด 1 ใบ\n\nถ้าบน Avatar Zone ฝ่ายเรามี \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ ตั้งแต่ 2 ใบขึ้นไป เปลี่ยนความสามารถการ์ดใบนี้เป็น\n\nจั่วการ์ด 2 ใบ จาก Deck เรา",
    subtype: "Normal",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "4 / กล่อง",
  },
  {
    name: "หนีคือยอดกลยุทธ์",
    type: "Magic",
    soi: 2,
    print: "SD07-016",
    rare: "C",
    mainEffect: "เมื่อ Avatar ฝ่ายเรา ถูกโจมตี : นำ Avatar ใบที่ถูกโจมตี กลับขึ้นมือ",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "หมอมาแล้วววว",
    type: "Magic",
    soi: 2,
    print: "SD07-017",
    rare: "C",
    mainEffect: "เมื่อ Avatar บนสนามจะถูกทำลาย : Avatar ใบนั้นจะไม่ถูกทำลาย",
    subtype: "React",
    cost: 3,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ง้าวมังกรเขียว",
    type: "Magic",
    soi: 2,
    print: "SD07-018",
    rare: "C",
    mainEffect:
      "สวมใส่ได้เฉพาะ Avatar \"ขุนพล\" ที่เป็น Symbol ชาวต่างชาติ เท่านั้น\n\nAvatar ที่สวมใส่การ์ดใบนี้ POWER +1 ถ้า Avatar ที่สวมใส่การ์ดใบนี้คือ \"กวนอู\" POWER +2 แทน",
    subtype: "Modification",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "เมืองลกเอี๋ยง",
    type: "Magic",
    soi: 2,
    print: "SD07-019",
    rare: "C",
    mainEffect: "หากบน Avatar Zone ฝ่ายเรามี Avatar 4 สี ขึ้นไป Avatar ทุกใบบน Avatar Zone ฝ่ายเรา POWER +2",
    subtype: "Land",
    cost: 2,
    symbol: "จอมเวทย์",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ด่านเฮาโลก๋วน",
    type: "Construct",
    soi: 2,
    print: "SD07-020",
    rare: "C",
    mainEffect:
      "ต่อเนื่อง ผู้เล่นฝ่ายตรงข้ามไม่สามารถใช้ ความสามารถ สามัคคี ได้\n\nต่อเนื่อง Avatar \"ขุนพล\" สีม่วง บน Avatar Zone ฝ่ายเรา ทุกใบ POWER +1",
    cost: 4,
    gem: 1,
    power: 3,
    symbol: "สิ่งก่อสร้าง",
    color: "ม่วง",
    dropRate: "2 / กล่อง",
  },
  {
    name: "ไม่นะ เล่าปี่",
    type: "Life",
    soi: 2,
    print: "SD07-021",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป สามารถ อัญเชิญ Avatar สีเขียว ที่ Cost 4 หรือต่ำกว่า 1 ใบ จากมือลงบน Avatar Zone ฝ่ายเรา",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ โจโฉ",
    type: "Life",
    soi: 2,
    print: "SD07-022",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป สามารถ อัญเชิญ Avatar สีฟ้า ที่ Cost 4 หรือต่ำกว่า 1 ใบ จากมือลงบน Avatar Zone ฝ่ายเรา",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ ซุนกวน",
    type: "Life",
    soi: 2,
    print: "SD07-023",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป สามารถ อัญเชิญ Avatar สีแดง ที่ Cost 4 หรือต่ำกว่า 1 ใบ จากมือลงบน Avatar Zone ฝ่ายเรา",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ตั๋งโต๊ะตายแล้วววว",
    type: "Life",
    soi: 2,
    print: "SD07-024",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
  {
    name: "ไม่นะ อาม่า",
    type: "Life",
    soi: 2,
    print: "SD07-025",
    rare: "C",
    mainEffect: "ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ",
    favorText: "",
    dropRate: "1 / กล่อง",
  },
];
