import { Card } from '@/src/types/cards';

export const CARDS_SD08: Card[] = [
  {
    name: 'ไพรมอล รัททาทุย',
    type: 'Avatar',
    soi: 3,
    print: 'SD08-001',
    rare: 'UR',
    mainEffect:
      'เทิร์นละครั้ง สั่งใช้ : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 จํานวน 1 ใบ จากใน Deck หรือ นรก เรา ลงบน Avatar Zone ฝ่ายเรา ถ้า อัญเชิญ จาก Deck ให้สับ Deck\nเทิร์นละครั้ง อัตโนมัติ เมื่อ Avatar ใบนี้จะออกจากสนาม เนรเทศ การ์ด {symbol รัททาทุย} ในนรกเรา 5 ใบ : Avatar ใบนี้จะไม่ออกจากสนาม\nสั่งใช้ เมื่อ Avatar ใบนี้โจมตี เซ่นไหว้ Avatar {symbol รัททาทุย} ฝ่ายเรา 1 ใบ : เปลี่ยนสภาพ Avatar ใบนี้เป็นสภาพตื่น',
    cost: 6,
    gem: 2,
    power: 6,
    symbol: 'รัททาทุย',
    color: 'ฟ้า',
    ex: 'Only #1',
  },
  {
    name: 'ไพรมอล รัททาทุย',
    type: 'Avatar',
    soi: 3,
    print: 'SD08-001',
    rare: 'PR',
    mainEffect:
      'เทิร์นละครั้ง สั่งใช้ : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 จํานวน 1 ใบ จากใน Deck หรือ นรก เรา ลงบน Avatar Zone ฝ่ายเรา ถ้า อัญเชิญ จาก Deck ให้สับ Deck\nเทิร์นละครั้ง อัตโนมัติ เมื่อ Avatar ใบนี้จะออกจากสนาม เนรเทศ การ์ด {symbol รัททาทุย} ในนรกเรา 5 ใบ : Avatar ใบนี้จะไม่ออกจากสนาม\nสั่งใช้ เมื่อ Avatar ใบนี้โจมตี เซ่นไหว้ Avatar {symbol รัททาทุย} ฝ่ายเรา 1 ใบ : เปลี่ยนสภาพ Avatar ใบนี้เป็นสภาพตื่น',
    cost: 6,
    gem: 2,
    power: 6,
    symbol: 'รัททาทุย',
    color: 'ฟ้า',
    ex: 'Only #1',
  },
  {
    name: 'ไพรมอล รัททาทุย',
    type: 'Avatar',
    soi: 3,
    print: 'SD08-001',
    rare: 'CBR',
    mainEffect:
      'เทิร์นละครั้ง สั่งใช้ : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 จํานวน 1 ใบ จากใน Deck หรือ นรก เรา ลงบน Avatar Zone ฝ่ายเรา ถ้า อัญเชิญ จาก Deck ให้สับ Deck\nเทิร์นละครั้ง อัตโนมัติ เมื่อ Avatar ใบนี้จะออกจากสนาม เนรเทศ การ์ด {symbol รัททาทุย} ในนรกเรา 5 ใบ : Avatar ใบนี้จะไม่ออกจากสนาม\nสั่งใช้ เมื่อ Avatar ใบนี้โจมตี เซ่นไหว้ Avatar {symbol รัททาทุย} ฝ่ายเรา 1 ใบ : เปลี่ยนสภาพ Avatar ใบนี้เป็นสภาพตื่น',
    cost: 6,
    gem: 2,
    power: 6,
    symbol: 'รัททาทุย',
    color: 'ฟ้า',
    ex: 'Only #1',
  },
  {
    name: 'รัททาทุย พาหะ',
    type: 'Avatar',
    soi: 3,
    print: 'SD08-002',
    rare: 'C',
    mainEffect:
      'อัตโนมัติ เมื่อ Avatar ใบนี้ต่อสู้ : Avatar ที่ต่อสู้กับ Avatar ใบนี้ POWER -1 #สามารถใส่การ์ดใบนี้ใน Deck ได้มากสุด 50 ใบ',
    cost: 1,
    gem: 1,
    power: 1,
    symbol: 'รัททาทุย',
    color: 'ฟ้า',
    customLimit: 50,
  },
  {
    name: 'รัททาทุย 2 แสนโวลต์',
    type: 'Avatar',
    soi: 3,
    print: 'SD08-004',
    rare: 'C',
    mainEffect:
      'สามัคคี (เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็น สภาพนอนบน และนํา POWER การ์ดนี้ไปเพิ่มให้กับ Avatar เรา ที่ โจมตี จนจบการต่อสู้นั้น)',
    cost: 2,
    gem: 3,
    power: 2,
    symbol: 'รัททาทุย',
    color: 'ฟ้า',
  },
  {
    name: 'รัททาทุย แบงค์',
    type: 'Avatar',
    soi: 3,
    print: 'SD08-009',
    rare: 'C',
    mainEffect: '',
    cost: 2,
    gem: 4,
    power: 2,
    symbol: 'รัททาทุย',
    color: 'ฟ้า'
  },
  {
    name: "เลือกมันสำหรับพวก จน !!!",
    type: "Magic",
    soi: 3,
    print: "SD08-013",
    rare: "C",
    mainEffect:
      "เลือกปฏิบัติ :\n\n1) นำ Avatar Cost 5 หรือต่ำกว่า จาก นรก ฝ่ายเรา  ขึ้นมือ 1 ใบ ยกเว้นการ์ด {only} \n\n2) นำ Avatar ที่มี Cost 5 หรือต่ำกว่า จาก Deck ฝ่ายเรา ขึ้นมือ 1 ใบ ยกเว้นการ์ด  {only} 1 แล้วสับ Deck\n\nถ้า Life Card ของเราถูกหงายตั้งแต่ 4 ใบขึ้นไปและหงายมากกว่าฝ่ายตรงข้าม ทำความสามารถ 1) และ 2)",
    subtype: "Normal",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: 'โดมรัททาทุย',
    type: 'Avatar',
    cost: 3,
    gem: 1,
    power: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-003',
    rare: 'SR',
    dropRate: '',
    soi: 3,
    mainEffect: 'สั่งใช้ เซ่นไหว้ Avatar ใบนี้ และแสดง Construct {symbol รัททาทุย} 1 ใบ จากมือ : ก่อสร้าง การ์ดใบที่แสดง'
  },
  {
    name: 'รัททาทุยกินซาก',
    type: 'Avatar',
    cost: 5,
    gem: 1,
    power: 0,
    symbol: 'รัททาทุย',
    print: 'SD08-005',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'เทิร์นละครั้ง สั่งใช้ เนรเทศ Avatar {symbol รัททาทุย} ในนรกเราชื่อแตกต่างกันกี่ใบก็ได้ : ต่อจำนวนที่เนรเทศ Avatar ใบนี้ POWER+1 จนจบเทิร์น'
  },
  {
    name: 'รัททาทุย พาราไซท์',
    type: 'Avatar',
    symbol: 'รัททาทุย',
    print: 'SD08-006',
    rare: 'C',
    dropRate: '',
    cost: 2,
    power: 2,
    gem: 2,
    soi: 3,
    mainEffect: 'คำสั่งเสีย : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 จำนวน 1 ใบ จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck'
  },
  {
    name: 'รัทาทุย หัวค้อน',
    type: 'Avatar',
    cost: 3,
    gem: 1,
    power: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-007',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'จุติ (เมื่อ Avatar ใบนี้ถูกอัญเชิญลง Avatar Zone แบบจ่าย Cost ด้วยตัวผู้เล่นเอง) : นำ  Construct  {symbol รัททาทุย} 1 ใบจากนรกขึ้นมือ'
  },
  {
    name: 'รัททาทุยโป๊',
    type: 'Avatar',
    cost: 1,
    gem: 1,
    power: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-008',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'โล่มนุษย์ (เมื่อฝ่ายตรงข้ามเลือกเป้าหมายการโจมตี และทำการโจมตี เปลี่ยนการ์ดนี้ที่อยู่บน Avatar Zone ในสภาพตื่นเป็นสภาพนอน และเปลี่ยนเป้าหมายการโจมตีมาที่การ์ดใบนี้แทน )'
  },
  {
    name: 'ตุ๊กตารัททาทุย',
    type: 'Avatar',
    cost: 1,
    gem: 3,
    power: 0,
    symbol: 'รัททาทุย',
    print: 'SD08-010',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol รัททาทุย} เท่านั้น\nเมื่อการ์ดใบนี้ถูกทิ้งเป็นค่า Cost ให้กับ Avatar "รัททาทุย" : อัญเชิญ Avatar รัททาทุย ที่มี Cost 1 GEM 1 POWER 1 1ใบ จากใน Deck ลงบน Avatar Zone ฝ่ายเรา'
  },
  {
    name: 'รัททาทุย เฝ้าทวาร',
    type: 'Avatar',
    cost: 0,
    gem: 3,
    power: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-011',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: ''
  },
  {
    name: 'กรุงโรมใน 1 วัน',
    type: 'Magic',
    subtype: 'Normal',
    cost: 1,
    symbol: 'จอมเวทย์',
    print: 'SD08-012',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'เลือกการ์ด Construct ที่ไม่ใช่ {only} สูงสุดไม่เกิน 2 ใบจากนรกเราที่ Cost รวมกันไม่เกิน 5 ก่อสร้าง Construct นั้น'
  },
  {
    name: 'แพร่พันธ์ุทันใจ',
    type: 'Magic',
    subtype: 'Normal',
    cost: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-014',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'ทิ้ง Avatar {symbol รัททาทุย} จากบนมือกี่ใบก็ได้ จากนั้นอัญเชิญ Avatar {symbol รัททาทุย} 1 ใบ จาก Deck ที่มี Cost ที่รวมกันไม่เกินจาก Cost ของการ์ดที่ทิ้งด้วยความสามารถการ์ดใบนี้'
  },
  {
    name: 'รัททาท่วม',
    type: 'Magic',
    subtype: 'React',
    cost: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-015',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'เมื่อ Avatar {symbol รัททาทุย} ฝ่ายเราถูกทำลาย : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 มากสุด 2 ใบ (อย่างน้อย 1) จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck'
  },
  {
    name: 'นวมรัททาทุย',
    type: 'Magic',
    subtype: 'Modification',
    cost: 3,
    symbol: 'รัททาทุย',
    print: 'SD08-016',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'สวมใส่ได้แค่ Avatar {symbol รัททาทุย} \nAvatar ที่สวมใส่ POWER+1 ตาม Avatar {symbol รัททาทุย} บนสนามฝ่ายเรา'
  },
  {
    name: 'พิภพรัททาทุย',
    type: 'Magic',
    subtype: 'Land',
    cost: 3,
    symbol: 'รัททาทุย',
    print: 'SD08-017',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'ถ้าบน Avatar Zone ของฝ่ายเรา เป็น Avatar {symbol รัททาทุย} ทั้งหมด เราจะสามารถควบคุม Avatar {symbol รัททาทุย} บน Avatar Zone ได้ 6 ใบ\n POWER +2 ให้ Avatar {symbol รัททาทุย} ที่สั่งโจมตีจนจบการต่อสู้นั้น'
  },
  {
    name: 'รังรักรัททาทุย',
    type: 'Construct',
    cost: 3,
    gem: 2,
    power: 3,
    symbol: 'รัททาทุย',
    print: 'SD08-018',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'เมื่อการ์ดใบนี้ก่อสร้าง : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 จำนวน 1 ใบ จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck\n เทิร์นละครั้ง สั่งใช้ : อัญเชิญ Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 จำนวน 1 ใบ จากใน Deck เรา ลงบน Avatar Zone ฝ่ายเรา จากนั้นสับ Deck'
  },
  {
    name: 'วงล้อรัททาทุย',
    type: 'Construct',
    cost: 2,
    gem: 1,
    power: 2,
    symbol: 'รัททาทุย',
    print: 'SD08-019',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'ต่อเนื่อง Avatar {symbol รัททาทุย} ที่มี Cost 1 Gem 1 POWER 1 บน Avatar Zone ฝ่ายเราทุกใบ POWER+1'
  },
  {
    name: 'บ่อหมัก รัททาทุย',
    type: 'Construct',
    cost: 5,
    gem: 4,
    power: 1,
    symbol: 'รัททาทุย',
    print: 'SD08-020',
    rare: 'C',
    dropRate: '',
    soi: 3,
    mainEffect: 'เมื่อการ์ดใบนี้ถูกทิ้งเป็นค่า Cost เพื่ออัญเชิญ Avatar {symbol รัททาทุย} : ก่อสร้าง Construct ใบนี้\nเทิรน์ละครั้ง อัตโนมัติ เมื่อ Avatar {symbol รัททาทุย} ฝ่ายเราถูกทำลาย : จั่วการ์ด 1 ใบ'
  },
  {
    name: 'เฮ้ย รัททาทุย ตาย !',
    type: 'Life',
    print: 'SD08-021',
    rare: 'C',
    dropRate: '',
    soi: 2,
    favorText: '',
    mainEffect: 'ใน Main Phase ถัดไป สามารถ อัญเชิญ Avatar ที่ Cost 4 หรือต่ำกว่า 1 ใบ จากมือลงบน Avatar Zone ฝ่ายเรา'
  },
  {
    name: 'ไม่นะ มณโท !',
    type: 'Life',
    print: 'SD08-022',
    rare: 'C',
    dropRate: '',
    soi: 2,
    favorText: '',
    mainEffect: 'ใน Main Phase ถัดไป อัญเชิญ Avatar 1 ใบ จากนรก ที่มี Cost ไม่เกิน 2 ลงบน Avatar Zone ฝ่ายเรา'
  },
  {
    name: 'เฮ้ย นางพญา ตาย !',
    type: 'Life',
    print: 'SD08-023',
    rare: 'C',
    dropRate: '',
    soi: 2,
    favorText: '',
    mainEffect: 'ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ'
  },
  {
    name: 'เฮ้ย พ่อพันธุ์ ตาย !',
    type: 'Life',
    print: 'SD08-024',
    rare: 'C',
    dropRate: '',
    soi: 2,
    favorText: '',
    mainEffect: 'ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ'
  },
  {
    name: 'เฮ้ย รัททาทุย โป๊ !',
    type: 'Life',
    print: 'SD08-025',
    rare: 'C',
    dropRate: '',
    soi: 2,
    mainEffect: 'ใน Main Phase ถัดไป จั่วการ์ด 1 ใบ',
    favorText: '',
  }
]