import { Card } from '@/src/types/cards';

export const CARDS_SL02: Card[] = [
  {
    name: 'อนันตวดี ราชินีแห่งนาค',
    type: 'Avatar',
    soi: 2,
    print: 'SL02-001',
    rare: 'USEC',
    mainEffect:
      'เมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ Avatar "นาค" ที่เป็น Symbol สัตว์มหัศจรรย์ : POWER + 3 ให้กับ Avatar ที่อัญเชิญ จนจบเทิร์น \nเมื่อการ์ดใบนี้ถูกใช้เป็น Cost เพื่ออัญเชิญ อนันต์ ราชาแห่งนาค Avatar ใบนี้จะถือว่ามี 6 GEM สีแดง\n#การ์ดใบนี้ใช้เป็น Cost การอัญเชิญได้เฉพาะ Avatar {symbol สัตว์}มหัศจรรย์ เท่านั้น',
    cost: 1,
    gem: 4,
    power: 1,
    symbol: 'สัตว์มหัศจรรย์',
    color: 'แดง',
  },
  {
    name: 'ครุฑเวนไตย เจ้ากำลัง',
    type: "Avatar",
    soi: 2,
    print: "SL02-002",
    rare: "USEC",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ นำ Avatar \"ครุฑ\" ที่ไม่ใช่ ครุฑเวนไตย เจ้ากำลัง 1ใบ  หรือ \"ขนมณี แฟลร์\"  1 ใบในนรกเรา กลับใต้ Deck :\nPOWER +3 จนจบเทิร์น",
    cost: 3,
    gem: 2,
    power: 3,
    symbol: "สัตว์มหัศจรรย์",
    color: "ฟ้า",
  },
  {
    name: "เจค นักฆ่ามือเก๋า",
    type: "Avatar",
    soi: 2,
    print: "SL02-003",
    rare: "USEC",
    mainEffect:
      "ลูกฮึด (เมื่อ Avatar ใบนี้ ต่อสู้กับ Avatar ที่มี POWER เท่ากัน และ ไม่มี ลูกฮึด Avatar ใบนี้จะเป็นฝ่ายชนะ)\nอัตโนมัติ เมื่อ Avatar ใบนี้ประกาศโจมตี และ ในนรกเรามีการ์ด ของขวัญที่เมียทิ้งไว้ให้ : สุ่มทิ้งการ์ด 1 ใบบนมือของฝ่ายตรงข้าม\n#เราสามารถควบคุม เจค นักฆ่ามือเก๋า ใน Avatar Zone ได้เพียง 1 ใบเท่านั้น",
    cost: 4,
    gem: 1,
    power: 6,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "เตียวเลี้ยว ขุนพลมือปราบแห่งวุยก๊ก",
    type: "Avatar",
    soi: 2,
    print: "SL02-004",
    rare: "USEC",
    mainEffect:
      "จุติ : สอดแนม 5 ใบ เลือก Avatar \"ขุนพล\" ที่เป็น Symbol ต่างชาติ ที่มีสีเดียวกันกับ Avatar ใบนี้ 1 ใบ จากที่สอดแนม และนำขึ้นมือ การ์ดที่เหลือนำกลับเข้า Deck แล้วสับ\n#Avatar ใบนี้ถือว่าเป็น Avatar สีม่วง ด้วย",
    cost: 4,
    gem: 2,
    power: 4,
    symbol: "ต่างชาติ",
    color: "ฟ้า",
  },
  {
    name: "ง่อวซอรัส",
    type: "Avatar",
    soi: 2,
    print: "SL02-005",
    rare: "USEC",
    mainEffect: "",
    cost: 5,
    gem: 3,
    power: 5,
    symbol: "กะปอม",
    color: "ฟ้า",
  },
  {
    name: "งี่เง่ากับงอแง",
    type: "Avatar",
    soi: 2,
    print: "SL02-006",
    rare: "USEC",
    mainEffect:
      "เทิร์นละครั้ง เลือกปฏิบัติ :\n1) เซ่นไหว้ Avatar ใบนี้ จั่วการ์ด 2 ใบ\n2) ได้รับ ความสามารถ เตะไข่ จนจบเทิร์น จากนั้นทำลาย Avatar ใบนี้ ในช่วง End Phase",
    cost: 2,
    gem: 0,
    power: 1,
    symbol: "สัตว์",
    color: "ม่วง",
  },
  {
    name: "อย่าให้มีครั้งที่ 2",
    type: "Magic",
    soi: 2,
    print: "SL02-007",
    rare: "USEC",
    mainEffect:
      "เมื่อฝ่ายตรงข้ามใช้ {react} : ยกเลิกผลของการ์ดใบนั้น \nการ์ดใบนี้สามารถใช้ได้แม้ว่าในเทิร์นนี้เราใช้ การ์ด {react} ไปแล้ว#สามารถใช้การ์ด อย่าให้มีครั้งที่ 2 ได้ 1 ใบ ต่อเทิร์น เท่านั้น",
    subtype: "React",
    cost: 1,
    symbol: "จอมเวทย์",
  },
  {
    name: "พลังแฝง",
    type: "Magic",
    soi: 2,
    print: "SL02-008",
    rare: "USEC",
    mainEffect: "เมื่อ Avatar ฝ่ายเราต่อสู้ : Avatar ใบนั้น POWER +2 จนจบเทิร์น",
    subtype: "React",
    cost: 2,
    symbol: "จอมเวทย์",
  },
  {
    name: "เอรา นาคเกล็ดเขียว",
    type: "Avatar",
    soi: 2,
    print: "SL02-009",
    rare: "USEC",
    mainEffect: "จุติ : เลือก Avatar \"นาค\" ที่เป็น Symbol สัตว์มหัศจรรย์ 1 ใบ ใน Avatar Zone ฝ่ายเรา Avatar ใบนั้น POWER +2",
    cost: 2,
    gem: 3,
    power: 1,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
  },
  {
    name: "อนันต์ ราชาแห่งนาค",
    type: "Avatar",
    soi: 2,
    print: "SL02-010",
    rare: "USEC",
    mainEffect:
      "เทิร์นละครั้ง สั่งใช้ : Avatar \"นาค\" ที่เป็น symbol สัตว์มหัศจรรย์ ใบอื่น ทุกใบใน Avatar Zone ฝ่ายเรา จะมี POWER เท่ากับ POWER ของ Avatar ใบนี้ จนจบเทิร์น\nอัตโนมัติ เมื่อ Avatar ใบนี้ โจมตี และทำลาย Avatar ฝ่ายตรงข้ามสำเร็จจากการต่อสู้ : ฝ่ายตรงข้าม หงาย LIFE Card 1 ใบ",
    cost: 6,
    gem: 2,
    power: 7,
    symbol: "สัตว์มหัศจรรย์",
    color: "แดง",
    ex: "Only #1",
  },
];
